bedroom_light_wakeup:
  sequence:

    - service: light.turn_off
      entity_id: light.light_bedroom_light

    - service: light.turn_on
      entity_id: light.light_bedroom_light
    
    - service: light.turn_on
      entity_id: light.light_bedroom_light
      data:
        rgb_color: [255, 100, 1]
        brightness: 1

    - delay:
        seconds: 10

    - service: light.turn_on
      entity_id: light.light_bedroom_light
      data:
        brightness: 100
        transition: 1190

    - delay:
        seconds: 1200

    - service: light.turn_on
      entity_id: light.light_bedroom_light
      data:
        brightness: 255
        transition: 290

    - delay:
        seconds: 300

    - service: light.turn_on
      entity_id: light.light_bedroom_light
      data:
        rgb_color: [255, 226, 145]
        brightness: 255
        transition: 300
