wakeup:
  sequence:

    - service: automation.turn_off
      entity_id: automation.bedroom_light_autooff

    # async
    - service: script.turn_on
      entity_id:
        - script.wakeup_espresso
        - script.bedroom_light_wakeup

    - delay:
        minutes: 30

    - service: script.turn_on
      entity_id: script.music_radio_srf4
    
    - service: input_boolean.turn_off
      entity_id: input_boolean.state_sleep

    - delay:
        minutes: 90
    
    - service: light.turn_off
      entity_id: light.light_bedroom

    - service: automation.turn_on
      entity_id: automation.bedroom_light_autooff

    - service: script.music_turn_off


wakeup_espresso:
  sequence:
    - delay:
        minutes: 10
    - service: switch.turn_on
      entity_id: switch.espresso
