wakeup:
  sequence:

    - service: script.turn_on
      entity_id:
        - script.wakeup_espresso
        - script.bedroom_light_wakeup
    
    - service: input_boolean.turn_off
      entity_id: input_boolean.state_sleep


wakeup_espresso:
  sequence:
    - delay:
        minutes: 10
    - service: switch.turn_on
      entity_id: switch.espresso
