wakeup:
  sequence:

    # async
    - service: script.turn_on
      entity_id:
        - script.wakeup_espresso
    
    # sync
    - service: script.bedroom_light_wakeup

    - service: script.music_radio_srf4
      data:
        media_player_entity_id: media_player.home_group
    
    - delay:
        minutes: 5
    
    - service: input_boolean.turn_off
      entity_id: input_boolean.state_sleep

    - delay:
        minutes: 35
    
    - service: media_player.media_stop
      entity_id: media_player.home_group


wakeup_espresso:
  sequence:
    - delay:
        minutes: 10
    - service: switch.turn_on
      entity_id: switch.espresso
