wakeup:
  sequence:

    - service: script.turn_on
      entity_id:
        - script.wakeup_espresso
        - script.bedroom_light_wakeup
    
    - service: input_boolean.turn_off
      entity_id: input_boolean.state_sleep

    - delay:
        minutes: 5

    - service: script.radio
      data:
        media_player_entity_id: media_player.home_group


wakeup_espresso:
  sequence:
    - delay:
        minutes: 10
    - service: switch.turn_on
      entity_id: switch.espresso
