wakeup:
  sequence:

    # async
    - service: script.turn_on
      entity_id:
        - script.wakeup_espresso
        - script.bedroom_light_wakeup

    - delay:
        minutes: 30

    - service: script.music_radio_srf4
      data:
        media_player_entity_id: media_player.home_group
    
    - delay:
        minutes: 5
    
    - service: input_boolean.turn_off
      entity_id: input_boolean.state_sleep

    - delay:
        minutes: 55
    
    - service: light.turn_off
      entity_id: light.light_bedroom_light

    - service: media_player.media_stop
      entity_id: media_player.home_group


wakeup_espresso:
  sequence:
    - delay:
        minutes: 10
    - service: switch.turn_on
      entity_id: switch.espresso
