- alias: Light Aus
  trigger:
    - platform: state
      entity_id: input_select.state_livingroom_light
      to: 'Aus'
  action:
    # lights
    - service: light.turn_off
      entity_id: light.livingroom_front
    - service: light.turn_off
      entity_id: light.livingroom_sofatable
    - service: light.turn_off
      entity_id: light.livingroom_rgbww
    - service: light.turn_off
      entity_id: light.shelly_diningtable
    - service: light.turn_off
      entity_id: light.christmas_light
    - service: light.turn_off
      entity_id: light.wohnzimmer_tv_ambilight
    - service: light.turn_off
      entity_id: light.livingroom_co2


- alias: Light Film
  trigger:
    - platform: state
      entity_id: input_select.state_livingroom_light
      to: 'Film'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.mode_livingroom_light
        option: "{{ states('input_select.state_livingroom_light') }}"
    # lights
    - service: light.turn_off
      entity_id: light.shelly_kitchen
    - service: light.turn_off
      entity_id: light.kitchen
    - service: light.turn_off
      entity_id: light.floor
    - service: light.turn_off
      entity_id: light.light_door
    - service: light.turn_off
      entity_id: light.livingroom_front
    - service: light.turn_off
      entity_id: light.livingroom_sofatable
    - service: light.turn_on
      entity_id: light.livingroom_rgbww
      data:
        brightness_pct: 40
        effect: none
        rgbww_color: [0, 0, 255, 0, 0]
    - service: light.turn_off
      entity_id: light.shelly_diningtable
    - service: light.turn_off
      entity_id: light.christmas_light
    - service: light.turn_on
      entity_id: light.wohnzimmer_tv_ambilight
      data:
        brightness_pct: 50
        effect: 'FOLLOW_VIDEO: NATURAL'
    - service: light.turn_on
      entity_id: light.livingroom_co2


- alias: Light Beamer
  trigger:
    - platform: state
      entity_id: input_select.state_livingroom_light
      to: 'Beamer'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.mode_livingroom_light
        option: "{{ states('input_select.state_livingroom_light') }}"
    # lights
    - service: light.turn_off
      entity_id: light.livingroom_front
    - service: light.turn_off
      entity_id: light.livingroom_sofatable
    - service: light.turn_on
      entity_id: light.livingroom_rgbww
      data:
        brightness_pct: 100
        effect: none
        rgbww_color: [191, 0, 255, 0, 0]
    - service: light.turn_off
      entity_id: light.christmas_light
    - service: light.turn_on
      entity_id: light.wohnzimmer_tv_ambilight
      data:
        brightness_pct: 100
        effect: 'FOLLOW_VIDEO: STANDARD'
    - service: light.turn_on
      entity_id: light.livingroom_co2


- alias: Light Beamer Bright
  trigger:
    - platform: state
      entity_id: input_select.state_livingroom_light
      to: 'Beamer Hell'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.mode_livingroom_light
        option: "{{ states('input_select.state_livingroom_light') }}"
    # lights
    - service: light.turn_off
      entity_id: light.livingroom_front
    - service: light.turn_on
      entity_id: light.livingroom_sofatable
    - service: light.turn_on
      entity_id: light.livingroom_rgbww
      data:
        brightness_pct: 100
        effect: none
        rgbww_color: [0, 0, 0, 0, 150]
    - service: light.turn_off
      entity_id: light.christmas_light
    - service: light.turn_on
      entity_id: light.wohnzimmer_tv_ambilight
      data:
        brightness_pct: 100
        effect: 'FOLLOW_VIDEO: VIVID'
    - service: light.turn_on
      entity_id: light.livingroom_co2


- alias: Light Chill
  trigger:
    - platform: state
      entity_id: input_select.state_livingroom_light
      to: 'Chill'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.mode_livingroom_light
        option: "{{ states('input_select.state_livingroom_light') }}"
    # lights
    - service: light.turn_on
      entity_id: light.livingroom_front
    - service: light.turn_on
      entity_id: light.livingroom_sofatable
    - service: light.turn_on
      entity_id: light.livingroom_rgbww
      data:
        brightness_pct: 100
        effect: none
        rgbww_color: [255, 0, 0, 0, 100]
    - service: light.turn_on
      entity_id: light.livingroom_rgbww
      data:
        effect: rainbow
    - service: light.turn_on
      entity_id: light.shelly_diningtable
    - service: light.turn_on
      entity_id: light.christmas_light
    - service: light.turn_on
      entity_id: light.wohnzimmer_tv_ambilight
      data:
        brightness_pct: 15
        rgb_color: [255, 0, 255]
        effect: 'Mode: manual'
    - service: light.turn_on
      entity_id: light.livingroom_co2


- alias: Light Ambient
  trigger:
    - platform: state
      entity_id: input_select.state_livingroom_light
      to: 'Normal'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.mode_livingroom_light
        option: "{{ states('input_select.state_livingroom_light') }}"
    # lights
    - service: light.turn_on
      entity_id: light.livingroom_front
    - service: light.turn_on
      entity_id: light.livingroom_sofatable
    - service: light.turn_on
      entity_id: light.livingroom_rgbww
      data:
        brightness_pct: 100
        effect: none
        rgbww_color: [0, 0, 0, 0, 255]
    - service: light.turn_on
      entity_id: light.shelly_diningtable
    - service: light.turn_on
      entity_id: light.christmas_light
    - service: light.turn_on
      entity_id: light.wohnzimmer_tv_ambilight
      data:
        brightness_pct: 15
        rgb_color: [255, 0, 255]
        effect: 'Mode: manual'
    - service: light.turn_on
      entity_id: light.livingroom_co2


- alias: Light Hell
  trigger:
    - platform: state
      entity_id: input_select.state_livingroom_light
      to: 'Hell'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.mode_livingroom_light
        option: "{{ states('input_select.state_livingroom_light') }}"
    # lights
    - service: light.turn_on
      entity_id: light.livingroom_front
    - service: light.turn_on
      entity_id: light.livingroom_sofatable
    - service: light.turn_on
      entity_id: light.livingroom_rgbww
      data:
        brightness_pct: 100
        effect: none
        rgbww_color: [255, 255, 255, 255, 255]
    - service: light.turn_on
      entity_id: light.shelly_diningtable
    - service: light.turn_on
      entity_id: light.christmas_light
    - service: light.turn_on
      entity_id: light.wohnzimmer_tv_ambilight
      data:
        brightness_pct: 100
        rgb_color: [255, 255, 255]
        effect: 'Mode: manual'
    - service: light.turn_on
      entity_id: light.livingroom_co2

# - alias: Dimmer
#   trigger:
#     - platform: state
#       entity_id: sensor.dimmer_brightness
#   action:
#     - service: light.turn_on
#       entity_id: light.livingroom_rgbww
#       data_template:
#         brightness: "{{ states('sensor.dimmer_brightness') }}"
