- alias: Livingroom Media ON
  trigger:
    - platform: state
      entity_id: media_player.horizon
      to: 'playing'
    - platform: state
      entity_id: switch.ps4
      to: 'on'
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.state_media
