- alias: Livingroom Motion ON
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_livingroom_1_occupancy
      to: 'on'
    - platform: state
      entity_id: binary_sensor.motion_livingroom_2_occupancy
      to: 'on'
  condition:
    - condition: and
      conditions: !include ../../../condition/light.nosleep.yaml
    - condition: state
      entity_id: input_boolean.state_media
      state: 'off'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.state_livingroom_light
        option: "{{ states('input_select.mode_livingroom_light') }}"

- alias: Livingroom Motion OFF
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_livingroom_1_occupancy
      to: 'off'
      for:
        minutes: 10
    - platform: state
      entity_id: binary_sensor.motion_livingroom_2_occupancy
      to: 'off'
      for:
        minutes: 10
  condition:
    - condition: state
      entity_id: binary_sensor.motion_livingroom_1_occupancy
      state: 'off'
    - condition: state
      entity_id: binary_sensor.motion_livingroom_2_occupancy
      state: 'off'
    - condition: state
      entity_id: input_boolean.state_media
      state: 'off'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.state_livingroom_light
        option: Aus
