- alias: Livingroom Motion ON
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_livingroom_tuya_occupancy
      to: 'on'
  condition:
    - condition: or
      conditions:
      - condition: state
        entity_id: media_player.wohnzimmer_tv
        state: 'off'
      - condition: state
        entity_id: input_select.state_livingroom_light
        state: 'Aus'
  action:
    - service: script.livingroom_light
      data_template:
        mode: "{{ states('input_select.mode_livingroom_light') }}"

- alias: Livingroom Motion ON -> TV
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_livingroom_tuya_occupancy
      to: 'on'
  condition:
    - condition: and
      conditions: !include ../../../condition/awake.yaml
  action:
    - service: switch.turn_on
      entity_id: switch.livingroom_tv_relay

- alias: Livingroom Motion OFF
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_livingroom_tuya_occupancy
      to: 'off'
      for:
        minutes: 15
  condition:
    - condition: state
      entity_id: binary_sensor.motion_livingroom_tuya_occupancy
      state: 'off'
    - condition: state
      entity_id: media_player.wohnzimmer_tv
      state: 'off'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.state_livingroom_light
        option: Aus


- alias: Livingroom Motion OFF Long
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_livingroom_tuya_occupancy
      to: 'off'
      for:
        minutes: 60
  action:
    - service: homeassistant.turn_on
      entity_id: automation.livingroom_motion_off
    - service: input_select.select_option
      data:
        entity_id: input_select.state_livingroom_light
        option: Aus
