- alias: ps4_on
  trigger:
    - platform: state
      entity_id: media_player.playstation_4
      to: 'idle'
  action:
    - service: media_player.turn_on
      entity_id: media_player.wohnzimmer_tv
    - service: media_player.select_source
      entity_id: media_player.wohnzimmer_tv
      data:
        source: HDMI 1
