- alias: switch_diningtable_click_1
  trigger:
    - platform: event
      event_type: shelly_switch_click
      event_data:
        entity_id: binary_sensor.shelly_diningtable_switch
        click_cnt: 1
  action:
    - service: input_boolean.toggle
      entity_id: input_boolean.state_media

- alias: switch_diningtable_click_2
  trigger:
    - platform: event
      event_type: shelly_switch_click
      event_data:
        entity_id: binary_sensor.shelly_diningtable_switch
        click_cnt: 2
  action:
    - service: light.toggle
      entity_id: light.shelly_diningtable
