- alias: Livingroom Switch LEFT
  trigger:
    - platform: state
      entity_id: sensor.0x00158d000254cc4f_click
      to: 'left'
  action:
    - service: input_select.select_previous
      entity_id: input_select.state_livingroom_light

- alias: Livingroom Switch RIGHT
  trigger:
    - platform: state
      entity_id: sensor.0x00158d000254cc4f_click
      to: 'right'
  action:
    - service: input_select.select_next
      entity_id: input_select.state_livingroom_light

- alias: Livingroom Switch BOTH
  trigger:
    - platform: state
      entity_id: sensor.0x00158d000254cc4f_click
      to: 'both'
  action:
    - service: script.vacuum_livingroom_table
