- alias: Livingroom Switch LEFT
  trigger:
    - platform: state
      entity_id: sensor.switch_livingroom_click
      to: 'left'
  action:
    - service: input_select.select_previous
      entity_id: input_select.state_livingroom_light
      data:
        cycle: false

- alias: Livingroom Switch RIGHT
  trigger:
    - platform: state
      entity_id: sensor.switch_livingroom_click
      to: 'right'
  action:
    - service: input_select.select_next
      entity_id: input_select.state_livingroom_light
      data:
        cycle: false

- alias: Livingroom Switch BOTH
  trigger:
    - platform: state
      entity_id: sensor.switch_livingroom_click
      to: 'both'
  action:
    - service: input_boolean.toggle
      entity_id: input_boolean.state_media
