- alias: switch_livingroom_brightness_up_click
  trigger:
    - platform: state
      entity_id: sensor.switch_livingroom_action
      to: 'brightness_up_click'
  action:
    - service: input_select.select_next
      entity_id: input_select.state_livingroom_light
      data:
        cycle: false

- alias: switch_livingroom_brightness_down_click
  trigger:
    - platform: state
      entity_id: sensor.switch_livingroom_action
      to: 'brightness_down_click'
  action:
    - service: input_select.select_previous
      entity_id: input_select.state_livingroom_light
      data:
        cycle: false

# - alias: switch_livingroom_toggle
#   trigger:
#     - platform: state
#       entity_id: sensor.switch_livingroom_action
#       to: 'toggle'
#   action:
#     - service: script.vacuum_room_kitchen

- alias: switch_livingroom_arrow_left_click
  trigger:
    - platform: state
      entity_id: sensor.switch_livingroom_action
      to: 'arrow_left_click'
  action:
    - service: script.ir_receiver_vol_down

- alias: switch_livingroom_arrow_right_click
  trigger:
    - platform: state
      entity_id: sensor.switch_livingroom_action
      to: 'arrow_right_click'
  action:
    - service: script.ir_receiver_vol_up
