- alias: wohnzimmer_tv_on
  id: wohnzimmer_tv_on
  trigger:
    - platform: state
      entity_id: media_player.wohnzimmer_tv
      to: 'on'
  action:
    # scene beamer
    - service: script.livingroom_light
      data:
        mode: Beamer
    - service: script.receiver_on

- alias: wohnzimmer_tv_off
  id: wohnzimmer_tv_off
  trigger:
    - platform: state
      entity_id: media_player.wohnzimmer_tv
      from: 'on'
  action:
    # scene chill
    - service: script.livingroom_light
      data:
        mode: Chill
    - service: script.turn_on
      entity_id: script.receiver_off
    - service: media_player.turn_off
      entity_id: media_player.playstation_4
