- alias: wohnzimmer_tv_on
  trigger:
    - platform: state
      entity_id: media_player.wohnzimmer_tv
      to: 'on'
  action:
    - service: script.receiver_on
    # scene beamer
    - service: input_select.select_option
      data:
        entity_id: input_select.state_livingroom_light
        option: Beamer

- alias: wohnzimmer_tv_off
  trigger:
    - platform: state
      entity_id: media_player.wohnzimmer_tv
      to: 'off'
  action:
    - service: script.receiver_off
    # scene
    - service: input_select.select_option
      data:
        entity_id: input_select.state_livingroom_light
        option: Chill

