# - alias: livingroom_wall_switch_click_1
#   trigger:
#     - platform: event
#       event_type: shelly.click
#       event_data:
#         entity_id: binary_sensor.shelly_diningtable_switch
#         click_cnt: 1
#   action:
#     - choose:
#         - conditions:
#             - condition: state
#               entity_id: media_player.shield_cast
#               state: playing
#           sequence:
#             - service: script.music_turn_off
#       default:
#         - service: script.youtube_music_shield_playlist_chill
#         - service: media_player.volume_set
#           entity_id: media_player.shield_cast
#           data:
#             volume_level: 0.5
#     - service: input_boolean.turn_off
#       entity_id: input_boolean.state_media


# - alias: livingroom_wall_switch_click_2
#   trigger:
#     - platform: event
#       event_type: shelly.click
#       event_data:
#         entity_id: binary_sensor.shelly_diningtable_switch
#         click_cnt: 2
#   action:
#     - service: input_boolean.turn_on
#       entity_id: input_boolean.state_media
