views:
  - badges: []
    title: Home
    path: home
    icon: mdi:home
    cards: !include home.yaml

  - badges: []
    title: Espresso
    path: espresso
    icon: mdi:coffee
    cards: !include espresso.yaml

  - badges: []
    title: Media
    path: media
    icon: mdi:cast-connected
    cards: !include media.yaml
