views:
  - badges: []
    title: Home
    path: home
    icon: mdi:home
    cards: !include home.yaml

  - badges: []
    title: Staubi
    path: vacuum
    icon: mdi:vacuum
    cards: !include vacuum.yaml

  - badges: []
    title: Media
    path: media
    icon: mdi:cast-connected
    cards: !include media.yaml
