- type: vertical-stack
  cards:
    # CO2
    - type: custom:apexcharts-card
      header:
        show: true
        title: CO₂
      graph_span: 72h
      series:
        - entity: sensor.netatmo_home_indoor_co2
          name: Wohnzimmer
          show:
            extremas: true
        - entity: sensor.netatmo_home_indoor_buro_co2
          name: Büro
          show:
            extremas: true

    # Temperatur
    - type: custom:apexcharts-card
      header:
        show: true
        title: Temperatur
      graph_span: 72h
      series:
        - entity: sensor.netatmo_home_indoor_temperature
          name: Wohnzimmer
          show:
            extremas: true
        - entity: sensor.netatmo_home_indoor_buro_temperature
          name: Büro
          show:
            extremas: true
        - entity: sensor.netatmo_home_indoor_aussen_temperature
          name: Aussen
          show:
            extremas: true

    # Feuchtigkeit
    - type: custom:apexcharts-card
      header:
        show: true
        title: Feuchtigkeit
      graph_span: 72h
      series:
        - entity: sensor.netatmo_home_indoor_humidity
          name: Wohnzimmer
          show:
            extremas: true
        - entity: sensor.netatmo_home_indoor_buro_humidity
          name: Büro
          show:
            extremas: true
        - entity: sensor.netatmo_home_indoor_aussen_humidity
          name: Aussen
          show:
            extremas: true
