- type: vertical-stack
  cards:
    - type: custom:apexcharts-card
      header:
        show: true
        title: Kilowattstunden pro Tag
      update_interval: 1m
      graph_span: 30d
      span:
        end: day
      stacked: true
      show:
        last_updated: true
      apex_config:
        yaxis:
          min: 0
      experimental:
        brush: true
      brush:
        selection_span: 7d
        apex_config:
          yaxis:
            min: 0
      all_series_config:
        unit: kWh
        type: column
        float_precision: 2
        fill_raw: zero
        group_by:
          func: diff
          duration: 1d
          fill: zero
      series:
        - entity: sensor.shelly_powermeter_phase_a_total_active_energy
          name: A
        - entity: sensor.shelly_powermeter_phase_b_total_active_energy
          name: B (Fitnesszimmer)
        - entity: sensor.shelly_powermeter_phase_c_total_active_energy
          name: C (Küche)
          show:
            datalabels: total
        - entity: sensor.shelly_powermeter_total_active_energy
          name: Total
          type: column
          show:
            in_brush: true
            in_chart: false
    
    - type: custom:apexcharts-card
      header:
        show: true
        title: Kosten pro Tag
      update_interval: 1m
      graph_span: 30d
      span:
        end: day
      stacked: true
      show:
        last_updated: true
      apex_config:
        yaxis:
          min: 0
      experimental:
        brush: true
      brush:
        selection_span: 7d
        apex_config:
          yaxis:
            min: 0
      all_series_config:
        unit: CHF
        type: column
        float_precision: 2
        transform: "return x * 0.25;"
        fill_raw: zero
        group_by:
          func: diff
          duration: 1d
          fill: zero
      series:
        - entity: sensor.shelly_powermeter_phase_a_total_active_energy
          name: A
        - entity: sensor.shelly_powermeter_phase_b_total_active_energy
          name: B (Fitnesszimmer)
        - entity: sensor.shelly_powermeter_phase_c_total_active_energy
          name: C (Küche)
          show:
            datalabels: total
        - entity: sensor.shelly_powermeter_total_active_energy
          name: Total
          show:
            in_brush: true
            in_chart: false

    - type: custom:apexcharts-card
      header:
        show: true
        title: Wattstunden
      update_interval: 1m
      graph_span: 3d
      span:
        end: day
      show:
        last_updated: true
      apex_config:
        yaxis:
          min: 0
      experimental:
        brush: true
      brush:
        selection_span: 1d
        apex_config:
          yaxis:
            min: 0
      all_series_config:
        unit: Wh
        stroke_width: 2
        extend_to: false
        fill_raw: zero
        group_by:
          func: avg
          duration: 1h
          fill: zero
      series:
        - entity: sensor.shelly_powermeter_phase_a_active_power
          name: A
        - entity: sensor.shelly_powermeter_phase_b_active_power
          name: B (Fitnesszimmer)
        - entity: sensor.shelly_powermeter_phase_c_active_power
          name: C (Küche)
        - entity: sensor.shelly_powermeter_active_power
          name: Total
          type: column
          show:
            in_brush: true

    - type: custom:apexcharts-card
      header:
        show: true
        title: Wattminuten
      update_interval: 1m
      graph_span: 12h
      show:
        last_updated: true
      apex_config:
        yaxis:
          min: 0
      experimental:
        brush: true
      brush:
        selection_span: 1h
        apex_config:
          yaxis:
            min: 0
      all_series_config:
        unit: Wmin
        stroke_width: 2
        extend_to: false
        fill_raw: zero
        group_by:
          func: avg
          duration: 1m
          fill: zero
      series:
        - entity: sensor.shelly_powermeter_phase_a_active_power
          name: A
        - entity: sensor.shelly_powermeter_phase_b_active_power
          name: B (Fitnesszimmer)
        - entity: sensor.shelly_powermeter_phase_c_active_power
          name: C (Küche)
        - entity: sensor.shelly_powermeter_active_power
          name: Total
          type: column
        - entity: sensor.shelly_powermeter_active_power
          name: Total
          type: column
          group_by:
            func: avg
            duration: 15m
            fill: zero
          show:
            in_brush: true
            in_chart: false

    - type: custom:apexcharts-card
      header:
        show: true
        title: Watt (Relativ)
      update_interval: 15s
      graph_span: 5m
      stacked: true
      show:
        last_updated: true
      all_series_config:
        unit: W
        type: column
        fill_raw: zero
        group_by:
          func: avg
          duration: 15s
          fill: zero
      series:
        - entity: sensor.shelly_powermeter_phase_a_active_power_dt
          name: A
        - entity: sensor.shelly_powermeter_phase_b_active_power_dt
          name: B (Fitnesszimmer)
        - entity: sensor.shelly_powermeter_phase_c_active_power_dt
          name: C (Küche)
