- type: custom:xiaomi-vacuum-map-card
  entity: vacuum.staubi
  vacuum_platform: default
  map_source:
    camera: camera.xiaomi_cloud_map_extractor
  calibration_source:
    camera: true
  map_locked: true
  two_finger_pan: false
  append_icons: true
  icons:
    - icon: mdi:sync
      tap_action:
        action: call-service
        service: homeassistant.update_entity
        service_data:
          entity_id: camera.xiaomi_cloud_map_extractor
  append_tiles: true
  tiles:
    - label: Letzte Dauer
      entity: sensor.staubi_last_clean_duration
      icon: mdi:timer
      multiplier: 0.017
      precision: 1
      unit: min
  map_modes:
    - template: vacuum_clean_segment
      max_repeats: 10
      predefined_selections:
        - id: '16'
          icon:
            name: mdi:bed
            x: 29800
            y: 22650
          outline:
            - [28350, 20300]
            - [31250, 20300]
            - [31250, 25000]
            - [28350, 25000]
        - id: '17'
          icon:
            name: mdi:pot-steam
            x: 33375
            y: 26900
          outline:
            - [31450, 26250]
            - [35300, 26250]
            - [35300, 27500]
            - [31450, 27500]
        - id: '18'
          icon:
            name: mdi:desk
            x: 32800
            y: 29650
          outline:
            - [30300, 28150]
            - [35250, 28150]
            - [35250, 31150]
            - [30300, 31150]
        - id: '19'
          icon:
            name: mdi:door
            x: 30000
            y: 26600
          outline:
            - [28600, 25050]
            - [31400, 25050]
            - [31400, 28150]
            - [28600, 28150]
        - id: '20'
          icon:
            name: mdi:table-furniture
            x: 33400
            y: 24725
          outline:
            - [31450, 23250]
            - [35350, 23250]
            - [35350, 26200]
            - [31450, 26200]
        - id: '21'
          icon:
            name: mdi:toilet
            x: 27900
            y: 27075
          outline:
            - [27300, 26200]
            - [28500, 26200]
            - [28500, 27950]
            - [27300, 27950]
        - id: '22'
          icon:
            name: mdi:shower
            x: 26500
            y: 27050
          outline:
            - [25850, 26200]
            - [27150, 26200]
            - [27150, 27900]
            - [25850, 27900]
        - id: '23'
          icon:
            name: mdi:floor-plan
            x: 27000
            y: 25600
          outline:
            - [25200, 25050]
            - [28600, 25050]
            - [28600, 26150]
            - [25200, 26150]
        - id: '24'
          icon:
            name: mdi:sofa
            x: 33425
            y: 21800
          outline:
            - [31500, 20400]
            - [35350, 20400]
            - [35350, 23200]
            - [31500, 23200]
    - template: vacuum_goto_predefined
      predefined_selections:
        - position: [32300, 26550]
          icon:
            name: "mdi:broom"
            x: 32300
            y: 26550
        - position: [26900, 25500]
          icon:
            name: "mdi:broom"
            x: 26900
            y: 25500
    - template: vacuum_clean_zone
      max_repeats: 10
    - template: vacuum_goto
    - template: vacuum_follow_path
