# - platform: mqtt
#   name: kitchen_lightswitch
#   state_topic: "shellies/kitchen/input/0"
#   command_topic: "shellies/kitchen/input/0/command"
#   availability_topic: "shellies/kitchen/online"
#   payload_on: "1"
#   payload_off: "0"
#   state_on: "1"
#   state_off: "0"
#   retain: true

# - platform: mqtt
#   name: bedroom_lightswitch
#   state_topic: "shellies/bedroom/input/0"
#   command_topic: "shellies/bedroom/input/0/command"
#   availability_topic: "shellies/bedroom/online"
#   payload_on: "1"
#   payload_off: "0"
#   state_on: "1"
#   state_off: "0"
#   retain: true

# - platform: mqtt
#   name: wc_lightswitch
#   state_topic: "shellies/wc/input/0"
#   command_topic: "shellies/wc/input/0/command"
#   availability_topic: "shellies/wc/online"
#   payload_on: "1"
#   payload_off: "0"
#   state_on: "1"
#   state_off: "0"
#   retain: true

# - platform: mqtt
#   name: bathroom_lightswitch
#   state_topic: "shellies/bathroom/input/0"
#   command_topic: "shellies/bathroom/input/0/command"
#   availability_topic: "shellies/bathroom/online"
#   payload_on: "1"
#   payload_off: "0"
#   state_on: "1"
#   state_off: "0"
#   retain: true

# - platform: mqtt
#   name: workroom_lightswitch
#   state_topic: "shellies/workroom/input/0"
#   command_topic: "shellies/workroom/input/0/command"
#   availability_topic: "shellies/workroom/online"
#   payload_on: "1"
#   payload_off: "0"
#   state_on: "1"
#   state_off: "0"
#   retain: true

# - platform: mqtt
#   name: fitnessroom_lightswitch
#   state_topic: "shellies/fitnessroom/input/0"
#   command_topic: "shellies/fitnessroom/input/0/command"
#   availability_topic: "shellies/fitnessroom/online"
#   payload_on: "1"
#   payload_off: "0"
#   state_on: "1"
#   state_off: "0"
#   retain: true
