- platform: mqtt
  name: livingroom_bass
  state_topic: "homie/livingroom-bass/switch/state"
  command_topic: "homie/livingroom-bass/switch/state/set"
  retain: true

- platform: mqtt
  name: espresso
  state_topic: "homie/espresso/switch/state"
  command_topic: "homie/espresso/switch/state/set"
  retain: true

- platform: mqtt
  name: humidifier
  state_topic: "homie/livingroom-steamer/switch/state"
  command_topic: "homie/livingroom-steamer/switch/state/set"
  retain: true

- platform: mqtt
  name: resin
  state_topic: "homie/resin/switch/state"
  command_topic: "homie/resin/switch/state/set"
  retain: true

- platform: command_line
  switches:
    ps4:
      command_on: "echo on"
      command_off: "echo off"
      command_state: "nc -z -w 5 {{ !secret ps4_ip }} 9295"
