# Single
espresso_mill_calibrate_single:
  sequence:
    - service: input_number.set_value
      entity_id: input_number.espresso_mill_time_single
      data_template:
        value: >
          {% set current_time = states('input_number.espresso_mill_time_single') | float %}
          {% set current_amount = states('input_number.espresso_mill_amount_measure_single') | float %}
          {% set target_amount = states('input_number.espresso_mill_amount_single') | float %}
          {% set new_time = (0.5 * current_time) + (0.5 * current_time * target_amount / current_amount) %}
          {{ new_time | round(2) }}
    - service: input_number.set_value
      entity_id: input_number.espresso_mill_amount_measure_single
      data_template:
        value: "{{ states('input_number.espresso_mill_amount_single') }}"

# Double
espresso_mill_calibrate_double:
  sequence:
    - service: input_number.set_value
      entity_id: input_number.espresso_mill_time_double
      data_template:
        value: >
          {% set current_time = states('input_number.espresso_mill_time_double') | float %}
          {% set current_amount = states('input_number.espresso_mill_amount_measure_double') | float %}
          {% set target_amount = states('input_number.espresso_mill_amount_double') | float %}
          {% set new_time = (0.5 * current_time) + (0.5 * current_time * target_amount / current_amount) %}
          {{ new_time | round(2) }}
    - service: input_number.set_value
      entity_id: input_number.espresso_mill_amount_measure_double
      data_template:
        value: "{{ states('input_number.espresso_mill_amount_double') }}"
