homeassistant:
  # Name of the location where Home Assistant is running
  name: Home Assistant
  # Location required to calculate the time the sun rises and set
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Zurich

  customize: !include customize.yaml

system_health:

frontend:

http:
  base_url: !secret base_url

updater:

recorder:
  purge_keep_days: 30
  # include:
  #   domains:
  #     - light
  #     - switch
  #     - input_boolean
  #     - sensor
    # entities:
    #   - sensor.plant1_moisture
    #   - sensor.plant1_conductivity
    #   - sensor.plant2_moisture
    #   - sensor.plant2_conductivity
    #   - sensor.plant3_moisture
    #   - sensor.plant3_conductivity
    #   - sensor.temperature_espresso
    #   - sensor.humidity_espresso
    #   - sensor.temperature_livingroom
    #   - sensor.humidity_livingroom

history:

# logbook:

config:

automation: !include automations.yaml
automation old: !include_dir_merge_list config/automation
sensor: !include_dir_merge_list config/entity/sensor/sensor
binary_sensor: !include_dir_merge_list config/entity/sensor/binary_sensor
switch: !include_dir_merge_list config/entity/switch
light: !include_dir_merge_list config/entity/light
input_boolean: !include_dir_merge_named config/entity/input/boolean
input_select: !include_dir_merge_named config/entity/input/select
scene: !include_dir_merge_list config/scene
group: !include_dir_merge_named config/group
script: !include_dir_merge_named config/script

sun:

mqtt:
  discovery: true
  broker: localhost

shelly:
  discovery: true
  version: false #add version sensor
  sensors:
    - switch
  devices:
    - id: "8CAAB505F04A"
      name: Lichtschalter Schlafzimmer
      entity_id: bedroom
      light_switch: true
    - id: "E098068CC71C"
      name: Licht Küchenzeile
      entity_id: kitchen
      light_switch: true
    - id: "E098068DA426"
      name: Licht WC
      entity_id: wc
      light_switch: true
    - id: "8CAAB505EDCA"
      name: Licht Badzimmer
      entity_id: bathroom
      light_switch: true
    - id: "E098068CC7E3"
      name: Lichtschalter Büro
      entity_id: workroom
      light_switch: true
    - id: "E098068DA79E"
      name: Licht Fitnesszimmer
      entity_id: fitnessroom
      light_switch: true
    - id: "F3C4C0"
      name: Licht Esstisch
      entity_id: diningtable
      light_switch: true

device_tracker:
  - platform: ddwrt
    host: !secret ddwrt_ip
    username: !secret ddwrt_username
    password: !secret ddwrt_password
    interval_seconds: 60
    consider_home: 180
    track_new_devices: yes

google_assistant:
  project_id: !secret google_project_id
  service_account: !include google_assistant_service_account.json
  expose_by_default: false
  entity_config:
    # 1 Wohnzimmer
    input_boolean.state_media:
      expose: true
      name: Media
      room: '1 Wohnzimmer'
      aliases:
        - Beamer
    # 2 Küche
    switch.espresso:
      expose: true
      room: '2 Küche'
    # 3 Schlafzimmer
    input_boolean.state_sleep:
      expose: true
      room: '3 Schlafzimmer'
    light.light_bedroom_light:
      expose: true
      room: '3 Schlafzimmer'
    # Scenes
    script.bedroom_light_wakeup:
      expose: true
      name: Licht WakeUp
    script.vacuum_kitchen:
      expose: true
      name: Küche staubsaugen
    script.vacuum_livingroom:
      expose: true
      name: Wohnzimmer staubsaugen
    script.vacuum_livingroom_table:
      expose: true
      name: Sofatisch staubsaugen

plant:
  plant1:
    sensors:
      moisture: sensor.plant1_moisture
      battery: sensor.plant1_battery
      temperature: sensor.plant1_temperature
      conductivity: sensor.plant1_conductivity
      brightness: sensor.plant1_light
    min_moisture: 20
    max_moisture: 60
    min_battery: 17
    min_conductivity: 500
    min_temperature: 15
  plant2:
    sensors:
      moisture: sensor.plant2_moisture
      battery: sensor.plant2_battery
      temperature: sensor.plant2_temperature
      conductivity: sensor.plant2_conductivity
      brightness: sensor.plant2_light
    min_moisture: 20
    max_moisture: 60
    min_battery: 17
    min_conductivity: 500
    min_temperature: 15
  plant3:
    sensors:
      moisture: sensor.plant3_moisture
      battery: sensor.plant3_battery
      temperature: sensor.plant3_temperature
      conductivity: sensor.plant3_conductivity
      brightness: sensor.plant3_light
    min_moisture: 20
    max_moisture: 60
    min_battery: 17
    min_conductivity: 500
    min_temperature: 15

tts:
  - platform: google_translate
    service_name: google_say
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300

notify:
  - name: flo
    platform: pushbullet
    api_key: !secret pushbullet_api_key
  - name: google
    platform: rest
    resource: http://localhost:5000/broadcast_message

vacuum:
  - name: xiaomi_vacuum
    platform: xiaomi_miio
    host: rockrobo
    token: !secret xiaomi_vaccum_token

webhook:

zigbee2mqtt_networkmap:
  #topic: y40:31:3C:A8:41:E4our topic (optional, default zigbee2mqtt)
panel_iframe:
  networkmap:
    title: 'ZigBee'
    url: '/local/community/zigbee2mqtt_networkmap/map.html'
    icon: 'mdi:graphql'
