homeassistant:
  # Name of the location where Home Assistant is running
  name: Home Assistant
  # Location required to calculate the time the sun rises and set
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Zurich

  customize: !include_dir_merge_named config/customize

frontend:

http: !include config/http.yaml

updater:

recorder:
  include:
    domains:
      - light
      - switch
      - device_tracker
      - binary_sensor
      - sensor

history:

logbook:

config:

panel_iframe: !include config/panel.yaml

sun:

lirc:

mqtt:
  broker: localhost

zone: !include config/zones.yaml

device_tracker:
  - platform: ddwrt
    host: !secret ddwrt_ip
    username: !secret ddwrt_username
    password: !secret ddwrt_password
    interval_seconds: 60
    consider_home: 180
    track_new_devices: yes

  - platform: owntracks

# media_player:
#   - platform: horizon
#     host: 192.168.0.3

# vacuum:
#   - platform: xiaomi_miio
#     name: "Staubi"
#     host: 192.168.0.133
#     token: "3249544c437648434d32433441345454"

notify:
  - name: flo
    platform: pushbullet
    api_key: !secret pushbullet_flo_api_key

sensor: !include config/sensors.yaml

binary_sensor: !include config/binary_sensors.yaml

switch: !include config/switches.yaml

light: !include config/lights.yaml

input_number: !include config/input_sliders.yaml

input_select: !include_dir_merge_named config/input_select

input_boolean: !include config/input_boolean.yaml

group: !include_dir_merge_named config/group

scene: !include_dir_merge_list config/scene

automation: !include automations.yaml
automation old: !include_dir_merge_list config/automation

script: !include_dir_merge_named config/script
