default_config:

homeassistant:
  packages: !include_dir_named custom_config/packages
  auth_providers:
    - type: trusted_networks
      allow_bypass_login: true
      trusted_networks:
        - 192.168.0.0/16
    - type: homeassistant

automation ui: !include automations.yaml
script ui: !include scripts.yaml
scene ui: !include scenes.yaml

mqtt: !include custom_config/mqtt.yaml

frontend:
  themes: !include_dir_merge_named themes

lovelace:
  mode: storage

panel_custom:
  - name: config/logs
    sidebar_title: Logs
    sidebar_icon: mdi:math-log
    module_url: logs
