homeassistant:
  # Name of the location where Home Assistant is running
  name: Home Assistant
  # Location required to calculate the time the sun rises and set
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Zurich

  customize: !include customize.yaml

frontend:

http:
  base_url: !secret base_url
  server_port: 443
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key

updater:

recorder:
  include:
    domains:
      - light
      - switch
      - device_tracker
      - binary_sensor
      - sensor

history:

logbook:

config:

sun:

lirc:

mqtt:
  discovery: true
  broker: localhost

device_tracker:
  - platform: ddwrt
    host: !secret ddwrt_ip
    username: !secret ddwrt_username
    password: !secret ddwrt_password
    interval_seconds: 60
    consider_home: 180
    track_new_devices: yes

  - platform: owntracks

google_assistant:
  project_id: !secret google_project_id
  api_key: !secret google_api_key
  exposed_domains:
    - light
  entity_config:
    media_player.horizon:
      expose: true
    switch.resin:
      expose: true
    switch.livingroom_bass:
      expose: true
    switch.espresso:
      expose: true
    switch.humidifier:
      expose: true
    input_boolean.state_sleep:
      expose: true
    input_boolean.state_media:
      expose: true
      name: Media
      aliases:
        - Beamer

tts:
  - platform: google
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300

media_player:
  - platform: horizon
    host: !secret horizon_ip

notify:
  - name: flo
    platform: pushbullet
    api_key: !secret pushbullet_api_key
  - name: google
    platform: rest
    resource: http://localhost:5000/broadcast_message

automation: !include automations.yaml
automation old: !include_dir_merge_list config/automation
sensor: !include_dir_merge_list config/entity/sensor/sensor
binary_sensor: !include_dir_merge_list config/entity/sensor/binary_sensor
switch: !include_dir_merge_list config/entity/switch
light: !include_dir_merge_list config/entity/light
input_boolean: !include_dir_merge_named config/entity/input/boolean
input_select: !include_dir_merge_named config/entity/input/select
scene: !include_dir_merge_list config/scene
group: !include_dir_merge_named config/group
script: !include_dir_merge_named config/script
