title: Home Assistant
views:

  ####################  Home Tab ####################
  - badges: []
    title: Home
    path: lovelace-home
    icon: 'mdi:home'
    cards:
    
      ####################  Main  ####################
      - type: entities
        show_header_toggle: false
        entities:
          
          ####################  States  ####################
          - type: buttons
            entities:
              - entity: input_boolean.state_home
                icon: 'mdi:home'
              - entity: input_boolean.state_sleep
                icon: 'mdi:sleep'
              - entity: input_boolean.state_media
                icon: 'mdi:projector-screen'

          - type: section

          ####################  Lights  ####################
          # Esstisch
          # - type: 'custom:slider-entity-row'
          #   entity: light.shelly_diningtable
          #   name: Esstisch
          #   toggle: true

          # Wohnzimmer
          - type: 'custom:multiple-entity-row'
            entity: light.livingroom_led_rgb
            name: Wohnzimmer
            icon: mdi:lightbulb-group
            show_state: false
            entities:
              - entity: input_select.state_livingroom_light
                name: false
          - type: buttons
            entities:
              - entity: input_select.state_livingroom_light
                icon: 'mdi:track-light'
                tap_action:
                  action: call-service
                  service: input_select.select_option
                  service_data:
                    entity_id: input_select.state_livingroom_light
                    option: Hell
              - entity: input_select.state_livingroom_light
                icon: 'mdi:lightbulb-group'
                tap_action:
                  action: call-service
                  service: input_select.select_option
                  service_data:
                    entity_id: input_select.state_livingroom_light
                    option: Normal
              - entity: input_select.state_livingroom_light
                icon: 'mdi:lightbulb-multiple'
                tap_action:
                  action: call-service
                  service: input_select.select_option
                  service_data:
                    entity_id: input_select.state_livingroom_light
                    option: Chill
              - entity: input_select.state_livingroom_light
                icon: 'mdi:lightbulb'
                tap_action:
                  action: call-service
                  service: input_select.select_option
                  service_data:
                    entity_id: input_select.state_livingroom_light
                    option: Beamer Hell
              - entity: input_select.state_livingroom_light
                icon: 'mdi:projector-screen'
                tap_action:
                  action: call-service
                  service: input_select.select_option
                  service_data:
                    entity_id: input_select.state_livingroom_light
                    option: Beamer
              - entity: input_select.state_livingroom_light
                icon: 'mdi:movie-open'
                tap_action:
                  action: call-service
                  service: input_select.select_option
                  service_data:
                    entity_id: input_select.state_livingroom_light
                    option: Film
              - entity: input_select.state_livingroom_light
                icon: 'mdi:lightbulb-group-off'
                tap_action:
                  action: call-service
                  service: input_select.select_option
                  service_data:
                    entity_id: input_select.state_livingroom_light
                    option: Aus

          # Schlafzimmer
          - type: 'custom:slider-entity-row'
            entity: light.light_bedroom_light
            name: Schlafzimmer
            toggle: true

          # Büro
          - type: 'custom:slider-entity-row'
            entity: light.light_workroom_light
            toggle: true

          # Fitnesszimmer
          - name: Fitnesszimmer
            entity: light.shelly_fitnessroom

          # Eingang
          - type: 'custom:multiple-entity-row'
            entity: light.floor
            name: Eingang
            show_state: false
            entities:
              - entity: light.light_door_light
                name: Türe
                toggle: true
              - entity: light.floor
                name: Gang
                toggle: true

          # WC
          - type: 'custom:multiple-entity-row'
            entity: light.shelly_wc
            name: WC
            show_state: false
            entities:
              - entity: light.wc
                name: LED
                toggle: true
              - entity: light.shelly_wc
                name: Lavabo
                toggle: true

          # Badezimmer
          - type: 'custom:multiple-entity-row'
            entity: light.shelly_bathroom
            name: Badezimmer
            show_state: false
            entities:
              - entity: light.bathroom_led
                name: LED
                toggle: true
              - entity: light.shelly_bathroom
                name: Lavabo
                toggle: true

      ####################  Espresso  ####################
      # Toggle
      - type: entities
        name: Espresso
        entities:
          - type: 'custom:multiple-entity-row'
            entity: switch.espresso
            name: Espresso
            icon: mdi:coffee
            state_color: true
            toggle: true
            entities:
              - entity: sensor.temperature_espresso
                name: false
          # Chart
          - type: 'custom:mini-graph-card'
            entities:
              - entity: sensor.temperature_espresso
                show_points: false
            animate: true
            height: 100
            line_width: 1
            decimals: 1
            hour24: true
            hours_to_show: 8
            points_per_hour: 30
            group: true
            show:
              name: false
              icon: false
              state: false
              labels: true
            color_thresholds:
              - value: 0
                color: '#0000ff'
              - value: 50
                color: '#0000ff'
              - value: 55
                color: '#ff0000'
              - value: 65
                color: '#ff0000'


  ####################  Temperatur Tab  ####################
  - badges: []
    title: Temperatur
    path: lovelace-temperature
    icon: 'mdi:thermometer'
    panel: true
    cards:

      - type: vertical-stack
        cards:

          ####################  Innen  ####################
          - type: horizontal-stack
            cards:
              # Temperatur
              - type: 'custom:mini-graph-card'
                name: Temperatur
                icon: mdi:thermometer
                entities:
                  - entity: sensor.netatmo_home_indoor_temperature
                    name: Wohnzimmer
                    show_points: false
                  - entity: sensor.netatmo_home_indoor_buro_temperature
                    name: Büro
                    show_points: false
                animate: true
                height: 400
                line_width: 1
                decimals: 1
                hour24: true
                hours_to_show: 24
                points_per_hour: 6
                tap_action: none
                show:
                  labels: true
                  icon_adaptive_color: true
                color_thresholds:
                  - value: 30
                    color: "#ff0000"
                  - value: 23
                    color: "#00ff00"
                  - value: 15
                    color: "#0000ff"
              # Feuchtigkeit
              - type: 'custom:mini-graph-card'
                name: Feuchtigkeit
                icon: mdi:water-percent
                entities:
                  - entity: sensor.netatmo_home_indoor_humidity
                    name: Wohnzimmer
                    show_points: false
                  - entity: sensor.netatmo_home_indoor_buro_humidity
                    name: Büro
                    show_points: false
                animate: true
                height: 400
                line_width: 1
                hour24: true
                hours_to_show: 24
                points_per_hour: 6
                tap_action:
                  action: more-info
                  entity: switch.humidifier
                show:
                  labels: true
                  icon_adaptive_color: true
                color_thresholds:
                  - value: 30
                    color: "#ff0000"
                  - value: 45
                    color: "#00ff00"
                  - value: 60
                    color: "#0000ff"
          - type: horizontal-stack
            cards:
              # CO2
              - type: 'custom:mini-graph-card'
                name: CO²
                icon: mdi:molecule-co2
                entities:
                  - entity: sensor.netatmo_home_indoor_co2
                    name: Wohnzimmer
                    show_points: false
                  - entity: sensor.netatmo_home_indoor_buro_co2
                    name: Büro
                    show_points: false
                animate: true
                height: 400
                line_width: 1
                hour24: true
                hours_to_show: 24
                points_per_hour: 6
                tap_action: none
                show:
                  labels: true
                  icon_adaptive_color: true
                color_thresholds:
                  - value: 1600
                    color: "#ff0000"
                  - value: 400
                    color: "#00ff00"
              # Luftdruck
              - type: 'custom:mini-graph-card'
                name: Luftdruck
                icon: mdi:gauge
                entities:
                  - entity: sensor.netatmo_home_indoor_pressure
                    name: Wohnzimmer
                    show_points: false
                animate: true
                height: 400
                line_width: 1
                decimals: 1
                hour24: true
                hours_to_show: 24
                points_per_hour: 6
                tap_action: none
                show:
                  labels: true
                  icon_adaptive_color: true


          ####################  Aussen  ####################
          - type: horizontal-stack
            title: Aussen
            cards:
              # Temperatur
              - type: 'custom:mini-graph-card'
                name: Temperatur
                icon: mdi:thermometer
                entities:
                  - entity: sensor.netatmo_home_indoor_aussen_temperature
                    name: Aussen
                    show_points: false
                animate: true
                height: 400
                line_width: 1
                decimals: 1
                hour24: true
                hours_to_show: 168
                points_per_hour: 6
                tap_action: none
                show:
                  labels: true
                  icon_adaptive_color: true
                color_thresholds:
                  - value: 35
                    color: "#ff0000"
                  - value: 20
                    color: "#00ff00"
                  - value: 5
                    color: "#0000ff"
              # Feuchtigkeit
              - type: 'custom:mini-graph-card'
                name: Feuchtigkeit
                icon: mdi:water-percent
                entities:
                  - entity: sensor.netatmo_home_indoor_aussen_humidity
                    name: Aussen
                    show_points: false
                animate: true
                height: 400
                line_width: 1
                hour24: true
                hours_to_show: 168
                points_per_hour: 6
                tap_action: none
                show:
                  labels: true
                  icon_adaptive_color: true
                color_thresholds:
                  - value: 30
                    color: "#ff0000"
                  - value: 45
                    color: "#00ff00"
                  - value: 60
                    color: "#0000ff"


  ####################  Pflanzen  ####################
  - badges: []
    title: Pflanzen
    path: 'lovelance-plant'
    icon: mdi:flower
    panel: true
    cards:

      - type: vertical-stack
        cards:

          # Wasser
          - type: 'custom:mini-graph-card'
            name: Wasser
            entities:
              - entity: sensor.plant1_moisture
                name: Busch
                show_points: false
              - entity: sensor.plant2_moisture
                name: Baum
                show_points: false
              - entity: sensor.plant3_moisture
                name: Rosmarin
                show_points: false
            animate: true
            height: 240
            line_width: 1
            decimals: 0
            hour24: true
            hours_to_show: 720
            points_per_hour: 0.2
            lower_bound: 0
            upper_bound: 100
            tap_action: none
            show:
              icon_adaptive_color: true
            color_thresholds:
              - value: 20
                color: '#ff0000'
              - value: 40
                color: '#00ff00'
              - value: 60
                color: '#00ff00'
              - value: 80
                color: '#ff9800'

          # Dünger
          - type: 'custom:mini-graph-card'
            name: Dünger
            entities:
              - entity: sensor.plant1_conductivity
                name: Busch
                show_points: false
              - entity: sensor.plant2_conductivity
                name: Baum
                show_points: false
              - entity: sensor.plant3_conductivity
                name: Rosmarin
                show_points: false
            animate: true
            height: 240
            line_width: 1
            decimals: 0
            hour24: true
            hours_to_show: 720
            points_per_hour: 0.2
            lower_bound: 0
            upper_bound: 3000
            tap_action: none
            show:
              icon_adaptive_color: true
            color_thresholds:
              - value: 300
                color: '#ff0000'
              - value: 800
                color: '#00ff00'
              - value: 2000
                color: '#00ff00'
              - value: 2500
                color: '#ff9800'
