- condition: or
  conditions:
    - condition: and
      conditions: !include night.yaml
    - condition: numeric_state
      entity_id: sensor.motion_office_illuminance
      below: 100
    - condition: numeric_state
      entity_id: sensor.motion_office_tuya_illuminance
      below: 1500
