- condition: state
  entity_id: input_boolean.state_home
  state: 'on'
- condition: or
  conditions:
    - condition: sun
      after: sunset
    - condition: sun
      before: sunrise
    - condition: numeric_state
      entity_id: sensor.motion_livingroom_1_illuminance
      below: 40
    - condition: numeric_state
      entity_id: sensor.motion_livingroom_2_illuminance
      below: 40
