type: entities
show_header_toggle: false
entities:
  - entity: input_boolean.state_home
    type: custom:multiple-entity-row
    name: false
    icon: mdi
    show_state: false
    entities:
      - entity: input_boolean.state_home
        icon: mdi:home
        state_color: true
        name: false
        tap_action:
          action: toggle
      - entity: input_boolean.state_sleep
        icon: mdi:sleep
        state_color: true
        name: false
        tap_action:
          action: toggle
      - entity: input_boolean.state_media
        icon: mdi:projector-screen
        state_color: true
        name: false
        tap_action:
          action: toggle

  - entity: light.shelly_diningtable
    type: custom:slider-entity-row
    name: Esstisch

  - entity: light.livingroom_led_rgb
    type: custom:multiple-entity-row
    name: Wohnzimmer
    show_state: false
    entities:
      - icon: mdi:lightbulb-multiple
        tap_action:
          action: call-service
          service: input_select.select_option
          service_data:
            entity_id: input_select.state_livingroom_light
            option: Chill
      - icon: mdi:lightbulb-group
        tap_action:
          action: call-service
          service: input_select.select_option
          service_data:
            entity_id: input_select.state_livingroom_light
            option: Hell
      - icon: mdi:lightbulb-group-off
        tap_action:
          action: call-service
          service: input_select.select_option
          service_data:
            entity_id: input_select.state_livingroom_light
            option: Aus

  - entity: light.livingroom_led_rgb
    type: custom:multiple-entity-row
    name: false
    icon: mdi
    show_state: false
    entities:
      - icon: mdi:lightbulb
        tap_action:
          action: call-service
          service: input_select.select_option
          service_data:
            entity_id: input_select.state_livingroom_light
            option: Beamer Hell
      - icon: mdi:projector-screen
        tap_action:
          action: call-service
          service: input_select.select_option
          service_data:
            entity_id: input_select.state_livingroom_light
            option: Beamer
      - icon: mdi:movie-open
        tap_action:
          action: call-service
          service: input_select.select_option
          service_data:
            entity_id: input_select.state_livingroom_light
            option: Film

  - entity: light.light_bedroom_light
    type: custom:slider-entity-row
    name: Schlafzimmer

  - entity: light.light_workroom_light
    type: custom:slider-entity-row
  
  - entity: light.shelly_fitnessroom
    name: Fitnesszimmer

  - entity: light.floor
    type: custom:multiple-entity-row
    name: Eingang
    show_state: false
    entities:
      - entity: light.light_door_light
        name: Türe
        toggle: true
      - entity: light.floor
        name: Gang
        toggle: true

  - entity: light.shelly_wc
    type: custom:multiple-entity-row
    name: WC
    show_state: false
    entities:
      - entity: light.wc
        name: LED
        toggle: true
      - entity: light.shelly_wc
        name: Lavabo
        toggle: true

  - entity: light.shelly_bathroom
    type: custom:multiple-entity-row
    name: Badezimmer
    show_state: false
    entities:
      - entity: light.bathroom_led
        name: LED
        toggle: true
      - entity: light.shelly_bathroom
        name: Lavabo
        toggle: true
