- platform: template
  sensors:

    weather_temperature:
      friendly_name: "Wetter Temperatur"
      unit_of_measurement: 'degrees'
      value_template: "{{ state_attr('weather.home', 'temperature') }}"

    weather_humidity:
      friendly_name: "Wetter Luftfeuchtigkeit"
      unit_of_measurement: 'percent'
      value_template: "{{ state_attr('weather.home', 'humidity') }}"
