- platform: template
  sensors:
    workroom_light_temp:
      value_template: >
        {% set coldLightTemp = 250 %}
        {% set warmLightTemp = 454 %}
        {% set risingTime = as_datetime(state_attr('sun.sun', 'next_rising')).replace(year=1, month=1, day=1) %}
        {% set settingTime = as_datetime(state_attr('sun.sun', 'next_setting')).replace(year=1, month=1, day=1) - timedelta(hours=1) %}
        {% set duskTime = as_datetime(state_attr('sun.sun', 'next_dusk')).replace(year=1, month=1, day=1) %}
        {% set nowTime = utcnow().replace(year=1, month=1, day=1) %}

        {% if nowTime < risingTime or nowTime > duskTime %}
            {% set lightTemp = warmLightTemp %}
        {% elif nowTime < settingTime %}
            {% set lightTemp = coldLightTemp %}
        {% else %}
            {% set coldWarmLightTempDiff = warmLightTemp - coldLightTemp %}
            {% set settingToDuskTimeDiff = duskTime - settingTime %}
            {% set timeToDusk = duskTime - nowTime%}
            {% set timeToDuskRatio = 1 - (timeToDusk / settingToDuskTimeDiff) %}
            {% set lightTemp = coldLightTemp + int(timeToDuskRatio * coldWarmLightTempDiff) %}
        {% endif %}
        {{ lightTemp }}

- platform: template
  sensors:
    workroom_light_desk_ambilight:
      value_template: >
        {% set x = states('sensor.netatmo_home_indoor_buro_co2') | int %}

        {% set x_1 = 400 %}
        {% set x_2 = 2000 %}
        {% set y_1 = 120 %}
        {% set y_2 = 360 %}

        {% set dt = (y_2 - y_1) / (x_2 - x_1) %}
        {% set b = y_1 - dt * x_1 %}
        {% set y = x * dt + b %}

        {% set y = min(max(y,y_1),y_2) | int %}

        {{ y }}
