- type: entities
  entities:
    - type: custom:fold-entity-row
      open: true
      head:
        entity: script.cellar_charge
        name: Ladestation
      entities:
        - type: custom:fold-entity-row
          open: true
          head:
            entity: switch.ebike
            name: E-Bike
          entities:
            - entity: input_select.ebike_charging_limit
              name: E-Bike Akku Limite
              icon: mdi:battery-unknown
        - type: custom:fold-entity-row
          open: true
          head:
            entity: switch.cellar_charger
            name: Ladegeräte
          entities:
            - entity: input_number.cellar_charger_hours
              name: Ladegeräte Stunden
              icon: mdi:battery-unknown

# Charts
- type: custom:mini-graph-card
  entities:
    - entity: sensor.ebike_power
      name: Power
      show_points: false
  animate: true
  height: 100
  line_width: 1
  decimals: 1
  hour24: true
  hours_to_show: 168
  points_per_hour: 12
  show:
    name: true
    icon: true
    state: true
    labels: true
    icon_adaptive_color: true
    extrema: true
    average: true
  color_thresholds:
    - value: 0
      color: '#ff0000'
    - value: 140
      color: '#00ff00'
- type: custom:mini-graph-card
  entities:
    - entity: sensor.ebike_temperature
      name: Temperatur
      show_points: false
  animate: true
  height: 100
  line_width: 1
  decimals: 1
  hour24: true
  hours_to_show: 168
  points_per_hour: 1
  show:
    name: true
    icon: true
    state: true
    labels: true
    icon_adaptive_color: true
    extrema: true
    average: true
  color_thresholds:
    - value: 10
      color: '#0000ff'
    - value: 15
      color: '#00ff00'
    - value: 25
      color: '#ff0000'
