- type: entities
  name: E-Bike
  entities:
    - type: custom:fold-entity-row
      open: true
      head:
        type: custom:multiple-entity-row
        entity: switch.mystrom_1
        name: E-Bike
        icon: mdi:bike
        state_color: true
        toggle: false
        show_state: false
        entities:
          - entity: sensor.mystrom_1_power
            name: false
          - entity: switch.mystrom_1
            name: E-Bike
            toggle: true
          - entity: switch.cellar_charger
            name: Ladegeräte
            toggle: true
          - entity: switch.cellar_charger_led
            name: Laden
            toggle: true
      entities:
        - entity: input_select.ebike_charging_limit
          name: E-Bike Akku Limite
          icon: mdi:battery-unknown
        - entity: input_number.cellar_charger_hours
          name: Ladegeräte Stunden
          icon: mdi:ev-station

# Charts
- type: custom:mini-graph-card
  entities:
    - entity: sensor.mystrom_1_power
      name: Power
      show_points: false
  animate: true
  height: 100
  line_width: 1
  decimals: 1
  hour24: true
  hours_to_show: 168
  points_per_hour: 4
  show:
    name: true
    icon: true
    state: true
    labels: true
    icon_adaptive_color: true
    extrema: true
    average: true
  color_thresholds:
    - value: 0
      color: '#00ff00'
    - value: 150
      color: '#ff0000'
- type: custom:mini-graph-card
  entities:
    - entity: sensor.mystrom_1_temperature
      name: Temperatur
      show_points: false
  animate: true
  height: 100
  line_width: 1
  decimals: 1
  hour24: true
  hours_to_show: 168
  points_per_hour: 4
  show:
    name: true
    icon: true
    state: true
    labels: true
    icon_adaptive_color: true
    extrema: true
    average: true
  color_thresholds:
    - value: 10
      color: '#0000ff'
    - value: 15
      color: '#00ff00'
    - value: 25
      color: '#ff0000'
