- name: livingroom_ambient
  entities:
    light.livingroom_rainbow: on
    light.livingroom_front: on
    light.livingroom_big: off
    light.livingroom_sofatable: on
    light.livingroom_led_rgb:
      state: on
      rgb_color: [255, 0, 0]
      brightness: 255
    light.livingroom_led_white_front:
      state: on
      brightness: 255
    light.livingroom_led_white_back:
      state: on
      brightness: 255
    light.shelly_diningtable:
      state: on
      brightness: 75

- name: livingroom_chill
  entities:
    light.livingroom_rainbow: on
    light.livingroom_front: on
    light.livingroom_big: off
    light.livingroom_sofatable: on
    light.livingroom_led_rgb:
      state: on
      effect: rainbow
      brightness: 255
    light.livingroom_led_white_front: off
    light.livingroom_led_white_back: off
    light.shelly_diningtable:
      state: on
      brightness: 75

- name: livingroom_bright
  entities:
    light.livingroom_rainbow: on
    light.livingroom_front: on
    light.livingroom_big: on
    light.livingroom_sofatable: on
    light.livingroom_led_rgb:
      state: on
      effect: rainbow
      brightness: 255
    light.livingroom_led_white_front: off
    light.livingroom_led_white_back: off
    light.shelly_diningtable:
      state: on
      brightness: 255

- name: livingroom_beamer
  entities:
    light.livingroom_rainbow: on
    light.livingroom_front: off
    light.livingroom_big: off
    light.livingroom_sofatable: off
    light.livingroom_led_rgb:
      state: on
      effect: rainbow
      brightness: 20
    light.livingroom_led_white_front: off
    light.livingroom_led_white_back: off
    light.shelly_diningtable: off

- name: livingroom_beamer_bright
  entities:
    light.livingroom_rainbow: on
    light.livingroom_front: off
    light.livingroom_big: off
    light.livingroom_sofatable: on
    light.livingroom_led_rgb:
      state: on
      effect: rainbow
      brightness: 50
    light.livingroom_led_white_front: off
    light.livingroom_led_white_back:
      state: on
      brightness: 255
    light.shelly_diningtable:
      state: on
      brightness: 75

- name: livingroom_film
  entities:
    light.shelly_kitchen: off
    light.kitchen: off
    light.floor: off
    light.light_door_light: off
    light.livingroom_rainbow: off
    light.livingroom_front: off
    light.livingroom_big: off
    light.livingroom_sofatable: off
    light.livingroom_led_rgb:
      state: on
      rgb_color: [255, 204, 0]
      brightness: 2
    light.livingroom_led_white_front: off
    light.livingroom_led_white_back:
      state: on
      brightness: 1
    light.shelly_diningtable: off
