- name: livingroom_bright
  entities:
    light.livingroom_front: on
    light.livingroom_sofatable: on
    light.livingroom_rgbww:
      state: on
      brightness_pct: 100
      effect: none
      rgbww_color: [255, 255, 255, 255, 255]
    light.shelly_diningtable: on
    light.christmas_light: on

- name: livingroom_ambient
  entities:
    light.livingroom_front: on
    light.livingroom_sofatable: on
    light.livingroom_rgbww:
      state: on
      brightness_pct: 100
      effect: none
      rgbww_color: [255, 0, 0, 0, 255]
    light.shelly_diningtable: on
    light.christmas_light: on

- name: livingroom_chill
  entities:
    light.livingroom_front: on
    light.livingroom_sofatable: on
    light.livingroom_rgbww:
      state: on
      brightness_pct: 100
      effect: rainbow_ww40
    light.shelly_diningtable: on
    light.christmas_light: on

- name: livingroom_beamer_bright
  entities:
    light.livingroom_front: off
    light.livingroom_sofatable: on
    light.livingroom_rgbww:
      state: on
      brightness_pct: 50
      effect: none
      rgbww_color: [0, 0, 0, 0, 255]
    light.christmas_light: on

- name: livingroom_beamer
  entities:
    light.livingroom_front: off
    light.livingroom_sofatable: off
    light.livingroom_rgbww:
      state: on
      brightness_pct: 20
      effect: rainbow

- name: livingroom_film
  entities:
    light.shelly_kitchen: off
    light.kitchen: off
    light.floor: off
    light.light_door: off
    light.livingroom_front: off
    light.livingroom_sofatable: off
    light.livingroom_rgbww:
      state: on
      brightness_pct: 20
      effect: none
      rgbww_color: [0, 0, 255, 0, 0]
    light.shelly_diningtable: off
    light.christmas_light: off

- name: livingroom_off
  entities:
    light.livingroom_front: off
    light.livingroom_sofatable: off
    light.livingroom_rgbww: off
    light.christmas_light: off