- name: all_off
  entities:
    input_select.state_livingroom_light:
      option: Aus
    group.all_lights: off
    group.all_switches: off

- name: livingroom_ambient
  entities:
    light.livingroom_rainbow: on
    light.livingroom_front: on
    light.livingroom_big: off
    light.livingroom_sofatable: on
    light.livingroom_led_rgb:
      state: on
      effect: rainbow-light
      brightness: 255
    light.livingroom_led_white_front:
      state: on
      brightness: 255
    light.livingroom_led_white_back:
      state: on
      brightness: 255

- name: livingroom_bright
  entities:
    light.livingroom_rainbow: on
    light.livingroom_front: off
    light.livingroom_big: on
    light.livingroom_sofatable: off
    light.livingroom_led_rgb:
      state: on
      effect: rainbow
      brightness: 255
    light.livingroom_led_white_front: off
    light.livingroom_led_white_back: off

- name: livingroom_beamer
  entities:
    light.livingroom_rainbow: on
    light.livingroom_front: off
    light.livingroom_big: off
    light.livingroom_sofatable: off
    light.livingroom_led_rgb:
      state: on
      effect: rainbow
      brightness: 20
    light.livingroom_led_white_front: off
    light.livingroom_led_white_back:
      state: on
      brightness: 50

- name: livingroom_beamer_bright
  entities:
    light.livingroom_rainbow: on
    light.livingroom_front: off
    light.livingroom_big: off
    light.livingroom_sofatable: on
    light.livingroom_led_rgb:
      state: on
      effect: rainbow
      brightness: 50
    light.livingroom_led_white_front: off
    light.livingroom_led_white_back:
      state: on
      brightness: 255
