- alias: key_media_power_pressed
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: KEY_POWER
  action:
    - service: input_boolean.toggle
      entity_id: input_boolean.state_media


- alias: ir_horizon_volumeup_pressed
  trigger:
    platform: event
    event_type: ir_command_received
    event_data:
      button_name: KEY_VOLUMEUP
  action:
    - service: script.ir_receiver_vol_up


- alias: ir_horizon_volumedown_pressed
  trigger:
    platform: event
    event_type: ir_command_received
    event_data:
      button_name: KEY_VOLUMEDOWN
  action:
    - service: script.ir_receiver_vol_down


- alias: ir_horizon_mute_pressed
  trigger:
    platform: event
    event_type: ir_command_received
    event_data:
      button_name: KEY_MUTE
  action:
    - service: switch.toggle
      entity_id: switch.livingroom_bass
