- type: 'custom:multiple-entity-row'
  entity: switch.mystrom_1
  name: E-Bike
  icon: mdi:bike
  state_color: true
  toggle: false
  show_state: false
  entities:
    - entity: sensor.mystrom_1_power
      name: false
    - entity: script.cellar_charge_ebike_90
      name: Full
    - entity: switch.mystrom_1
      name: E-Bike
      toggle: true
    - entity: switch.cellar_charger
      name: Ladegeräte
      toggle: true
    - entity: switch.cellar_charger_led
      name: Laden
      toggle: true
# Chart
- type: 'custom:mini-graph-card'
  entities:
    - entity: sensor.mystrom_1_power
      show_points: false
  animate: true
  height: 100
  line_width: 1
  decimals: 1
  hour24: true
  hours_to_show: 24
  points_per_hour: 30
  group: true
  show:
    name: false
    icon: false
    state: false
    labels: true
  color_thresholds:
    - value: 0
      color: '#00ff00'
    - value: 150
      color: '#ff0000'
