########## Radio ##########
music_radio_srf4:
  sequence:
    - service: media_player.play_media
      data_template:
        entity_id: "{{ media_player_entity_id }}"
        media_content_id: "{{ states('input_text.radio_srf4') }}"
        media_content_type: music


########## Playlist ##########
youtube_music_shield_playlist_chill:
  sequence:
    - service: script.youtube_music_shield_playlist
      data:
        playlist_entity_id: input_text.playlist_chill

youtube_music_playlist_sleep:
  sequence:
    - service: media_player.select_source
      entity_id: media_player.youtube_music
      data:
        source: schlafzimmer_assistent
    - service: media_player.play_media
      entity_id: media_player.youtube_music
      data_template:
        media_content_id: "{{ states('input_text.playlist_sleep') }}"
        media_content_type: playlist


########## Youtube - Play ##########
youtube_music_shield_playlist:
  sequence:
    - service: script.youtube_music_shield_play
      data_template:
        media_content_id: "{{ states(playlist_entity_id) }}"
        media_content_type: playlist

youtube_music_shield_play:
  sequence:
    - service: script.turn_on
      entity_id: script.receiver_on
    - service: media_player.turn_off
      entity_id: media_player.shield_cast
    - service: media_player.select_source
      entity_id: media_player.youtube_music
      data:
        source: shield_cast
    - service: media_player.shuffle_set
      entity_id: media_player.youtube_music
      data:
        shuffle: true
    - service: media_player.play_media
      entity_id: media_player.youtube_music
      data_template:
        media_content_id: "{{ media_content_id }}"
        media_content_type: "{{ media_content_type }}"


########## Youtube - Add to playlist ##########
youtube_music_add_to_playlist_from_entity_id:
  sequence:
    - service: ytube_music_player.add_to_playlist
      data_template:
        entity_id: media_player.youtube_music
        playlist_id: "{{ states(playlist_entity_id) }}"


########## Youtube - Remove from playlist ##########
youtube_music_remove_from_playlist_from_entity_id:
  sequence:
    - service: ytube_music_player.remove_from_playlist
      data_template:
        entity_id: media_player.youtube_music
        playlist_id: "{{ states(playlist_entity_id) }}"