radio:
  sequence:
    - service: media_player.play_media
      data_template:
        entity_id: "{{ media_player_entity_id }}"
        media_content_id: "{{ states('input_text.radio_srf4') }}"
        media_content_type: music
