music_turn_off:
  sequence:
    - service: media_player.turn_off
      entity_id: media_player.wohnzimmer_assistent
    - service: media_player.turn_off
      entity_id: media_player.schlafzimmer_assistent
    - service: media_player.turn_off
      entity_id: media_player.home_group
