views:
  - badges: []
    title: Klima
    path: climate
    icon: mdi:thermometer
    cards: !include climate.yaml

  - badges: []
    title: Pflanzen
    path: plants
    icon: mdi:flower
    cards: !include plants.yaml