- alias: WC Motion ON
  id: wc motion on
  trigger:
    platform: state
    entity_id: binary_sensor.motion_wc
    to: 'on'
  condition: !include ../../../condition/illuminance_livingroom.yaml
  action:
    service: light.turn_on
    entity_id: light.wc


- alias: WC Motion OFF
  id: wc motion off
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_wc
      to: 'off'
      for:
        minutes: 5
  action:
    service: light.turn_off
    entity_id: light.wc


- alias: WC Motion OFF
  id: wc motion off
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_wc
      to: 'off'
      for:
        minutes: 5
  action:
    service: light.turn_off
    entity_id: light.shelly_wc
