- type: entities
  show_header_toggle: false
  name: Main
  entities: !include main/main.yaml

- type: entities
  name: Espresso
  entities: !include espresso/espresso.yaml

- type: entities
  name: E-Bike
  entities: !include ebike/ebike.yaml
