- alias: fitnessroom_motion_off_long
  id: fitnessroom_motion_off_long
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_fitnessroom_occupancy
      to: 'off'
      for:
        minutes: 120
  action:
    - service: light.turn_off
      entity_id: light.shelly_fitnessroom
