- alias: fitnessroom_switch_1
  trigger:
    - platform: event
      event_type: shelly_switch_click
      event_data:
        entity_id: binary_sensor.shelly_fitnessroom_switch
        click_cnt: 1
  action:
    - service: light.toggle
      entity_id: light.shelly_fitnessroom


- alias: fitnessroom_switch_2_on
  trigger:
    - platform: event
      event_type: shelly_switch_click
      event_data:
        entity_id: binary_sensor.shelly_fitnessroom_switch
        click_cnt: 2
  condition:
    - condition: state
      entity_id: input_boolean.state_fitnessroom
      state: 'off'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.state_fitnessroom
    - service: light.turn_on
      entity_id: light.shelly_fitnessroom


- alias: fitnessroom_switch_2_off
  trigger:
    - platform: event
      event_type: shelly_switch_click
      event_data:
        entity_id: binary_sensor.shelly_fitnessroom_switch
        click_cnt: 2
  condition:
    - condition: state
      entity_id: input_boolean.state_fitnessroom
      state: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.state_fitnessroom
    - service: light.turn_off
      entity_id: light.shelly_fitnessroom
