
- alias: Door Open
  trigger:
    - platform: state
      entity_id: binary_sensor.sensor_door_contact
      to: 'on'
  action:
    - service: script.turn_off
      entity_id: script.not_home
    - service: script.home


- alias: Door Close
  trigger:
    - platform: state
      entity_id: binary_sensor.sensor_door_contact
      to: 'off'
  action:
    - service: script.not_home
