
- alias: Door Open
  trigger:
    - platform: state
      entity_id: binary_sensor.sensor_door_contact
      to: 'on'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.state_home
    # light
    - condition: and
      conditions: !include ../../../condition/light_livingroom.yaml
    - service: light.turn_on
      entity_id: light.light_door
    - service: light.turn_on
      entity_id: light.floor
