
- alias: Door Open
  id: door_open
  trigger:
    - platform: state
      entity_id: binary_sensor.sensor_door_contact
      to: 'on'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.state_home
    - service: input_boolean.turn_off
      entity_id: input_boolean.state_sleep
    # light
    - condition: and
      conditions: !include ../../../condition/light_livingroom.yaml
    - service: light.turn_on
      entity_id: light.light_door
    - service: light.turn_on
      entity_id: light.floor


- alias: Door Close
  id: door_close
  trigger:
    - platform: state
      entity_id: binary_sensor.sensor_door_contact
      to: 'off'
      for:
        minutes: 10
  condition:
    - condition: state
      entity_id: group.people
      state: 'not_home'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.state_home
