
- alias: Door Open
  trigger:
    - platform: state
      entity_id: binary_sensor.0x00158d00032b6a0a_contact
      to: 'on'
  action:
    - service: script.home


- alias: Door Close
  trigger:
    - platform: state
      entity_id: binary_sensor.0x00158d00032b6a0a_contact
      to: 'off'
  action:
    - service: script.not_home
