- alias: Floor Switch LEFT
  trigger:
    - platform: state
      entity_id: sensor.switch_door_action
      to: 'single_left'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.state_home

- alias: Floor Switch RIGHT
  trigger:
    - platform: state
      entity_id: sensor.switch_door_action
      to: 'single_right'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.state_sleep
