- alias: Floor Switch LEFT
  trigger:
    - platform: state
      entity_id: sensor.switch_door_click
      to: 'left'
  action:
    - service: script.turn_off
      entity_id: script.not_home
    - service: script.home
    - service: light.turn_on
      entity_id: light.floor
    - service: light.turn_on
      entity_id: light.light_door


- alias: Floor Switch RIGHT
  trigger:
    - platform: state
      entity_id: sensor.switch_door_click
      to: 'right'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.state_sleep


- alias: Floor Switch BOTH Clean
  trigger:
    - platform: state
      entity_id: sensor.switch_door_click
      to: 'both'
  condition:
    - condition: state
      entity_id: vacuum.staubi
      state: 'docked'
  action:
    - service: vacuum.start
      entity_id: vacuum.staubi

- alias: Floor Switch BOTH Clean Stop
  trigger:
    - platform: state
      entity_id: sensor.switch_door_click
      to: 'both'
  condition:
    - condition: state
      entity_id: vacuum.staubi
      state: 'cleaning'
  action:
    - service: script.vacuum_home_stop
