- alias: Floor Switch LEFT
  trigger:
    - platform: state
      entity_id: sensor.switch_door_action
      to: 'single_left'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.state_home
    - service: input_boolean.turn_off
      entity_id: input_boolean.state_sleep
    - service: light.turn_on
      entity_id: light.floor
    - service: light.turn_on
      entity_id: light.light_door


- alias: Floor Switch RIGHT
  trigger:
    - platform: state
      entity_id: sensor.switch_door_action
      to: 'single_right'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.state_sleep


- alias: Floor Switch BOTH Clean
  trigger:
    - platform: state
      entity_id: sensor.switch_door_action
      to: 'single_both'
  condition:
    - condition: state
      entity_id: vacuum.staubi
      state: 'docked'
  action:
    - service: script.vacuum_start

- alias: Floor Switch BOTH Clean Stop
  trigger:
    - platform: state
      entity_id: sensor.switch_door_action
      to: 'single_both'
  condition:
    - condition: state
      entity_id: vacuum.staubi
      state: 'cleaning'
  action:
    - service: script.vacuum_stop
