- alias: Floor Switch LEFT
  trigger:
    - platform: state
      entity_id: sensor.switch_door_click
      to: 'left'
  action:
    - service: light.turn_on
      entity_id: light.light_door_light


- alias: Floor Switch RIGHT
  trigger:
    - platform: state
      entity_id: sensor.switch_door_click
      to: 'right'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.state_sleep


- alias: Floor Switch BOTH
  trigger:
    - platform: state
      entity_id: sensor.switch_door_click
      to: 'both'
  action:
    - service: vacuum.start
      entity_id: vacuum.xiaomi_vacuum
