bedroom_light_wakeup:
  sequence:

    - service: light.turn_on
      entity_id: light.light_bedroom_light
      data:
        transition: 0
        brightness: 1
        rgb_color: [255, 100, 1]

    - delay:
        seconds: 5

    - service: light.turn_on
      entity_id: light.light_bedroom_light
      data:
        transition: 900
        brightness: 1
        rgb_color: [1,190,255]

    - delay:
        seconds: 1

    - service: light.turn_on
      entity_id: light.light_bedroom_light
      data:
        transition: 900
        brightness: 255
