bedroom_light_wakeup:
  sequence:

    - service: light.turn_on
      entity_id: light.light_bedroom_light
      data:
        transition: 0
        rgb_color: [255, 100, 1]
        brightness: 1

    - delay:
        seconds: 3

    - service: light.turn_on
      entity_id: light.light_bedroom_light
      data:
        transition: 300
        brightness: 255

    - delay:
        seconds: 400

    - service: light.turn_on
      entity_id: light.light_bedroom_light
      data:
        transition: 500
        rgb_color: [255, 226, 145]
