bedroom_light_wakeup:
  sequence:

    - service: light.turn_on
      entity_id: light.light_bedroom_light
    
    - service: light.turn_on
      entity_id: light.light_bedroom_light
      data:
        rgb_color: [255, 100, 1]
        brightness: 1

    - delay:
        seconds: 3

    - service: light.turn_on
      entity_id: light.light_bedroom_light
      data:
        transition: 1200
        brightness: 255

    - service: light.turn_on
      entity_id: light.light_bedroom_light
      data:
        transition: 600
        rgb_color: [255, 226, 145]
