state_livingroom_light:
  name: Wohnzimmer Licht
  options:
    - Aus
    - Film
    - Beamer
    - Beamer Hell
    - Chill
    - Normal
    - Hell

mode_livingroom_light:
  name: Wohnzimmer Licht Mode
  options:
    - Film
    - Beamer
    - Beamer Hell
    - Chill
    - Normal
    - Hell
