state_bedroom_light_color:
  name: Farbe
  options:
    - Weiss
    - Gelb
    - Orange
    - Rot
    - Pink
    - Violett
    - Blau
    - Grün

state_bedroom_light_brightness:
  name: Helligkeit
  options:
    - 1%
    - 33%
    - 66%
    - 100%
