sensor.livingroom_temperature:
  friendly_name: Wohnzimmer Temperatur

sensor.livingroom_humidity:
  friendly_name: Wohnzimmer Feuchtigkeit
  icon: mdi:water

sensor.kitchen_temperature:
  friendly_name: Küche Temperatur

sensor.kitchen_humidity:
  friendly_name: Küche Feuchtigkeit
  icon: mdi:water

sensor.mold_indicator:
  friendly_name: Luftverschmutzung
  icon: mdi:notification-clear-all

switch.livingroom_humidifier:
  friendly_name: Luftbefeuchter
  icon: mdi:water

switch.resin:
  friendly_name: Brunnen
  icon: mdi:water