# views
group.default_view:
  order: 10
group.light_view:
  order: 20
group.media_view:
  order: 30
group.mill_view:
  order: 40
group.settings_view:
  order: 50

# settings_view
group.all_scripts:
  hidden: false
  order: 10
group.all_automations:
  hidden: false
  order: 20
group.all_devices:
  hidden: false
  order: 30
group.all_lights:
  hidden: false
  order: 40
group.all_switches:
  hidden: false
  order: 50

# default_view
group.flat:
  order: 10
group.weather:
  order: 20
group.states:
  order: 30
group.people:
  order: 40

# light_view
group.scenes:
  order: 10
group.light:
  order: 20
group.light_livingroom:
  order: 30
group.motion:
  order: 40
