light.floor:
  friendly_name: Gang

light.kitchen:
  friendly_name: Küche

light.livingroom_back:
  friendly_name: Wohnzimmer

light.livingroom_front:
  friendly_name: Wohnzimmer Vorne

light.livingroom_led_top:
  friendly_name: Wohnzimmer LED

light.rainbow:
  friendly_name: Rainbow

light.bedroom:
  friendly_name: Schlafzimmer

light.wc:
  friendly_name: WC
