light.floor:
  friendly_name: Gang

light.kitchen:
  friendly_name: Küche

light.livingroom_back:
  friendly_name: Stehlampe

light.livingroom_back_small:
  friendly_name: Sofatisch

light.livingroom_front:
  friendly_name: Vorne

light.livingroom_led_top:
  friendly_name: LED

light.livingroom_led_top_front:
  friendly_name: LED Vorne

light.livingroom_led_top_back:
  friendly_name: LED Hinten

script.livingroom_led_color:
  friendly_name: LED Auto Color
  icon: mdi:sync

light.rainbow:
  friendly_name: Rainbow

light.bedroom:
  friendly_name: Schlafzimmer

light.wc:
  friendly_name: WC

light.badroom:
  friendly_name: Bad

script.scene_ambient:
  friendly_name: Ambient

script.scene_media:
  friendly_name: Media

script.scene_pause:
  friendly_name: Pause
