light.floor:
  friendly_name: Gang

light.kitchen:
  friendly_name: Küche

light.livingroom_back:
  friendly_name: Wohnzimmer Stehlampe

light.livingroom_back_small:
  friendly_name: Wohnzimmer Sofatisch

light.livingroom_front:
  friendly_name: Wohnzimmer Vorne

light.livingroom_led_top:
  friendly_name: Wohnzimmer LED

script.livingroom_led_color:
  friendly_name: Wohnzimmer LED Auto Color
  icon: mdi:sync

light.rainbow:
  friendly_name: Wohnzimmer Rainbow

light.bedroom:
  friendly_name: Schlafzimmer

light.wc:
  friendly_name: WC
