input_select.media_power:
  friendly_name: Media Power
  icon: mdi:power

script.ir_receiver_power:
  friendly_name: Receiver Power
  icon: mdi:library-music

script.ir_beamer_power_on:
  friendly_name: Beamer ON
  icon: mdi:monitor

script.ir_beamer_power_off:
  friendly_name: Beamer OFF
  icon: mdi:monitor

input_select.media_channel:
  friendly_name: Media Channel
  icon: mdi:keyboard-tab

script.ir_receiver_vol_up:
  friendly_name: Lautstärke - Lauter
  icon: mdi:volume-high

script.ir_receiver_vol_down:
  friendly_name: Lautstärke - Leiser
  icon: mdi:volume-low

switch.livingroom_bass:
  friendly_name: Bass
  icon: mdi:speaker
