- type: entities
  show_header_toggle: false
  name: Espresso
  entities:
    - type: 'custom:multiple-entity-row'
      entity: switch.espresso
      name: Espresso
      icon: mdi:coffee
      state_color: true
      toggle: true
      entities:
        - entity: sensor.temperature_espresso
          name: false
    # Chart
    - type: 'custom:mini-graph-card'
      entities:
        - entity: sensor.temperature_espresso
          show_points: false
      animate: true
      height: 100
      line_width: 1
      decimals: 1
      hour24: true
      hours_to_show: 8
      points_per_hour: 30
      group: true
      show:
        name: false
        icon: false
        state: false
        labels: true
      color_thresholds:
        - value: 0
          color: '#0000ff'
        - value: 50
          color: '#0000ff'
        - value: 55
          color: '#ff0000'
        - value: 65
          color: '#ff0000'

- type: entities
  show_header_toggle: false
  name: Mühle
  entities:

    - type: custom:fold-entity-row
      head:
        entity: switch.espresso_mill
        name: Mühle
      entities:
        - type: custom:slider-entity-row
          entity: input_number.espresso_mill_learning_rate
          name: Lernrate
          grow: true
    
    # Single
    - type: custom:fold-entity-row
      open: true
      head:
        type: custom:multiple-entity-row
        entity: input_number.espresso_mill_amount_measure_single
        name: Single
        icon: mdi:coffee-maker
        show_state: false
        entities:
          - entity: input_number.espresso_mill_amount_single
            name: Menge
            styles:
              width: 50px
          - entity: input_number.espresso_mill_time_single
            name: Zeit
            styles:
              width: 50px
          - icon: mdi:target
            styles:
              margin-left: 10px
              margin-right: 20px
            tap_action:
              action: call-service
              service: script.espresso_mill_calibrate_single
          - icon: mdi:sync
            styles:
              margin-right: 10px
            tap_action:
              action: call-service
              service: script.espresso_mill_sync_single
      entities:
        - type: custom:slider-entity-row
          entity: input_number.espresso_mill_amount_measure_single
          full_row: true
          min: 7.0
          max: 11.0

    # Double
    - type: custom:fold-entity-row
      open: true
      head:
        type: custom:multiple-entity-row
        entity: input_number.espresso_mill_amount_measure_double
        name: Double
        icon: mdi:coffee-maker
        show_state: false
        entities:
          - entity: input_number.espresso_mill_amount_double
            name: Menge
            styles:
              width: 50px
          - entity: input_number.espresso_mill_time_double
            name: Zeit
            styles:
              width: 50px
          - icon: mdi:target
            styles:
              margin-left: 10px
              margin-right: 20px
            tap_action:
              action: call-service
              service: script.espresso_mill_calibrate_double
          - icon: mdi:sync
            styles:
              margin-right: 10px
            tap_action:
              action: call-service
              service: script.espresso_mill_sync_double
      entities:
        - type: custom:slider-entity-row
          entity: input_number.espresso_mill_amount_measure_double
          full_row: true
          min: 12.0
          max: 16.0

    # Tripple
    - type: custom:fold-entity-row
      open: true
      head:
        type: custom:multiple-entity-row
        entity: input_number.espresso_mill_amount_measure_tripple
        name: Tripple
        icon: mdi:coffee-maker
        show_state: false
        entities:
          - entity: input_number.espresso_mill_amount_tripple
            name: Menge
            styles:
              width: 50px
          - entity: input_number.espresso_mill_time_tripple
            name: Zeit
            styles:
              width: 50px
          - icon: mdi:target
            styles:
              margin-left: 10px
              margin-right: 20px
            tap_action:
              action: call-service
              service: script.espresso_mill_calibrate_tripple
          - icon: mdi:sync
            styles:
              margin-right: 10px
            tap_action:
              action: call-service
              service: script.espresso_mill_sync_tripple
      entities:
        - type: custom:slider-entity-row
          entity: input_number.espresso_mill_amount_measure_tripple
          full_row: true
          min: 14.0
          max: 18.0
