- type: vertical-stack
  cards:
    - type: custom:mini-media-player
      name: Youtube Music
      entity: media_player.youtube_music
      artwork: cover
      hide:
        shuffle: false
        icon_state: false
      shortcuts:
        columns: 2
        buttons:
          - name: Chill
            type: script
            id: script.music_playlist_chill
          - name: Chill
            type: script
            id: script.music_playlist_charts
          - name: Radio
            type: service
            id: ytube_music_player.start_radio
            data:
              entity_id: media_player.youtube_music


    - type: entities
      title: Wohnzimmer
      entities:
        - type: custom:mini-media-player
          entity: media_player.shield_cast
          artwork: cover
          hide:
            volume_level: false
        - type: custom:mini-media-player
          entity: media_player.wohnzimmer_assistent
          name: Assistent
          artwork: cover
          hide:
            volume_level: false
          shortcuts:
            buttons:
              - name: Radio SRF4
                type: script
                id: script.music_radio_srf4
                data:
                  media_player_entity_id: media_player.wohnzimmer_assistent

    - type: entities
      title: Schlafzimmer
      entities:
        - type: custom:mini-media-player
          entity: media_player.schlafzimmer_tv
          name: TV
          artwork: cover
          hide:
            volume_level: false
        - type: custom:mini-media-player
          entity: media_player.schlafzimmer_assistent
          name: Assistent
          artwork: cover
          hide:
            volume_level: false
          shortcuts:
            buttons:
              - name: Radio SRF4
                type: script
                id: script.music_radio_srf4
                data:
                  media_player_entity_id: media_player.schlafzimmer_assistent
