- alias: Badroom Motion ON
  trigger:
    platform: state
    entity_id: binary_sensor.badroom_motion
    to: 'on'

  condition: !include ../conditions/night.yaml

  action:
    service: light.turn_on
    entity_id: light.badroom


- alias: Badroom Motion OFF
  trigger:
    - platform: state
      entity_id: binary_sensor.badroom_motion
      to: 'off'
      for:
        seconds: !env_var WC_LIGHT_SECONDS

  action:
    service: light.turn_off
    entity_id: light.badroom
