- alias: Bedroom OFF 5 min
  trigger:
    platform: state
    entity_id: light.bedroom
    to: 'on'
    for:
      minutes: 10
  action:
    service: light.turn_off
    entity_id: light.bedroom


- alias: MQTT Toggle
  trigger:
    platform: mqtt
    topic: cmd/bedroom/light

  action:
    - service: light.toggle
      entity_id: light.bedroom
