# - alias: Any Home
#   trigger:
#     - platform: state
#       entity_id: group.people
#       to: 'home'
#     - platform: sun
#       event: 'sunset'
#       offset: !env_var NIGHT_BEFORE_OFFSET

#   condition:
#     condition: and
#     conditions:
#     - condition: and
#       conditions: !include ../conditions/night_notsleep.yaml
#     - condition: state
#       entity_id: group.people
#       state: 'home'
#     - condition: time
#       before: '00:00'

#   action:
#     - service: script.scene_ambient


- alias: All OFF
  trigger:
    - platform: state
      entity_id: binary_sensor.sleep
      to: 'on'
    - platform: state
      entity_id: group.people
      to: 'not_home'

  action:
    - service: script.scene_all_off

# - alias: Near Home
#   trigger:
#     platform: zone
#     entity_id: device_tracker.f1e84262_flo
#     zone: zone.near_home
#     event: enter
#   action:
#     service: notify.flo
#     data:
#       title: HA
#       message: "Espresso ON!"


- alias: sleep_switch
  trigger:
    - platform: state
      entity_id: input_boolean.sleep
  action:
    - service: mqtt.publish
      data:
        topic: "cmd/sleep"
        payload_template: '{{states.input_boolean.sleep.state}}'
