- alias: Any Home
  trigger:
    - platform: state
      entity_id: group.people
      to: 'home'
    - platform: sun
      event: 'sunset'
      offset: '-01:00:00'

  condition:
    condition: and
    conditions:
    - condition: and
      conditions: !include ../conditions/night_notsleep.yaml
    - condition: state
      entity_id: group.people
      state: 'home'
    - condition: time
      before: '21:00'

  action:
    - service: scene.turn_on
      entity_id: scene.ambient


- alias: All OFF
  trigger:
    - platform: state
      entity_id: binary_sensor.sleep
      to: 'on'
    - platform: state
      entity_id: group.people
      to: 'not_home'

  action:
    - service: scene.turn_on
      entity_id: scene.all_off


- alias: Louisa Home
  trigger:
    - platform: state
      entity_id: group.people
      to: 'home'

  action:
    service_template: notify.flo
    data_template:
      title: HA
      message: "{{ trigger.entity_id }} ist Zuhause!"
