- alias: Humidifier ON
  trigger:
    platform: numeric_state
    entity_id: sensor.espresso_humidity
    below: 49
  action:
    - service: switch.turn_on
      entity_id: switch.livingroom_humidifier
    - service: notify.flo
      data_template:
        title: HA
        message: "Luftbefeuchter ON ({{ states.sensor.espresso_humidity.state }}%)"

- alias: Humidifier OFF
  trigger:
    platform: numeric_state
    entity_id: sensor.espresso_humidity
    above: 50
  action:
    - service: switch.turn_off
      entity_id: switch.livingroom_humidifier
    - service: notify.flo
      data_template:
        title: HA
        message: "Luftbefeuchter OFF ({{ states.sensor.espresso_humidity.state }}%)"
