- alias: ir_sony_tv
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: 'KEY_TV'
  action:
      - service: script.media_power_toggle


- alias: ir_sony_play
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: 'KEY_PLAY'
  action:
    - service: scene.turn_on
      entity_id: scene.media


- alias: ir_sony_pause
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: 'KEY_PAUSE'
  action:
    - service: scene.turn_on
      entity_id: scene.pause


- alias: ir_sony_stop
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: 'KEY_STOP'
  action:
    - service: scene.turn_on
      entity_id: scene.ambient


- alias: ir_sony_1
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: 'KEY_1'
  action:
    - service: light.turn_on
      entity_id: light.livingroom_back


- alias: ir_sony_2
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: 'KEY_2'
  action:
    - service: switch.toggle
      entity_id: switch.livingroom_bass


# - alias: ir_sony_3
#   trigger:
#     - platform: event
#       event_type: ir_command_received
#       event_data:
#         button_name: 'KEY_3'
#   action:
#     - service: switch.toggle
#       entity_id: switch.espresso


# - alias: ir_sony_4
#   trigger:
#     - platform: event
#       event_type: ir_command_received
#       event_data:
#         button_name: 'KEY_4'
#   action:
#     - service: switch.toggle
#       entity_id: switch.resin


# - alias: ir_sony_5
#   trigger:
#     - platform: event
#       event_type: ir_command_received
#       event_data:
#         button_name: 'KEY_5'
#   action:
#     - service: light.toggle
#       entity_id: light.livingroom_back_small


# - alias: ir_sony_6
#   trigger:
#     - platform: event
#       event_type: ir_command_received
#       event_data:
#         button_name: 'KEY_6'
#   action:
#     - service: light.toggle
#       entity_id: light.kitchen


# - alias: ir_sony_7
#   trigger:
#     - platform: event
#       event_type: ir_command_received
#       event_data:
#         button_name: 'KEY_7'
#   action:
#     - service: script.livingroom_led_top_brightness_max


# - alias: ir_sony_8
#   trigger:
#     - platform: event
#       event_type: ir_command_received
#       event_data:
#         button_name: 'KEY_8'
#   action:
#     - service: script.livingroom_led_top_brightness_medium


# - alias: ir_sony_9
#   trigger:
#     - platform: event
#       event_type: ir_command_received
#       event_data:
#         button_name: 'KEY_9'
#   action:
#     - service: switch.toggle
#       entity_id: switch.staubi


- alias: ir_sony_clear
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: 'KEY_CLEAR'
  action:
    - service: switch.toggle
      entity_id: switch.resin


- alias: ir_sony_enter
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: 'KEY_ENTER'
  action:
    - service: switch.toggle
      entity_id: switch.espresso


- alias: ir_sony_0
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: 'KEY_0'
  action:
    - service: switch.toggle
      entity_id: switch.staubi
