- alias: ir_sony_tv
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: 'KEY_TV'
  action:
      - service: script.media_power_toggle


- alias: ir_sony_play
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: 'KEY_PLAY'
  action:
    - service: script.scene_media


- alias: ir_sony_pause
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: 'KEY_PAUSE'
  action:
    - service: script.scene_pause


- alias: ir_sony_stop
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: 'KEY_STOP'
  action:
    - service: script.scene_ambient


- alias: ir_sony_1
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: 'KEY_1'
  action:
    - service: light.toggle
      entity_id: light.livingroom_front


- alias: ir_sony_2
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: 'KEY_2'
  action:
    - service: light.toggle
      entity_id: light.rainbow


- alias: ir_sony_3
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: 'KEY_3'
  action:
    - service: light.toggle
      entity_id: light.floor


- alias: ir_sony_4
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: 'KEY_4'
  action:
    - service: light.toggle
      entity_id: light.livingroom_back


- alias: ir_sony_5
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: 'KEY_5'
  action:
    - service: light.toggle
      entity_id: light.livingroom_back_small


- alias: ir_sony_6
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: 'KEY_6'
  action:
    - service: light.toggle
      entity_id: light.kitchen


- alias: ir_sony_7
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: 'KEY_7'
  action:
    - service: script.scene_all_on


- alias: ir_sony_8
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: 'KEY_8'
  action:
    - service: script.scene_all_off


- alias: ir_sony_9
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: 'KEY_9'
  action:
    - service: light.toggle
      entity_id: light.bedroom
