- alias: ir_sony_light_livingroom_back
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: 'KEY_PLAY'
  action:
    - service: light.toggle
      entity_id: light.livingroom_back


- alias: ir_sony_light_livingroom_front
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: 'KEY_PAUSE'
  action:
    - service: light.toggle
      entity_id: light.livingroom_front


- alias: ir_sony_light_floor
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: 'KEY_1'
  action:
    - service: light.toggle
      entity_id: light.floor


- alias: ir_sony_light_kitchen
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: 'KEY_2'
  action:
    - service: light.toggle
      entity_id: light.kitchen


- alias: ir_sony_light_rainbow
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: 'KEY_3'
  action:
    - service: light.toggle
      entity_id: light.rainbow


- alias: ir_sony_livingroom_bass
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: 'KEY_7'
  action:
    - service: switch.toggle
      entity_id: switch.livingroom_bass


- alias: ir_sony_beamer_power_on
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: 'KEY_TV'
  action:
    - service: script.ir_beamer_power_on


- alias: ir_sony_receiver_power_off
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: 'KEY_TV_HOLD'
  action:
    - service: script.ir_beamer_power_off
