- alias: Kitchen Motion ON
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_motion
    to: 'on'

  condition: !include ../conditions/night_notsleep.yaml

  action:
    service: light.turn_on
    entity_id: light.kitchen


- alias: Kitchen Motion OFF
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_motion
    to: 'off'
    for:
      seconds: !env_var KITCHEN_LIGHT_SECONDS
  action:
    service: light.turn_off
    entity_id: light.kitchen
