- alias: Kitchen Motion ON
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_motion
    to: 'on'
  condition:
    condition: sun
    after: sunset
    after_offset: "-0:30:00"
  action:
    service: light.turn_on
    entity_id: light.kitchen

- alias: Kitchen Motion OFF
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_motion
    to: 'off'
    for:
      minutes: 1
  action:
    service: light.turn_off
    entity_id: light.kitchen
