- alias: Bedroom OFF 5 min
  trigger:
    platform: state
    entity_id: light.bedroom
    to: 'on'
    for:
      minutes: 5
  action:
    service: light.turn_off
    entity_id: light.bedroom

- alias: Livingroom Front OFF 10 min
  trigger:
    platform: state
    entity_id: light.livingroom_front
    to: 'on'
    for:
      minutes: 10
  action:
    service: light.turn_off
    entity_id: light.livingroom_front
