- alias: Lights ON
  trigger:
    - platform: state
      entity_id: device_tracker.flo
      to: 'home'
    - platform: sun
      event: 'sunset'
      offset: '-00:30:00'
  condition:
    condition: and
    conditions:
    - condition: sun
      after: sunset
      after_offset: "-0:30:00"
    - condition: state
      entity_id: device_tracker.flo
      state: 'home'
    - condition: time
      before: '23:00'
  action:
    - service: light.turn_on
      entity_id: light.rainbow

    - service: light.turn_on
      entity_id: light.livingroom_back
