- alias: Front MQTT Toggle
  trigger:
    platform: mqtt
    topic: cmd/livingroom/light/front

  action:
    - service: light.toggle
      entity_id: light.livingroom_front


- alias: Livingroom Motion OFF
  trigger:
    platform: state
    entity_id: binary_sensor.livingroom_motion
    to: 'off'
    for:
      minutes: 5

  action:
    - service: script.scene_livingroom_off


- alias: Livingroom Motion ON
  trigger:
    platform: state
    entity_id: binary_sensor.livingroom_motion
    to: 'on'

  condition:
    - condition: state
      entity_id: group.light_livingroom
      state: 'off'

  action:
    - service: script.turn_on
      data_template:
        entity_id: >
          {% if is_state('input_select.media_power', 'True') %}
            script.scene_media
          {% else %}
            script.scene_ambient
          {% endif %}
