- alias: Livingroom Media ON
  trigger:
    - platform: state
      entity_id: media_player.horizon
      to: 'playing'
    # - platform: state
    #   entity_id: media_player.ps4
    #   to: 'on'

  action:
    service: script.media_power_on
