- alias: key_media_power_pressed
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: KEY_POWER
  action:
    - service: script.turn_on
      data_template:
        entity_id: >
          {% if is_state('input_select.media_power', 'False') %}
            script.media_power_on
          {% else %}
            script.media_power_off
          {% endif %}


- alias: media_power_selected
  trigger:
    - platform: state
      entity_id: input_select.media_power
  action:
    - service: script.turn_on
      data_template:
        entity_id: >
          {% if is_state('input_select.media_power', 'True') %}
            script.media_power_on
          {% else %}
            script.media_power_off
          {% endif %}


- alias: key_channel_pressed
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: KEY_CHANNEL
  action:
    - service: script.media_channel_switch


- alias: media_channel_selected
  trigger:
    - platform: state
      entity_id: input_select.media_channel
  action:
    - service: script.media_channel


- alias: key_volumeup_pressed
  trigger:
    platform: event
    event_type: ir_command_received
    event_data:
      button_name: KEY_VOLUMEUP
  action:
    - service: script.ir_receiver_vol_up


- alias: key_volumeup_pressed
  trigger:
    platform: event
    event_type: ir_command_received
    event_data:
      button_name: KEY_VOLUMEDOWN
  action:
    - service: script.ir_receiver_vol_down


- alias: key_mute_pressed
  trigger:
    platform: event
    event_type: ir_command_received
    event_data:
      button_name: KEY_MUTE
  action:
    - service: switch.toggle
      entity_id: switch.livingroom_bass
