vacuum_livingroom:
  sequence:
    - service: vacuum.xiaomi_clean_zone
      data_template:
        entity_id: vacuum.xiaomi_vacuum
        repeats: 3
        zone:
          - [25258,17220,28758,21220]
