- platform: yr
  monitored_conditions:
    - temperature
    - symbol
    - windSpeed
    - windDirection
    - pressure
    - humidity
    - cloudiness

- platform: mqtt
  name: temperature_livingroom
  state_topic: "homie/livingroom-climate/sensor/temperature"
  qos: 0
  unit_of_measurement: "°C"

- platform: mqtt
  name: humidity_livingroom.
  state_topic: "homie/livingroom-climate/sensor/humidity"
  qos: 0
  unit_of_measurement: "%"

- platform: mqtt
  name: temperature_kitchen
  state_topic: "homie/espresso/sensor/temperature"
  qos: 0
  unit_of_measurement: "°C"

- platform: mqtt
  name: humidity_kitchen
  state_topic: "homie/espresso/sensor/humidity"
  qos: 0
  unit_of_measurement: "%"
