- platform: mqtt
  name: temperature_livingroom
  state_topic: "homie/livingroom-climate/sensor/temperature"
  qos: 0
  unit_of_measurement: "°C"

- platform: mqtt
  name: humidity_livingroom
  state_topic: "homie/livingroom-climate/sensor/humidity"
  qos: 0
  unit_of_measurement: "%"

- platform: mqtt
  name: temperature_espresso
  state_topic: "homie/espresso/sensor/temperature"
  qos: 0
  unit_of_measurement: "°C"

- platform: mqtt
  name: humidity_espresso
  state_topic: "homie/espresso/sensor/humidity"
  qos: 0
  unit_of_measurement: "%"

- platform: template
  sensors:
    mystrom_1_power:
      friendly_name: "Current Power"
      unit_of_measurement: "W"
      value_template: "{{ state_attr('switch.mystrom_1', 'current_power_w') }}"
