- platform: mqtt
  name: temperature_livingroom
  state_topic: "homie/livingroom-climate/sensor/temperature"
  qos: 0
  unit_of_measurement: "°C"

- platform: mqtt
  name: humidity_livingroom
  state_topic: "homie/livingroom-climate/sensor/humidity"
  qos: 0
  unit_of_measurement: "%"

- platform: mqtt
  name: temperature_espresso
  state_topic: "homie/espresso/sensor/temperature"
  qos: 0
  unit_of_measurement: "°C"

- platform: mqtt
  name: humidity_espresso
  state_topic: "homie/espresso/sensor/humidity"
  qos: 0
  unit_of_measurement: "%"

- platform: rest
  name: mystrom_1_report
  resource: !secret mystrom-1_report
  scan_interval: 60
  json_attributes:
    - power
    - temperature
  value_template: "OK"

- platform: template
  sensors:
    mystrom_1_temperature:
      value_template: "{{ state_attr('sensor.mystrom_1_report', 'temperature') }}"
      device_class: temperature
      unit_of_measurement: "°C"
    mystrom_1_power:
      value_template: "{{ state_attr('sensor.mystrom_1_report', 'power') }}"
      device_class: power
      unit_of_measurement: "W"
