- alias: Notify Wohnzimmer CO2
  trigger:
    - platform: time_pattern
      minutes: '/55'
    - platform: numeric_state
      entity_id: sensor.netatmo_home_indoor_co2
      above: 1200
  condition:
    - condition: state
      entity_id: input_boolean.state_sleep
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.netatmo_home_indoor_co2
      above: 1200
      below: 1500
  action:
    - service: script.notify_google
      data:
        language: de
        message: 'schlächti luft'
        message_say: 'schlächti luft'


- alias: Notify Wohnzimmer CO2 Max
  trigger:
    - platform: time_pattern
      minutes: '/25'
    - platform: numeric_state
      entity_id: sensor.netatmo_home_indoor_co2
      above: 1500
  condition:
    - condition: state
      entity_id: input_boolean.state_sleep
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.netatmo_home_indoor_co2
      above: 1500
  action:
    - service: script.notify_google
      data:
        language: de
        message: 'du muäsch dringend lüfte'
        message_say: 'du muäsch dringend lüfte'


- alias: Notify Wohnzimmer Feuchtigkeit
  trigger:
    - platform: time_pattern
      minutes: '/56'
    - platform: numeric_state
      entity_id: sensor.netatmo_home_indoor_humidity
      below: 32
  condition:
    - condition: state
      entity_id: input_boolean.state_sleep
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.netatmo_home_indoor_humidity
      below: 32
  action:
    - service: script.notify_google
      data:
        language: de
        message: 'trochni luft'
        message_say: 'trochni luft'
