- alias: 'network new device'
  trigger:
    platform: event
    event_type: device_tracker_new_device
  action:
    - service: notify.browser
      data_template:
        message: >
          new device in network:
          {{ trigger.event.data.host_name }}
          ({{ trigger.event.data.entity_id }})
    - service: script.notify_google
      data_template:
        language: de
        message: "Neuer Netzwerkzugriff von {{ trigger.event.data.host_name }}"
        message_say: "Neuer Netzwerkzugriff von {{ trigger.event.data.host_name }}"


- alias: Louisa Home
  trigger:
    - platform: state
      entity_id: device_tracker.louisa
    - platform: state
      entity_id: device_tracker.myrtha
    - platform: state
      entity_id: device_tracker.ries
    - platform: state
      entity_id: device_tracker.bri
    - platform: state
      entity_id: device_tracker.gubi
    - platform: state
      entity_id: device_tracker.peti
  action:
    - service: notify.browser
      data_template:
        message: "{{ str(trigger.entity_id).replace('device_tracker.','') }} ist {{ str(trigger.to_state.state).replace('not_home','weg').replace('home','da') }}"
    - service: script.notify_google
      data_template:
        language: de
        message: "{{ str(trigger.entity_id).replace('device_tracker.','') }} ist {{ str(trigger.to_state.state).replace('not_home','weg').replace('home','da') }}"
        message_say: "{{ str(trigger.entity_id).replace('device_tracker.','') }} ist {{ str(trigger.to_state.state).replace('not_home','weg').replace('home','da') }}"
