- alias: Espresso Notify
  trigger:
    - platform: numeric_state
      entity_id: sensor.temperature_kitchen
      above: 40
    - platform: state
      entity_id: switch.espresso
      to: 'on'
      for:
        minutes: 5
  condition:
    - condition: numeric_state
      entity_id: sensor.temperature_kitchen
      above: 40
  action:
    - service: notify.flo
      data:
        message: 'Espresso ist aufgewärmt'
    - service: tts.google_say
      entity_id: media_player.home_group
      data:
        language: it
        message: 'hey hey, kafi isch fertig'