- alias: Espresso Notify
  trigger:
    - platform: numeric_state
      entity_id: sensor.temperature_kitchen
      above: 40
    - platform: state
      entity_id: switch.espresso
      to: 'on'
      for:
        minutes: 5
  condition:
    - condition: numeric_state
      entity_id: sensor.temperature_kitchen
      above: 40
  action:
    - service: notify.flo
      data:
        message: 'Espresso ist aufgewärmt'
    - service: script.notify_google
      data:
        language: it
        message: 'hey hey bueb käfi isch fertig'
