- alias: Espresso Notify
  trigger:
    - platform: numeric_state
      entity_id: sensor.temperature_espresso
      above: 40
    - platform: state
      entity_id: switch.espresso
      to: 'on'
      for:
        minutes: 6
  condition:
    - condition: numeric_state
      entity_id: sensor.temperature_espresso
      above: 40
    - condition: state
      entity_id: switch.espresso
      state: 'on'
      for:
        minutes: 6
  action:
    - service: notify.flo
      data:
        message: 'Espresso ist aufgewärmt'
    - service: script.notify_google
      data:
        language: it
        message: 'espresso isch fertig'
        message_say: 'hey hey bueb käfi isch fertig'
