- alias: Notify Handy Charge 80 Florian
  id: notify_handy_charge_80_florian
  trigger:
    - platform: numeric_state
      entity_id: sensor.florian_handy_battery_level
      above: 80
  condition:
    - condition: state
      entity_id: person.florian
      state: 'home'
  action:
    - service: script.notify_google
      data:
        language: de
        message: 'diss handy isch ufglade'
        message_say: 'diss handy isch ufglade'


- alias: Notify Handy Charge 30 Florian
  id: notify_handy_charge_30_florian
  trigger:
    - platform: numeric_state
      entity_id: sensor.florian_handy_battery_level
      below: 30
  condition:
    - condition: state
      entity_id: person.florian
      state: 'home'
    - condition: state
      entity_id: sensor.florian_handy_battery_state
      state: 'discharging'
  action:
    - service: script.notify_google
      data:
        language: de
        message: 'diss handy musch uflade'
        message_say: 'diss handy musch uflade'
