- platform: mqtt
  name: sleep
  state_topic: "cmd/sleep"

- platform: mqtt
  name: floor_motion
  state_topic: "homie/floor-light/motion/state"

- platform: mqtt
  name: kitchen_motion
  state_topic: "homie/kitchen-light/motion/state"

- platform: mqtt
  name: wc_motion
  state_topic: "homie/wc-light/motion/state"

