api_password: !secret api_password
server_port: 443
ssl_certificate: !secret ssl_certificate
ssl_key: !secret ssl_key
cors_allowed_origins:
  - https://google.com
  - https://home-assistant.io
ip_ban_enabled: True
login_attempts_threshold: 5