- name: media
  entities:
    light.rainbow: on
    light.livingroom_back: off

- name: ambient
  entities:
    light.rainbow: on
    light.livingroom_back: on

- name: all_off
  entities:
    group.light: off
    group.media: off

- name: green
  entities:
    light.rainbow:
      state: on
      rgb_color: [0, 255, 0]
