- platform: mqtt
  name: livingroom_bass
  state_topic: "homie/livingroom-bass/switch/state"
  command_topic: "homie/livingroom-bass/switch/state/set"

- platform: mqtt
  name: mill
  state_topic: "homie/mill/on/state"
  command_topic: "homie/mill/on/state/set"

- platform: mqtt
  name: espresso
  state_topic: "homie/espresso/switch/state"
  command_topic: "homie/espresso/switch/state/set"

- platform: mqtt
  name: livingroom_humidifier
  state_topic: "homie/livingroom-steamer/switch/state"
  command_topic: "homie/livingroom-steamer/switch/state/set"

- platform: mqtt
  name: resin
  state_topic: "homie/resin/switch/state"
  command_topic: "homie/resin/switch/state/set"

- platform: xiaomi_vacuum
  name: "Staubi"
  host: "rockrobo"
  token: "3249544c437648434d32433441345454"