input_boolean:
  state_sleep:

automation:
  - alias: Sleep ON
    id: sleep_on
    triggers:
      - trigger: state
        entity_id: input_boolean.state_sleep
        to: 'on'
    actions:
      # google volume
      - action: media_player.volume_set
        entity_id: media_player.schlafzimmer_assistant
        data_template:
          volume_level: 0.1
      - action: media_player.volume_set
        entity_id: media_player.wohnzimmer_assistant
        data_template:
          volume_level: 0
      # all off
      - action: script.all_off


  - alias: Sleep OFF
    id: sleep_off
    triggers:
      - trigger: state
        entity_id: input_boolean.state_sleep
        to: 'off'
    conditions:
      - condition: state
        entity_id: input_boolean.state_home
        state: 'on'
    actions:
      # google
      - action: media_player.volume_set
        entity_id: media_player.schlafzimmer_assistant
        data_template:
          volume_level: 0.2
      - action: media_player.volume_set
        entity_id: media_player.wohnzimmer_assistant
        data_template:
          volume_level: 0.2
      - action: input_select.select_option
        data:
          entity_id: input_select.mode_livingroom_light
          option: 'Normal'
