input_boolean:
  state_home:

automation:
  - alias: state_home_off
    id: state_home_off
    triggers:
      - trigger: state
        entity_id: input_boolean.state_home
        to: "off"
    actions:
      - action: input_boolean.turn_off
        entity_id: input_boolean.state_sleep
      - action: script.turn_on
        entity_id: script.all_off
      - action: media_player.turn_off
        entity_id: media_player.wohnzimmer_tv
      - action: media_player.turn_off
        entity_id: media_player.schlafzimmer_tv_android

  - alias: state_home_on
    id: state_home_on
    triggers:
      - trigger: state
        entity_id: input_boolean.state_home
        to: "on"
    actions:
      - action: input_select.select_option
        data:
          entity_id: input_select.mode_livingroom_light
          option: "Normal"
      - action: switch.turn_on
        entity_id: switch.shelly_bedroom
      - action: switch.turn_on
        entity_id: switch.shelly_office

  - alias: people_home
    id: people_home
    triggers:
      - trigger: numeric_state
        entity_id: zone.home
        above: 0
    actions:
      - action: input_boolean.turn_on
        entity_id: input_boolean.state_home

  - alias: people_not_home
    id: people_not_home
    triggers:
      - trigger: state
        entity_id: zone.home
        to: "0"
    conditions:
      - condition: state
        entity_id: input_boolean.state_sleep
        state: "off"
    actions:
      - action: input_boolean.turn_off
        entity_id: input_boolean.state_home
