- alias: cellar_charger_button_toggle
  trigger:
    - platform: state
      entity_id: binary_sensor.cellar_charger_button
      to: 'on'
  action:
    - service: switch.toggle
      entity_id: switch.cellar_charger_led


- alias: cellar_charger_led_start
  trigger:
    - platform: state
      entity_id: switch.cellar_charger_led
      to: 'on'
  action:
    - service: script.cellar_charge


- alias: cellar_charger_led_stop
  trigger:
    - platform: state
      entity_id: switch.cellar_charger_led
      to: 'off'
  action:
    - service: script.turn_off
      entity_id: 
        - script.cellar_charge
        - switch.cellar_charger
        - switch.ebike


- alias: cellar_charger_done
  trigger:
    - platform: state
      entity_id: switch.cellar_charger
      to: 'off'
    - platform: state
      entity_id: switch.ebike
      to: 'off'
  condition:
    - condition: state
      entity_id: switch.cellar_charger
      state: 'off'
    - condition: state
      entity_id: switch.ebike
      state: 'off'
  action:
    - service: switch.turn_off
      entity_id: switch.cellar_charger_led


- alias: cellar_charger_turn_off_time
  trigger:
    - platform: state
      entity_id: switch.cellar_charger
      to: 'on'
      for:
        hours: "{{ states('input_number.cellar_charger_hours') }}"
  action:
    - service: switch.turn_off
      entity_id: switch.cellar_charger
