- alias: ebike_charge_turn_off_power
  trigger:
    - platform: state
      entity_id: switch.ebike
      to: 'on'
      for:
        minutes: 1
    - platform: state
      entity_id: binary_sensor.ebike_power_outside_range
      to: 'on'
      for:
        minutes: 1
  condition:
    - condition: state
      entity_id: switch.ebike
      state: 'on'
      for:
        minutes: 1
    - condition: state
      entity_id: binary_sensor.ebike_power_outside_range
      state: 'on'
      for:
        minutes: 1
  action:
    - service: switch.turn_off
      entity_id: switch.ebike


- alias: ebike_charge_turn_off_time
  trigger:
    - platform: state
      entity_id: switch.ebike
      to: 'on'
      for:
        hours: "{{ states('input_number.cellar_charger_hours') }}"
  action:
    - service: switch.turn_off
      entity_id: switch.ebike


- alias: ebike_charge_reset_60_on_turn_off
  trigger:
    - platform: state
      entity_id: switch.ebike
      to: 'off'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.ebike_charging_limit
        option: 60%
    - service: input_number.set_value
      entity_id: input_number.cellar_charger_hours
      data:
        value: 2
