- alias: cellar_charger_button_toggle
  trigger:
    - platform: state
      entity_id: binary_sensor.cellar_charger_button
      to: 'on'
  action:
    - service: script.toggle
      entity_id: script.cellar_charge


- alias: cellar_charger_stop
  trigger:
    - platform: state
      entity_id: script.cellar_charge
      to: 'off'
  action:
    - service: script.turn_on
      entity_id: script.cellar_charge_stop


- alias: cellar_charger_turn_off_time
  trigger:
    - platform: state
      entity_id: switch.cellar_charger
      to: 'on'
      for:
        hours: "{{ states('input_number.cellar_charger_hours') }}"
  action:
    - service: switch.turn_off
      entity_id: switch.cellar_charger


- alias: ebike_charge_turn_off_power
  trigger:
    - platform: state
      entity_id: switch.ebike
      to: 'on'
      for:
        minutes: 3
    - platform: state
      entity_id: binary_sensor.ebike_power_outside_range
      to: 'on'
      for:
        minutes: 3
  condition:
    - condition: state
      entity_id: switch.ebike
      state: 'on'
      for:
        minutes: 3
    - condition: state
      entity_id: binary_sensor.ebike_power_outside_range
      state: 'on'
      for:
        minutes: 3
  action:
    - service: switch.turn_off
      entity_id: switch.ebike
