# Sync Single
espresso_mill_calibrate_single:
  sequence:
    - service: script.espresso_mill_calibrate
      data:
        time_entity_id: input_number.espresso_mill_time_single
        amount_entity_id: input_number.espresso_mill_amount_single
        amount_measure_entity_id: input_number.espresso_mill_amount_measure_single
    - service: script.espresso_mill_sync
      data:
        amount_source_entity_id: input_number.espresso_mill_amount_single
        time_source_entity_id: input_number.espresso_mill_time_single
        amount_target_entity_id: input_number.espresso_mill_amount_double
        time_target_entity_id: input_number.espresso_mill_time_double
    - service: script.espresso_mill_sync
      data:
        amount_source_entity_id: input_number.espresso_mill_amount_single
        time_source_entity_id: input_number.espresso_mill_time_single
        amount_target_entity_id: input_number.espresso_mill_amount_triple
        time_target_entity_id: input_number.espresso_mill_time_triple

# Sync Double
espresso_mill_calibrate_double:
  sequence:
    - service: script.espresso_mill_calibrate
      data:
        time_entity_id: input_number.espresso_mill_time_double
        amount_entity_id: input_number.espresso_mill_amount_double
        amount_measure_entity_id: input_number.espresso_mill_amount_measure_double
    - service: script.espresso_mill_sync
      data:
        amount_source_entity_id: input_number.espresso_mill_amount_double
        time_source_entity_id: input_number.espresso_mill_time_double
        amount_target_entity_id: input_number.espresso_mill_amount_single
        time_target_entity_id: input_number.espresso_mill_time_single
    - service: script.espresso_mill_sync
      data:
        amount_source_entity_id: input_number.espresso_mill_amount_double
        time_source_entity_id: input_number.espresso_mill_time_double
        amount_target_entity_id: input_number.espresso_mill_amount_triple
        time_target_entity_id: input_number.espresso_mill_time_triple

# Sync Triple
espresso_mill_calibrate_triple:
  sequence:
    - service: script.espresso_mill_calibrate
      data:
        time_entity_id: input_number.espresso_mill_time_triple
        amount_entity_id: input_number.espresso_mill_amount_triple
        amount_measure_entity_id: input_number.espresso_mill_amount_measure_triple
    - service: script.espresso_mill_sync
      data:
        amount_source_entity_id: input_number.espresso_mill_amount_triple
        time_source_entity_id: input_number.espresso_mill_time_triple
        amount_target_entity_id: input_number.espresso_mill_amount_single
        time_target_entity_id: input_number.espresso_mill_time_single
    - service: script.espresso_mill_sync
      data:
        amount_source_entity_id: input_number.espresso_mill_amount_triple
        time_source_entity_id: input_number.espresso_mill_time_triple
        amount_target_entity_id: input_number.espresso_mill_amount_double
        time_target_entity_id: input_number.espresso_mill_time_double

# Internal
espresso_mill_calibrate:
  sequence:
    - service: input_number.set_value
      data_template:
        entity_id: "{{ time_entity_id }}"
        value: >
          {% set learning_rate = states('input_number.espresso_mill_learning_rate') | float %}
          {% set current_time = states(time_entity_id) | float %}
          {% set current_amount = states(amount_measure_entity_id) | float %}
          {% set target_amount = states(amount_entity_id) | float %}
          {% set target_time = current_time * target_amount / current_amount %}
          {% set new_time = (1 - learning_rate) * current_time + learning_rate * target_time %}
          {{ new_time | round(2) }}
    - service: input_number.set_value
      data_template:
        entity_id: "{{ amount_measure_entity_id }}"
        value: "{{ states(amount_entity_id) }}"

espresso_mill_sync:
  sequence:
    - service: input_number.set_value
      data_template:
        entity_id: "{{ time_target_entity_id }}"
        value: >
          {% set learning_rate = states('input_number.espresso_mill_learning_rate') | float %}
          {% set amount_source = states(amount_source_entity_id) | float %}
          {% set amount_target = states(amount_target_entity_id) | float %}
          {% set time_source = states(time_source_entity_id) | float %}
          {% set time_target = states(time_target_entity_id) | float %}
          {% set time_target_calc = time_source * amount_target / amount_source %}
          {% set new_time = (1 - learning_rate) * time_target + learning_rate * time_target_calc %}
          {{ new_time | round(2) }}
