# Sync Single
espresso_mill_calibrate_single:
  sequence:
    - service: script.espresso_mill_calibrate
      data_template:
        time_entity_id: input_number.espresso_mill_time_single
        amount_measure_entity_id: input_number.espresso_mill_amount_measure_single

# Sync Double
espresso_mill_calibrate_double:
  sequence:
    - service: script.espresso_mill_calibrate
      data:
        time_entity_id: input_number.espresso_mill_time_double
        amount_measure_entity_id: input_number.espresso_mill_amount_measure_double

# Sync Triple
espresso_mill_calibrate_triple:
  sequence:
    - service: script.espresso_mill_calibrate
      data:
        time_entity_id: input_number.espresso_mill_time_triple
        amount_measure_entity_id: input_number.espresso_mill_amount_measure_triple


# Internal
espresso_mill_calibrate:
  variables:
    amount_time: >
      {% set current_time = states(time_entity_id) | float %}
      {% set current_amount = states(amount_measure_entity_id) | float %}
      {{ current_time / current_amount }}
  sequence:
    - service: script.espresso_mill_update_single
      data_template:
        amount_time: "{{ amount_time }}"
    - service: script.espresso_mill_update_double
      data_template:
        amount_time: "{{ amount_time }}"
    - service: script.espresso_mill_update_triple
      data_template:
        amount_time: "{{ amount_time }}"

espresso_mill_update_single:
  sequence:
    - service: script.espresso_mill_update
      data_template:
        time_entity_id: input_number.espresso_mill_time_single
        amount_entity_id: input_number.espresso_mill_amount_single
        amount_measure_entity_id: input_number.espresso_mill_amount_measure_single
        amount_time: "{{ amount_time }}"

espresso_mill_update_double:
  sequence:
    - service: script.espresso_mill_update
      data_template:
        time_entity_id: input_number.espresso_mill_time_double
        amount_entity_id: input_number.espresso_mill_amount_double
        amount_measure_entity_id: input_number.espresso_mill_amount_measure_double
        amount_time: "{{ amount_time }}"

espresso_mill_update_triple:
  sequence:
    - service: script.espresso_mill_update
      data_template:
        time_entity_id: input_number.espresso_mill_time_triple
        amount_entity_id: input_number.espresso_mill_amount_triple
        amount_measure_entity_id: input_number.espresso_mill_amount_measure_triple
        amount_time: "{{ amount_time }}"

espresso_mill_update:
  sequence:
    - service: input_number.set_value
      data_template:
        entity_id: "{{ time_entity_id }}"
        value: >
          {% set learning_rate = states('input_number.espresso_mill_learning_rate') | float %}
          {% set current_time = states(time_entity_id) | float %}
          {% set target_amount = states(amount_entity_id) | float %}
          {% set target_time = target_amount * amount_time %}
          {% set new_time = (1 - learning_rate) * current_time + learning_rate * target_time %}
          {{ new_time | round(2) }}
    - service: input_number.set_value
      data_template:
        entity_id: "{{ amount_measure_entity_id }}"
        value: "{{ states(amount_entity_id) }}"
