- alias: Bedroom OFF
  trigger:
    - platform: state
      entity_id: light.light_bedroom_light
      to: 'on'
      for:
        hour: 1
  action:
    - service: light.turn_off
      entity_id: light.light_bedroom_light
