- alias: bedroom_light_autooff
  trigger:
    - platform: state
      entity_id: light.light_bedroom
      to: 'on'
      for:
        minutes: 60
  action:
    - service: light.turn_off
      entity_id: light.light_bedroom
