- alias: shelly_bedroom_switch_off
  trigger:
    - platform: state
      entity_id: binary_sensor.shelly_bedroom_switch
  condition:
    - condition: state
      entity_id: light.light_bedroom_light
      state: 'on'
      for:
        seconds: 1
  action:
    - service: light.turn_off
      entity_id: light.light_bedroom_light

- alias: shelly_bedroom_switch_on
  trigger:
    - platform: state
      entity_id: binary_sensor.shelly_bedroom_switch
  condition:
    - condition: state
      entity_id: light.light_bedroom_light
      state: 'off'
      for:
        seconds: 1
  action:
    - service: light.turn_on
      entity_id: light.light_bedroom_light
      data:
        rgb_color: [255, 226, 145] #white
        brightness: 255
