- alias: Bedroom Light Color Weiss
  trigger:
    - platform: state
      entity_id: input_select.state_bedroom_light_color
      to: 'Weiss'
  action:
    - service: light.turn_on
      entity_id: light.light_bedroom_light
      data:
        transition: 0
        rgb_color: [255, 255, 255]

- alias: Bedroom Light Color Gelb
  trigger:
    - platform: state
      entity_id: input_select.state_bedroom_light_color
      to: 'Gelb'
  action:
    - service: light.turn_on
      entity_id: light.light_bedroom_light
      data:
        transition: 0
        rgb_color: [255, 190, 0]

- alias: Bedroom Light Color Orange
  trigger:
    - platform: state
      entity_id: input_select.state_bedroom_light_color
      to: 'Orange'
  action:
    - service: light.turn_on
      entity_id: light.light_bedroom_light
      data:
        transition: 0
        rgb_color: [255, 129, 1]

- alias: Bedroom Light Color Rot
  trigger:
    - platform: state
      entity_id: input_select.state_bedroom_light_color
      to: 'Rot'
  action:
    - service: light.turn_on
      entity_id: light.light_bedroom_light
      data:
        transition: 0
        rgb_color: [255, 0, 0]

- alias: Bedroom Light Color Pink
  trigger:
    - platform: state
      entity_id: input_select.state_bedroom_light_color
      to: 'Pink'
  action:
    - service: light.turn_on
      entity_id: light.light_bedroom_light
      data:
        transition: 0
        rgb_color: [255, 6, 128]

- alias: Bedroom Light Color Violett
  trigger:
    - platform: state
      entity_id: input_select.state_bedroom_light_color
      to: 'Violett'
  action:
    - service: light.turn_on
      entity_id: light.light_bedroom_light
      data:
        transition: 0
        rgb_color: [191, 2, 255]

- alias: Bedroom Light Color Blau
  trigger:
    - platform: state
      entity_id: input_select.state_bedroom_light_color
      to: 'Blau'
  action:
    - service: light.turn_on
      entity_id: light.light_bedroom_light
      data:
        transition: 0
        rgb_color: [0, 0, 255]

- alias: Bedroom Light Color Grün
  trigger:
    - platform: state
      entity_id: input_select.state_bedroom_light_color
      to: 'Grün'
  action:
    - service: light.turn_on
      entity_id: light.light_bedroom_light
      data:
        transition: 0
        rgb_color: [0, 255, 0]
