- alias: Bedroom Motion ON
  trigger:
    platform: state
    entity_id: binary_sensor.0x00158d000273269a_occupancy
    to: 'on'
  condition: !include ../../../condition/light.nosleep.yaml
  action:
    service: light.turn_on
    data:
      entity_id: light.0x90fd9ffffee5f479_light
      brightness: 100


- alias: Bedroom Motion OFF
  trigger:
    platform: state
    entity_id: binary_sensor.0x00158d000273269a_occupancy
    to: 'off'
    for:
      minutes: 5
  action:
    service: light.turn_off
    entity_id: light.0x90fd9ffffee5f479_light
