- alias: Sunrise
  id: sunrise
  trigger:
    - platform: time
      at: input_datetime.sunrise_time
  condition:
    - condition: state
      entity_id: input_boolean.sunrise_enabled
      state: 'on'
    - condition: template
      value_template: >
        {% set device = states.person.florian %}
        {% set isHome = not( device.state == 'not_home' and (now() - device.last_changed).total_seconds() > 10*60*60 ) %}
        {{ isHome }}
  action:
    service: script.wakeup

- alias: Sunrise Update Time
  id: sunrise_update_time
  trigger:
    - platform: state
      entity_id: sensor.florian_handy_next_alarm
  condition:
    - condition: template
      value_template: "{{ states('sensor.florian_handy_next_alarm') != 'unavailable' }}"
  action:
    - service: input_datetime.set_datetime
      entity_id: input_datetime.sunrise_time
      data_template:
        datetime: >
          {{ (states('sensor.florian_handy_next_alarm') | as_datetime | as_local) - timedelta(minutes=30) }}
