- alias: Bedroom Switch ON/OFF
  trigger:
    platform: state
    entity_id: sensor.switch_bedroom_action
    to: 'toggle'
  action:
    service: light.toggle
    entity_id: light.light_bedroom_light
    data:
      transition: 1

- alias: Bedroom Brightness UP
  trigger:
    - platform: state
      entity_id: sensor.switch_bedroom_action
      to: 'brightness_up_click'
  action:
    - service: input_select.select_next
      entity_id: input_select.state_bedroom_light_brightness

- alias: Bedroom Brightness DOWN
  trigger:
    - platform: state
      entity_id: sensor.switch_bedroom_action
      to: 'brightness_down_click'
  action:
    - service: input_select.select_previous
      entity_id: input_select.state_bedroom_light_brightness

- alias: Bedroom Color Right
  trigger:
    - platform: state
      entity_id: sensor.switch_bedroom_action
      to: 'arrow_right_click'
  action:
    - service: input_select.select_next
      entity_id: input_select.state_bedroom_light_color

- alias: Bedroom Color Left
  trigger:
    - platform: state
      entity_id: sensor.switch_bedroom_action
      to: 'arrow_left_click'
  action:
    - service: input_select.select_previous
      entity_id: input_select.state_bedroom_light_color
