- alias: Bedroom Color Right
  trigger:
    - platform: state
      entity_id: sensor.switch_bedroom_action
      to: 'arrow_right_click'
  action:
    - service: light.turn_on
      entity_id: light.light_bedroom_light
      data:
        rgb_color: [255, 100, 1] #orange
        brightness: 168

- alias: Bedroom Color Right Hold
  trigger:
    - platform: state
      entity_id: sensor.switch_bedroom_action
      to: 'arrow_right_hold'
  action:
    - service: light.turn_on
      entity_id: light.light_bedroom_light
      data:
        rgb_color: [255, 6, 128] #pink
        brightness: 255

- alias: Bedroom Color Left
  trigger:
    - platform: state
      entity_id: sensor.switch_bedroom_action
      to: 'arrow_left_click'
  action:
    - service: light.turn_on
      entity_id: light.light_bedroom_light
      data:
        rgb_color: [255, 226, 145] #white
        brightness: 255

- alias: Bedroom Color Left Hold
  trigger:
    - platform: state
      entity_id: sensor.switch_bedroom_action
      to: 'arrow_left_hold'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.state_sleep
