- alias: switch_bedroom_left
  trigger:
    - platform: state
      entity_id: sensor.switch_bedroom_action
      to: 'single_left'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.state_sleep
    # tv off
    - service: notify.google_assistant
      data:
        message: "turn off schlafzimmer tv"
    # sleep music
    - service: script.youtube_music_playlist_sleep
    - delay:
        hours: 2
    - service: script.all_off

- alias: switch_bedroom_right
  mode: restart
  trigger:
    - platform: state
      entity_id: sensor.switch_bedroom_action
      to: 'single_right'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.state_sleep
    - service: switch.turn_on
      entity_id: switch.espresso
    - service: script.music_radio_srf4
    - delay:
        hours: 1
    - service: script.music_turn_off

- alias: switch_bedroom_both
  trigger:
    - platform: state
      entity_id: sensor.switch_bedroom_action
      to: 'single_both'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.state_sleep
