- alias: Bedroom Color Right
  trigger:
    - platform: state
      entity_id: sensor.switch_bedroom_action
      to: 'arrow_right_click'
  action:
    - service: light.turn_on
      entity_id: light.light_bedroom_light
      data:
        rgb_color: [255, 100, 1] #orange
        brightness: 168

- alias: Bedroom Right Hold
  trigger:
    - platform: state
      entity_id: sensor.switch_bedroom_action
      to: 'arrow_right_hold'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.state_sleep

- alias: Bedroom Color Left
  trigger:
    - platform: state
      entity_id: sensor.switch_bedroom_action
      to: 'arrow_left_click'
  action:
    - service: light.turn_on
      entity_id: light.light_bedroom_light
      data:
        rgb_color: [255, 0, 0] #red
        brightness: 168

- alias: Bedroom Left Hold
  trigger:
    - platform: state
      entity_id: sensor.switch_bedroom_action
      to: 'arrow_left_hold'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.state_sleep

- alias: switch_bedroom_toggle_on
  trigger:
    - platform: state
      entity_id: sensor.switch_bedroom_action
      to: 'toggle'
  condition:
    - condition: state
      entity_id: light.light_bedroom_light
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.light_bedroom_light

- alias: switch_bedroom_toggle_off
  trigger:
    - platform: state
      entity_id: sensor.switch_bedroom_action
      to: 'toggle'
  condition:
    - condition: state
      entity_id: light.light_bedroom_light
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.light_bedroom_light
