- alias: Bathroom Light OFF
  trigger:
    - platform: state
      entity_id: light.shelly_bathroom
      to: 'on'
      for:
        minutes: 20
  action:
    service: light.turn_off
    entity_id: light.shelly_bathroom

- alias: Bathroom LED OFF
  trigger:
    - platform: state
      entity_id: light.bathroom_led
      to: 'on'
      for:
        minutes: 5
  action:
    service: light.turn_off
    entity_id: light.bathroom_led
