- alias: Bathroom OFF
  trigger:
    - platform: state
      entity_id: group.bathroom
      to: 'on'
      for:
        minutes: 30
  action:
    service: homeassistant.turn_off
    entity_id: group.bathroom
