- alias: Bathroom Light OFF
  id: bathroom_light_off
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_bathroom_occupancy
      to: 'off'
      for:
        minutes: 20
  action:
    service: light.turn_off
    entity_id: light.shelly_bathroom
