- alias: Bathroom Motion ON
  trigger:
    platform: state
    entity_id: binary_sensor.0x00158d000273269a_occupancy
    to: 'on'
  condition: !include ../../../condition/light.nosleep.yaml
  action:
    service: light.turn_on
    entity_id: light.bathroom_right


- alias: Bathroom Motion OFF
  trigger:
    platform: state
    entity_id: binary_sensor.0x00158d000273269a_occupancy
    to: 'off'
    for:
      minutes: 3
  action:
    service: light.turn_off
    entity_id: light.bathroom_right
