- alias: bathroom_switch_turn_on_led
  trigger:
    - platform: state
      entity_id: binary_sensor.shelly_bathroom_switch
  condition:
    - condition: state
      entity_id: light.shelly_bathroom
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.bathroom_led

- alias: bathroom_switch_turn_on_lavabo
  trigger:
    - platform: state
      entity_id: binary_sensor.shelly_bathroom_switch
  condition:
    - condition: state
      entity_id: light.bathroom_led
      state: 'on'
  action:
    - service: light.turn_on
      entity_id: light.shelly_bathroom

- alias: bathroom_switch_turn_off
  trigger:
    - platform: state
      entity_id: binary_sensor.shelly_bathroom_switch
  condition:
    - condition: state
      entity_id: light.bathroom_led
      state: 'on'
    - condition: state
      entity_id: light.shelly_bathroom
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.bathroom_led
    - service: light.turn_off
      entity_id: light.shelly_bathroom
