views:
  - badges: []
    title: Home
    path: home
    icon: mdi:home
    cards: !include home.yaml

  # - badges: []
  #   title: Staubi
  #   path: vacuum
  #   icon: mdi:vacuum
  #   cards: !include vacuum.yaml

  - badges: []
    title: E-Bike
    path: ebike
    icon: mdi:bike
    cards: !include ebike.yaml

  - badges: []
    title: Klima
    path: climate
    icon: mdi:thermometer
    cards: !include climate.yaml

  - badges: []
    title: Power
    path: power
    icon: mdi:home-lightning-bolt
    cards: !include power.yaml

  - badges: []
    title: Pflanzen
    path: plants
    icon: mdi:flower
    cards: !include plants.yaml

  - badges: []
    title: Media
    path: media
    icon: mdi:cast-connected
    cards: !include media.yaml
