- type: vertical-stack
  cards:

    - type: entities
      title: Klima (24h)
      entities:

        # CO2 24h
        - type: 'custom:mini-graph-card'
          name: CO²
          icon: mdi:molecule-co2
          entities:
            - entity: sensor.netatmo_home_indoor_co2
              name: Wohnzimmer
              show_state: true
            - entity: sensor.netatmo_home_indoor_buro_co2
              name: Büro
              show_state: true
          animate: true
          height: 190
          line_width: 4
          hour24: true
          hours_to_show: 24
          points_per_hour: 6
          group: true
          show:
            labels: true
            icon_adaptive_color: true
            extrema: true
            average: true
          color_thresholds:
            - value: 1600
              color: "#ff0000"
            - value: 400
              color: "#00ff00"
    
        # Temperatur 24h
        - type: 'custom:mini-graph-card'
          name: Temperatur
          icon: mdi:thermometer
          entities:
            - entity: sensor.netatmo_home_indoor_temperature
              name: Wohnzimmer
              show_state: true
            - entity: sensor.netatmo_home_indoor_buro_temperature
              name: Büro
            - entity: sensor.netatmo_home_indoor_aussen_temperature
              name: Aussen
              show_state: true
              show_fill: false
              y_axis: 'secondary'
          animate: true
          height: 190
          line_width: 4
          decimals: 1
          hour24: true
          hours_to_show: 24
          points_per_hour: 6
          group: true
          show:
            labels: true
            icon_adaptive_color: true
            extrema: true
            average: true
            labels_secondary: true
          color_thresholds:
            - value: 30
              color: "#ff0000"
            - value: 23
              color: "#00ff00"
            - value: 15
              color: "#0000ff"
        
        # Feuchtigkeit 24h
        - type: 'custom:mini-graph-card'
          name: Feuchtigkeit
          icon: mdi:water-percent
          entities:
            - entity: sensor.netatmo_home_indoor_humidity
              name: Wohnzimmer
              show_state: true
            - entity: sensor.netatmo_home_indoor_buro_humidity
              name: Büro
            - entity: sensor.netatmo_home_indoor_aussen_humidity
              name: Aussen
              show_state: true
              show_fill: false
              y_axis: 'secondary'
          animate: true
          height: 190
          line_width: 4
          hour24: true
          hours_to_show: 24
          points_per_hour: 6
          group: true
          tap_action:
            action: more-info
            entity: switch.humidifier
          show:
            labels: true
            icon_adaptive_color: true
            extrema: true
            average: true
            labels_secondary: true
          color_thresholds:
            - value: 30
              color: "#ff0000"
            - value: 45
              color: "#00ff00"
            - value: 60
              color: "#0000ff"


- type: vertical-stack
  cards:

    - type: entities
      title: Klima (7 Tage)
      entities:

        # CO2 7d
        - type: 'custom:mini-graph-card'
          name: CO²
          icon: mdi:molecule-co2
          entities:
            - entity: sensor.netatmo_home_indoor_co2
              name: Wohnzimmer
              show_state: true
            - entity: sensor.netatmo_home_indoor_buro_co2
              name: Büro
              show_state: true
            - entity: sensor.netatmo_home_indoor_pressure
              name: Luftdruck
              show_fill: false
              y_axis: secondary
              color: red
          animate: true
          height: 190
          line_width: 4
          hour24: true
          hours_to_show: 168
          points_per_hour: 1
          group: true
          show:
            labels: true
            icon_adaptive_color: true
            extrema: true
            average: true
            labels_secondary: true
          color_thresholds:
            - value: 1600
              color: "#ff0000"
            - value: 400
              color: "#00ff00"

        # Temperatur 7d
        - type: 'custom:mini-graph-card'
          name: Temperatur
          icon: mdi:thermometer
          entities:
            - entity: sensor.netatmo_home_indoor_aussen_temperature
              name: Aussen
              show_state: true
            - entity: sensor.netatmo_home_indoor_temperature
              name: Wohnzimmer
              show_state: true
              show_fill: false
              y_axis: 'secondary'
            - entity: sensor.netatmo_home_indoor_buro_temperature
              name: Büro
              show_fill: false
              y_axis: 'secondary'
          animate: true
          height: 190
          line_width: 4
          decimals: 1
          hour24: true
          hours_to_show: 168
          points_per_hour: 1
          group: true
          show:
            labels: true
            icon_adaptive_color: true
            extrema: true
            average: true
            labels_secondary: true
          color_thresholds:
            - value: 30
              color: "#ff0000"
            - value: 23
              color: "#00ff00"
            - value: 15
              color: "#0000ff"

        # Feuchtigkeit 7d
        - type: 'custom:mini-graph-card'
          name: Feuchtigkeit
          icon: mdi:water-percent
          entities:
            - entity: sensor.netatmo_home_indoor_aussen_humidity
              name: Aussen
              show_state: true
            - entity: sensor.netatmo_home_indoor_humidity
              name: Wohnzimmer
              show_state: true
              show_fill: false
              y_axis: 'secondary'
            - entity: sensor.netatmo_home_indoor_buro_humidity
              name: Büro
              show_fill: false
              y_axis: 'secondary'
          animate: true
          height: 190
          line_width: 4
          hour24: true
          hours_to_show: 168
          points_per_hour: 1
          group: true
          show:
            labels: true
            icon_adaptive_color: true
            extrema: true
            average: true
            labels_secondary: true
          color_thresholds:
            - value: 30
              color: "#ff0000"
            - value: 45
              color: "#00ff00"
            - value: 60
              color: "#0000ff"
