cellar_charge:
  sequence:

    - delay:
        hours: 2

    - wait_template: "{{ now().hour >= 20 or now().hour < 7 }}"
    
    - service: switch.turn_on
      entity_id:
        - switch.cellar_charger
        - switch.ebike
    
    - delay:
        hours: "{{ states('input_number.cellar_charger_hours') }}"

    - service: script.turn_off
      entity_id: 
        - script.cellar_charge
        - switch.ebike
    