cellar_charge:
  sequence:

    - delay:
        hours: 1

    - wait_template: "{{ now().hour >= 20 or now().hour < 7 }}"
    
    - service: switch.turn_on
      entity_id:
        - switch.cellar_charger
        - switch.ebike
