cellar_charge:
  sequence:

    - delay:
        hours: 2

    - wait_template: "{{ now().hour >= 20 or now().hour < 7 }}"
    
    - service: switch.turn_on
      entity_id: switch.cellar_charger
    
    - service: switch.turn_on
      entity_id: switch.mystrom_1

    - delay:
        hours: 5

    - service: switch.turn_off
      entity_id: switch.cellar_charger
    