cellar_charge:
  sequence:

    # set default settings
    - service: input_number.set_value
      entity_id: input_number.cellar_charger_hours
      data:
        value: 3
    - service: input_select.select_option
      data:
        entity_id: input_select.ebike_charging_limit
        option: 60%

    # turn on led
    - service: switch.turn_on
      entity_id: switch.cellar_charger_led

    # wait
    - delay:
        hours: 1
    - wait_template: "{{ now().hour >= 22 or now().hour < 7 }}"

    # turn on chargers
    - service: switch.turn_on
      entity_id: switch.cellar_charger
    - service: switch.turn_on
      entity_id: switch.ebike

    # wait
    - delay:
        minutes: 1

    # wait for chargers done
    - wait_template: "{{ is_state('switch.cellar_charger', 'off') }}"
    - wait_template: "{{ is_state('switch.ebike', 'off') }}"

    - service: script.cellar_charge_stop


cellar_charge_stop:
  sequence:
    # turn off chargers
    - service: switch.turn_off
      entity_id: switch.cellar_charger
    - service: switch.turn_off
      entity_id: switch.ebike
    # turn off led
    - service: switch.turn_off
      entity_id: switch.cellar_charger_led


ebike_charge:
  sequence:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.ebike_charging_limit
        option: "{{ ebike_charging_limit }}"
    - service: switch.turn_on
      entity_id: switch.ebike
