cellar_charge:
  sequence:

    - delay:
        hours: 3
    
    - service: switch.turn_on
      entity_id: switch.cellar_charger
    
    - service: switch.turn_on
      entity_id: switch.mystrom_1

    - delay:
        hours: 5

    - service: switch.turn_off
      entity_id: switch.cellar_charger
    