- platform: mqtt
  name: floor
  state_topic: "homie/floor-light/switch/state"
  command_topic: "homie/floor-light/switch/state/set"

- platform: mqtt
  name: kitchen
  state_topic: "homie/kitchen-light/switch/state"
  command_topic: "homie/kitchen-light/switch/state/set"

- platform: mqtt
  name: wc
  state_topic: "homie/wc-light/switch/state"
  command_topic: "homie/wc-light/switch/state/set"

- platform: mqtt
  name: bathroom_led
  state_topic: "homie/badroom-light/switch/state"
  command_topic: "homie/badroom-light/switch/state/set"
