- alias: Command Espresso ON
  trigger:
    - platform: mqtt
      topic: cmd/espresso
      payload: 'on'
  action:
    service: switch.turn_on
    entity_id: switch.espresso


- alias: Espresso OFF
  trigger:
    - platform: state
      entity_id: switch.espresso
      to: 'on'
      for:
        minutes: 20
  action:
    service: switch.turn_off
    entity_id: switch.espresso


- alias: Espresso ON Wakeup Alarm
  trigger:
    - platform: time
      at: sensor.florian_handy_next_alarm
  action:
    service: script.wakeup
