- alias: Espresso OFF
  id: espresso off
  trigger:
    - platform: state
      entity_id: switch.espresso
      to: 'on'
      for:
        minutes: 30
  action:
    service: switch.turn_off
    entity_id: switch.espresso

- alias: Espresso Heatup
  id: espresso heatup
  trigger:
    - platform: numeric_state
      entity_id: sensor.temperature_espresso
      above: 60
    - platform: state
      entity_id: switch.espresso
      to: 'on'
      for:
        minutes: 10
  condition:
    - condition: numeric_state
      entity_id: sensor.temperature_espresso
      above: 60
    - condition: state
      entity_id: switch.espresso
      state: 'on'
      for:
        minutes: 10
  action:
    - service: switch.turn_off
      entity_id: switch.espresso
    - service: script.notify_google
      data:
        language: it
        message: 'espresso isch fertig'
        message_say: 'espresso isch fertig'
