- alias: Espresso OFF
  trigger:
    - platform: state
      entity_id: switch.espresso
      to: 'on'
      for:
        minutes: 20
  action:
    service: switch.turn_off
    entity_id: switch.espresso
