- alias: Command Espresso ON
  trigger:
    - platform: mqtt
      topic: cmd/espresso
      payload: 'on'
  action:
    service: switch.turn_on
    entity_id: switch.espresso


- alias: Espresso OFF
  trigger:
    - platform: state
      entity_id: switch.espresso
      to: 'on'
      for:
        minutes: 60
  action:
    service: switch.turn_off
    entity_id: switch.espresso


- alias: Espresso Notify
  trigger:
    - platform: numeric_state
      entity_id: sensor.temperature_kitchen
      above: 45
  action:
    - service: notify.flo
      data:
        title: Espresso
        message: 'Espresso ist heiss'
    - service: tts.google_say
      entity_id: media_player.home_group
      data:
        language: de
        message: 'kafi isch ufgwärmt'
