- alias: motion_on_kitchen
  id: motion_on_kitchen
  trigger:
    platform: state
    entity_id: binary_sensor.motion_kitchen
    to: 'on'
  condition: !include ../../../condition/light_livingroom.yaml
  action:
    service: light.turn_on
    entity_id: light.kitchen_ceiling

- alias: motion_off_kitchen
  id: motion_off_kitchen
  trigger:
    platform: state
    entity_id: binary_sensor.motion_kitchen
    to: 'off'
    for:
      seconds: 60
  action:
    service: light.turn_off
    entity_id: light.kitchen_ceiling

- alias: motion_off_long_kitchen
  id: motion_off_long_kitchen
  trigger:
    platform: state
    entity_id: binary_sensor.motion_kitchen
    to: 'off'
    for:
      minutes: 5
  action:
    - service: light.turn_off
      entity_id: light.kitchen_ceiling
    - service: light.turn_off
      entity_id: light.shelly_kitchen

- alias: motion_off_disable_kitchen
  id: motion_off_disable_kitchen
  trigger:
    - platform: state
      entity_id: binary_sensor.shelly_kitchen_switch
  condition:
    - condition: state
      entity_id: light.shelly_kitchen
      state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: automation.motion_off_kitchen
    - service: light.turn_on
      entity_id: light.kitchen_ceiling
    - service: light.turn_on
      entity_id: light.shelly_kitchen

- alias: motion_reset_kitchen
  id: motion_reset_kitchen
  trigger:
    - platform: state
      entity_id: light.shelly_kitchen
      to: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: automation.motion_off_kitchen
