- alias: workroom_co2_warning_on
  trigger:
    - platform: numeric_state
      entity_id: sensor.netatmo_home_indoor_buro_co2
      above: 1000
    - platform: state
      entity_id: binary_sensor.motion_workroom_occupancy
      to: 'on'
  condition:
    - condition: and
      conditions: !include ../../../condition/awake.yaml
    - condition: numeric_state
      entity_id: sensor.netatmo_home_indoor_buro_co2
      above: 1000
    - condition: template
      value_template: >
        {% set motion = states.binary_sensor.motion_workroom_occupancy %}
        {{ motion.state == 'on' or
          (now() - motion.last_changed).total_seconds() <= 90*60 }}
  action:
    service: light.turn_on
    entity_id: light.workroom_co2_light


- alias: workroom_co2_warning_off
  trigger:
    - platform: numeric_state
      entity_id: sensor.netatmo_home_indoor_buro_co2
      below: 1000
  action:
    service: light.turn_off
    entity_id: light.workroom_co2_light
