- alias: workroom_illuminance_high
  trigger:
    - platform: numeric_state
      entity_id: sensor.motion_workroom_illuminance
      above: 50
  action:
    - service: light.turn_off
      entity_id: light.light_workroom_light
    - service: light.turn_off
      entity_id: light.workroom_salt_light
