- alias: workroom_illuminance_high
  id: workroom_illuminance_high
  trigger:
    - platform: numeric_state
      entity_id: sensor.motion_office_illuminance
      above: 300
    - platform: numeric_state
      entity_id: sensor.motion_office_tuya_illuminance
      above: 2000
  action:
    - service: light.turn_off
      entity_id: light.light_office
    - service: light.turn_off
      entity_id: light.workroom_desk
