- alias: workroom_motion_on
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_workroom_occupancy
      to: 'on'
  condition:
    - condition: and
      conditions: !include ../../../condition/awake.yaml
    - condition: or
      conditions:
        - condition: and
          conditions: !include ../../../condition/night.yaml
        - condition: numeric_state
          entity_id: sensor.motion_workroom_illuminance
          below: 60
  action:
    - service: light.turn_on
      entity_id: light.light_workroom_light


- alias: workroom_motion_off
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_workroom_occupancy
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.state_workroom
      state: 'off'
  action:
    - service: light.turn_off
      entity_id: light.light_workroom_light
    - service: light.turn_off
      entity_id: light.workroom_co2_light
    - service: light.turn_off
      entity_id: light.workroom_salt_light


- alias: workroom_motion_off_long
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_workroom_occupancy
      to: 'off'
      for:
        minutes: 90
  action:
    - service: light.turn_off
      entity_id: light.light_workroom_light
    - service: light.turn_off
      entity_id: light.workroom_co2_light
    - service: light.turn_off
      entity_id: light.workroom_salt_light
