- alias: workroom_motion_on
  id: workroom_motion_on
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_office_tuya_occupancy
      to: 'on'
  condition:
    - condition: and
      conditions: !include ../../../condition/awake.yaml
    - condition: and
      conditions: !include ../../../condition/illuminance_workroom.yaml
  action:
    - service: light.turn_on
      entity_id: light.light_office
    

- alias: workroom_desk_motion_on
  id: workroom_desk_motion_on
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_office_occupancy
      to: 'on'
  condition:
    - condition: and
      conditions: !include ../../../condition/awake.yaml
  action:
    - service: light.turn_on
      entity_id: light.yeelight_lamp15_0x1e6af9d3_ambilight
    - service: light.turn_on
      entity_id: light.yeelight_lamp15_0x1e64183a_ambilight
    - condition: and
      conditions: !include ../../../condition/illuminance_workroom.yaml
    - service: light.turn_on
      entity_id: light.yeelight_lamp15_0x1e6af9d3
    - service: light.turn_on
      entity_id: light.yeelight_lamp15_0x1e64183a
  

- alias: workroom_motion_off
  id: workroom_motion_off
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_office_occupancy
      to: 'off'
      for:
        minutes: 5
    - platform: state
      entity_id: binary_sensor.motion_office_tuya_occupancy
      to: 'off'
      for:
        minutes: 5
  condition:
    - condition: state
      entity_id: binary_sensor.motion_office_occupancy
      state: 'off'
      for:
        minutes: 5
    - condition: state
      entity_id: binary_sensor.motion_office_tuya_occupancy
      state: 'off'
      for:
        minutes: 5
  action:
    - service: light.turn_off
      entity_id: light.light_office
    - service: light.turn_off
      entity_id: light.yeelight_lamp15_0x1e6af9d3
    - service: light.turn_off
      entity_id: light.yeelight_lamp15_0x1e64183a
    - service: light.turn_off
      entity_id: light.yeelight_lamp15_0x1e6af9d3_ambilight
    - service: light.turn_off
      entity_id: light.yeelight_lamp15_0x1e64183a_ambilight
    