- alias: workroom_motion_on
  id: workroom_motion_on
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_workroom_tuya_occupancy
      to: 'on'
  condition:
    - condition: and
      conditions: !include ../../../condition/awake.yaml
    - condition: and
      conditions: !include ../../../condition/illuminance_workroom.yaml
  action:
    - service: light.turn_on
      entity_id: light.light_workroom
    

- alias: workroom_desk_motion_on
  id: workroom_desk_motion_on
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_workroom_occupancy
      to: 'on'
  condition:
    - condition: and
      conditions: !include ../../../condition/awake.yaml
  action:
    - service: light.turn_on
      entity_id: light.workroom_desk_ambilight
    - condition: and
      conditions: !include ../../../condition/illuminance_workroom.yaml
    - service: light.turn_on
      entity_id: light.workroom_desk
  

- alias: workroom_motion_off
  id: workroom_motion_off
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_workroom_occupancy
      to: 'off'
      for:
        minutes: 5
    - platform: state
      entity_id: binary_sensor.motion_workroom_tuya_occupancy
      to: 'off'
      for:
        minutes: 5
  condition:
    - condition: state
      entity_id: binary_sensor.motion_workroom_occupancy
      state: 'off'
      for:
        minutes: 5
    - condition: state
      entity_id: binary_sensor.motion_workroom_tuya_occupancy
      state: 'off'
      for:
        minutes: 5
  action:
    - service: light.turn_off
      entity_id: light.light_workroom
    - service: light.turn_off
      entity_id: light.workroom_desk
    - service: light.turn_off
      entity_id: light.workroom_desk_ambilight
    