- alias: workroom_motion_on
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_workroom_occupancy
      to: 'on'
  condition:
    - condition: and
      conditions: !include ../../../condition/awake.yaml
    - condition: and
      conditions: !include ../../../condition/illuminance_workroom.yaml
  action:
    - service: script.workroom_on


- alias: workroom_motion_off
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_workroom_occupancy
      to: 'off'
      for:
        minutes: 15
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: input_boolean.state_workroom
          state: 'off'
        - condition: state
          entity_id: binary_sensor.motion_workroom_occupancy
          state: 'off'
          for:
            minutes: 60
  action:
    - service: script.workroom_off
