- alias: workroom_motion_on
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_workroom_occupancy
      to: 'on'
  condition:
    - condition: and
      conditions: !include ../../../condition/awake.yaml
    - condition: and
      conditions: !include ../../../condition/illuminance_workroom.yaml
  action:
    - service: light.turn_on
      entity_id: light.light_workroom
    - service: light.turn_off
      entity_id: light.workroom_desk_ambilight
  

- alias: workroom_motion_off
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_workroom_occupancy
      to: 'off'
      for:
        minutes: 15
  action:
    - service: light.turn_off
      entity_id: light.light_workroom
