- alias: workroom_salt_on
  trigger:
    - platform: state
      entity_id: light.workroom_salt_light
      to: 'on'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.state_workroom
