- alias: workroom_switch_toggle
  id: workroom_switch_toggle
  trigger:
    - platform: state
      entity_id: binary_sensor.shelly_workroom_switch
  action:
    - service: light.toggle
      entity_id: light.light_workroom
