wohnzimmer_assistent_volume_awake:
  name: Google Assistent Volume Livingroom - Awake
  mode: slider
  min: 0
  max: 1
  step: 0.01

wohnzimmer_assistent_volume_sleep:
  name: Google Assistent Volume Livingroom Sleep
  mode: slider
  min: 0
  max: 1
  step: 0.01

schlafzimmer_assistent_volume_awake:
  name: Google Assistent Volume Bedroom - Awake
  mode: slider
  min: 0
  max: 1
  step: 0.01

schlafzimmer_assistent_volume_sleep:
  name: Google Assistent Volume Bedroom Sleep
  mode: slider
  min: 0
  max: 1
  step: 0.01
