# Single
espresso_mill_amount_single:
  name: Esprosso Mill Amount Single
  unit_of_measurement: g
  mode: slider
  initial: 9
  min: 7
  max: 11
  step: 0.1

espresso_mill_amount_measure_single:
  name: Esprosso Mill Amount Measure Single
  unit_of_measurement: g
  mode: slider
  initial: 9
  min: 3
  max: 15
  step: 0.1

espresso_mill_time_single:
  name: Esprosso Mill Time Single
  unit_of_measurement: s
  mode: slider
  initial: 10
  min: 1
  max: 30
  step: 0.01

# Double
espresso_mill_amount_double:
  name: Esprosso Mill Amount Double
  unit_of_measurement: g
  mode: slider
  initial: 14
  min: 12
  max: 16
  step: 0.1

espresso_mill_amount_measure_double:
  name: Esprosso Mill Amount Measure Double
  unit_of_measurement: g
  mode: slider
  initial: 14
  min: 8
  max: 20
  step: 0.1

espresso_mill_time_double:
  name: Esprosso Mill Time Double
  unit_of_measurement: s
  mode: slider
  initial: 10
  min: 1
  max: 30
  step: 0.01
