espresso_mill_learning_rate:
  name: Esprosso Mill Learning Rate
  mode: slider
  min: 0.0
  max: 1.0
  step: 0.1

# Single
espresso_mill_amount_single:
  name: Esprosso Mill Amount Single
  unit_of_measurement: g
  mode: slider
  min: 7
  max: 11
  step: 0.1

espresso_mill_amount_measure_single:
  name: Esprosso Mill Amount Measure Single
  unit_of_measurement: g
  mode: slider
  min: 3
  max: 15
  step: 0.1

espresso_mill_time_single:
  name: Esprosso Mill Time Single
  unit_of_measurement: s
  mode: slider
  min: 1
  max: 20
  step: 0.01

# Double
espresso_mill_amount_double:
  name: Esprosso Mill Amount Double
  unit_of_measurement: g
  mode: slider
  min: 12
  max: 16
  step: 0.1

espresso_mill_amount_measure_double:
  name: Esprosso Mill Amount Measure Double
  unit_of_measurement: g
  mode: slider
  min: 8
  max: 20
  step: 0.1

espresso_mill_time_double:
  name: Esprosso Mill Time Double
  unit_of_measurement: s
  mode: slider
  min: 1
  max: 20
  step: 0.01

# Triple
espresso_mill_amount_triple:
  name: Esprosso Mill Amount Triple
  unit_of_measurement: g
  mode: slider
  min: 15
  max: 21
  step: 0.1

espresso_mill_amount_measure_triple:
  name: Esprosso Mill Amount Measure Triple
  unit_of_measurement: g
  mode: slider
  min: 11
  max: 25
  step: 0.1

espresso_mill_time_triple:
  name: Esprosso Mill Time Triple
  unit_of_measurement: s
  mode: slider
  min: 1
  max: 30
  step: 0.01
