vacuum_room_entrance:
  mode: box
  min: 1
  max: 100
  initial: 19

vacuum_room_floor:
  mode: box
  min: 1
  max: 100
  initial: 23

vacuum_room_wc:
  mode: box
  min: 1
  max: 100
  initial: 21

vacuum_room_bathroom:
  mode: box
  min: 1
  max: 100
  initial: 22

vacuum_room_workroom:
  mode: box
  min: 1
  max: 100
  initial: 18

vacuum_room_kitchen:
  mode: box
  min: 1
  max: 100
  initial: 17

vacuum_room_livingroom:
  mode: box
  min: 1
  max: 100
  initial: 24

vacuum_room_livingroom_table:
  mode: box
  min: 1
  max: 100
  initial: 20

vacuum_room_bedroom:
  mode: box
  min: 1
  max: 100
  initial: 16
