automation:
  - alias: switch_bedroom_sleep
    id: switch_bedroom_sleep
    mode: restart
    triggers:
      - trigger: state
        entity_id: sensor.switch_bedroom_action
        to: "single_right"
    actions:
      - action: script.manual_sleep

  - alias: switch_bedroom_wakeup
    id: switch_bedroom_wakeup
    mode: restart
    triggers:
      - trigger: state
        entity_id: sensor.switch_bedroom_action
        to: "single_left"
    actions:
      - action: script.manual_wakeup

  - alias: switch_bedroom_sleep_light
    id: switch_bedroom_sleep_light
    mode: restart
    triggers:
      - trigger: state
        entity_id: sensor.switch_bedroom_action
        to: "single_both"
    actions:
      - action: script.manual_sleep_light_only

script:
  manual_sleep:
    sequence:
      # tv off
      - action: media_player.turn_off
        entity_id: media_player.schlafzimmer_tv_android

      # sleep on
      - action: input_boolean.turn_on
        continue_on_error: true
        entity_id: input_boolean.state_sleep

      # all off
      - action: script.turn_on
        entity_id: script.all_off
        continue_on_error: true

      - delay:
          seconds: 1

      - wait_template: "{{ not is_state('script.all_off', 'on') }}"

      - action: script.sleep_radio

  sleep_radio:
    sequence:
      - action: media_player.play_media
        entity_id: media_player.schlafzimmer_assistant
        data_template:
          media_content_id: "{{ states('sensor.sleep_podcast') }}"
          media_content_type: rss

  manual_wakeup:
    sequence:
      # sleep off
      - action: input_boolean.turn_off
        entity_id: input_boolean.state_sleep
      # espresso on
      - action: switch.turn_on
        entity_id: switch.espresso
      # radio
      - action: script.music_radio_srf4
      # wait 1h
      - delay:
          hours: 1
      # media off
      - action: script.music_turn_off

  manual_sleep_light_only:
    sequence:
      # sleep on
      - action: input_boolean.turn_on
        entity_id: input_boolean.state_sleep
      # wait 2h
      - delay:
          hours: 2
      # tv off
      - action: media_player.turn_off
        entity_id: media_player.schlafzimmer_tv_android
