automation:
  - alias: switch_bedroom_right
    id: switch_bedroom_right
    mode: restart
    triggers:
      - trigger: state
        entity_id: sensor.switch_bedroom_action
        to: 'single_right'
    actions:
      # tv off
      - action: media_player.turn_off
        entity_id: media_player.schlafzimmer_tv_android

      # sleep on
      - action: input_boolean.turn_on
        continue_on_error: true
        entity_id: input_boolean.state_sleep

      # all off
      - action: script.turn_on
        entity_id: script.all_off
        continue_on_error: true

      - delay:
          seconds: 1

      - wait_template: "{{ not is_state('script.all_off', 'on') }}"
      
      - action: google_assistant_sdk.send_text_command
        data_template:
          command: "{{ states('input_text.sleep_assistant_prompt') }}"


  - alias: switch_bedroom_left
    id: switch_bedroom_left
    mode: restart
    triggers:
      - trigger: state
        entity_id: sensor.switch_bedroom_action
        to: 'single_left'
    actions:
      # sleep off
      - action: input_boolean.turn_off
        entity_id: input_boolean.state_sleep
      # espresso on
      - action: switch.turn_on
        entity_id: switch.espresso
      # radio
      - action: script.music_radio_srf4
      # wait 1h
      - delay:
          hours: 1
      # media off
      - action: script.music_turn_off

  - alias: switch_bedroom_both
    id: switch_bedroom_both
    mode: restart
    triggers:
      - trigger: state
        entity_id: sensor.switch_bedroom_action
        to: 'single_both'
    actions:
      # sleep on
      - action: input_boolean.turn_on
        entity_id: input_boolean.state_sleep
      # wait 2h
      - delay:
          hours: 2
      # tv off
      - action: media_player.turn_off
        entity_id: media_player.schlafzimmer_tv_android
