automation:
  - alias: Floor Switch LEFT
    id: floor_switch_left
    trigger:
      - platform: state
        entity_id: sensor.switch_door_action
        to: 'single_left'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.state_home

  - alias: Floor Switch RIGHT
    id: floor_switch_right
    trigger:
      - platform: state
        entity_id: sensor.switch_door_action
        to: 'single_right'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.state_sleep

  - alias: Floor Switch Both
    id: floor_switch_both
    trigger:
      - platform: state
        entity_id: sensor.switch_door_action
        to: 'single_both'
    action:
      - service: script.tesla_climate
