automation:
  - alias: Floor Switch LEFT
    id: floor_switch_left
    triggers:
      - trigger: state
        entity_id: sensor.switch_door_action
        to: 'single_left'
    actions:
      - action: input_boolean.turn_off
        entity_id: input_boolean.state_home

  - alias: Floor Switch RIGHT
    id: floor_switch_right
    triggers:
      - trigger: state
        entity_id: sensor.switch_door_action
        to: 'single_right'
    actions:
      - action: input_boolean.turn_on
        entity_id: input_boolean.state_sleep

  - alias: Floor Switch Both
    id: floor_switch_both
    triggers:
      - trigger: state
        entity_id: sensor.switch_door_action
        to: 'single_both'
    actions:
      - action: script.tesla_climate
