automation:
  - alias: Door Open
    id: door_open
    mode: restart
    triggers:
      - trigger: state
        entity_id: binary_sensor.sensor_door_contact
        to: "on"
    actions:
      - action: input_boolean.turn_on
        entity_id: input_boolean.state_home
      - action: input_boolean.turn_off
        entity_id: input_boolean.state_sleep
      # light
      - condition: state
        entity_id: binary_sensor.condition_light
        state: "on"
      - action: light.turn_on
        entity_id: light.light_door
      - action: light.turn_on
        entity_id: light.floor
