automation:
  - alias: Floor Motion ON
    id: floor_motion_on
    triggers:
      - trigger: state
        entity_id: binary_sensor.motion_floor
        to: "on"
    conditions:
      - condition: state
        entity_id: binary_sensor.condition_light
        state: "on"
    actions:
      - action: light.turn_on
        entity_id: light.floor

  - alias: Floor Motion OFF
    id: floor_motion_off
    triggers:
      - trigger: state
        entity_id: binary_sensor.motion_floor
        to: "off"
        for:
          minutes: 1
    actions:
      - action: light.turn_off
        entity_id: light.floor
      - action: light.turn_off
        entity_id: light.light_door

  - alias: Floor Motion ON (Sleep) -> WC
    id: floor_motion_on_sleep_wc
    triggers:
      - trigger: state
        entity_id: binary_sensor.motion_floor
        to: "on"
    conditions:
      - condition: state
        entity_id: input_boolean.state_sleep
        state: "on"
    actions:
      - action: light.turn_on
        entity_id: light.wc_led
