automation:
  - alias: Espresso OFF
    id: espresso_off
    mode: restart
    triggers:
      - trigger: state
        entity_id: switch.espresso
        to: "on"
        for:
          minutes: 30
    actions:
      - action: switch.turn_off
        entity_id: switch.espresso

  - alias: Espresso Heatup
    id: espresso_heatup
    mode: restart
    triggers:
      - trigger: numeric_state
        entity_id: sensor.temperature_espresso
        above: 60
      - trigger: state
        entity_id: switch.espresso
        to: "on"
        for:
          minutes: 10
    conditions:
      - condition: numeric_state
        entity_id: sensor.temperature_espresso
        above: 60
      - condition: state
        entity_id: switch.espresso
        state: "on"
        for:
          minutes: 10
    actions:
      - action: switch.turn_off
        entity_id: switch.espresso
      - action: script.notify_google
        data:
          language: it
          message: "espresso isch fertig"
          message_say: "espresso isch fertig"

script:
  entkalken:
    mode: restart
    sequence:
      - repeat:
          while:
            - condition: template
              value_template: "true"
          sequence:
            - action: switch.turn_on
              entity_id: switch.espresso
            - delay:
                minutes: 1
            - action: switch.turn_off
              entity_id: switch.espresso
            - delay:
                minutes: 1
