input_select:
  state_livingroom_light:
    name: Wohnzimmer Licht
    options:
      - Aus
      - TV
      - Normal
      - Max

  mode_livingroom_light:
    name: Wohnzimmer Licht Mode
    options:
      - TV
      - Normal
      - Max

script:
  livingroom_light_scene_aus:
    sequence:
      - action: light.turn_off
        entity_id: light.group_livingroom
      - action: light.turn_off
        entity_id: light.group_dining_table_lamp

  livingroom_light_scene_tv:
    sequence:
      - action: light.turn_off
        entity_id: light.livingroom_sofatable
      - action: light.turn_on
        entity_id: light.livingroom_rgbww
        data:
          brightness_pct: 100
          effect: none
          rgbww_color: [255, 0, 0, 0, 150]
      - action: light.turn_off
        entity_id: light.wohnzimmer_tv_ambilight
      - action: light.turn_on
        entity_id: light.wohnzimmer_tv_ambilight
        data:
          brightness_pct: 100
          effect: "FOLLOW_VIDEO: VIVID"
      - action: light.turn_on
        entity_id: light.light_dining_table_led
        data:
          brightness_pct: 100
          effect: none
          rgb_color: [255, 120, 0]

  livingroom_light_scene_normal:
    sequence:
      - action: light.turn_on
        entity_id: light.livingroom_sofatable
      - action: light.turn_on
        entity_id: light.livingroom_rgbww
        data:
          brightness_pct: 100
          effect: none
          rgbww_color: [255, 0, 0, 0, 200]
      - action: light.turn_on
        entity_id: light.wohnzimmer_tv_ambilight
        data:
          brightness_pct: 100
          rgb_color: [255, 100, 0]
          effect: "Mode: manual"
      - action: light.turn_on
        entity_id: light.light_dining_table_led
        data:
          brightness_pct: 100
          effect: none
          rgb_color: [255, 120, 0]

  livingroom_light_scene_max:
    sequence:
      - action: light.turn_on
        entity_id: light.livingroom_sofatable
      - action: light.turn_on
        entity_id: light.livingroom_rgbww
        data:
          brightness_pct: 100
          effect: none
          rgbww_color: [255, 255, 255, 255, 255]
      - action: light.turn_on
        entity_id: light.shelly_diningtable
      - action: light.turn_on
        entity_id: light.wohnzimmer_tv_ambilight
        data:
          brightness_pct: 100
          rgb_color: [255, 255, 255]
          effect: "Mode: manual"
      - action: light.turn_on
        entity_id: light.light_dining_table_led
        data:
          brightness_pct: 100
          effect: none
          rgb_color: [255, 255, 255]

  livingroom_light_scene:
    fields:
      light_mode:
        name: Light Mode
        required: true
    sequence:
      - action: input_select.select_option
        data:
          entity_id: input_select.state_livingroom_light
          option: "{{ light_mode }}"
      - action: >-
          {{ "script.livingroom_light_scene_" + states('input_select.state_livingroom_light') | lower }}

automation:
  - alias: livingroom_light_scene
    id: livingroom_light_scene
    mode: restart
    triggers:
      - trigger: state
        entity_id: input_select.state_livingroom_light
    actions:
      - if:
          not:
            condition: state
            entity_id: input_select.state_livingroom_light
            state: "Aus"
        then:
          - action: input_select.select_option
            data_template:
              entity_id: input_select.mode_livingroom_light
              option: "{{ states('input_select.state_livingroom_light') }}"
      - action: >-
          {{ "script.livingroom_light_scene_" + states('input_select.state_livingroom_light') | lower }}
