automation:
  - alias: wohnzimmer_tv_on
    id: wohnzimmer_tv_on
    triggers:
      - trigger: state
        entity_id: media_player.wohnzimmer_tv
        to: 'on'
    actions:
      - action: script.livingroom_light
        data:
          mode: TV
      - action: script.receiver_on

  - alias: wohnzimmer_tv_off
    id: wohnzimmer_tv_off
    triggers:
      - trigger: state
        entity_id: media_player.wohnzimmer_tv
        from: 'on'
    actions:
      - action: script.livingroom_light
        data:
          mode: Normal
      - action: script.turn_on
        entity_id: script.receiver_off

script:
  receiver_on:
    mode: restart
    sequence:
      # disable off script
      - action: script.turn_off
        entity_id: script.receiver_off

      - action: script.ir_receiver_tv

  receiver_off:
    mode: restart
    sequence:
      # disable on script
      - action: script.turn_off
        entity_id: script.receiver_on

      - action: script.ir_receiver_tv
      - delay:
          seconds: 10
      - action: script.ir_receiver_power
