template:
  - binary_sensor:
      - name: office_condition_light
        state: >
          {{
            is_state('binary_sensor.condition_awake', 'on')
            and
            (
              is_state('binary_sensor.condition_night', 'on')
              or
              states('sensor.motion_office_illuminance') | int < 100
              or
              states('sensor.motion_office_tuya_illuminance') | int < 1500
            )
          }}

automation:
  - alias: workroom_motion_on
    id: workroom_motion_on
    mode: restart
    triggers:
      - trigger: state
        entity_id: binary_sensor.motion_office_tuya_occupancy
        to: "on"
    conditions:
      - condition: state
        entity_id: binary_sensor.office_condition_light
        state: "on"
    actions:
      - action: light.turn_on
        entity_id: light.group_office_ceiling

  - alias: workroom_desk_motion_on
    id: workroom_desk_motion_on
    mode: restart
    triggers:
      - trigger: state
        entity_id: binary_sensor.motion_office_occupancy
        to: "on"
    conditions:
      - condition: state
        entity_id: binary_sensor.condition_awake
        state: "on"
    actions:
      - action: light.turn_on
        entity_id: light.group_office_desk_monitor_ambilight
      - condition: state
        entity_id: binary_sensor.office_condition_light
        state: "on"
      - action: light.turn_on
        entity_id: light.group_office_desk_monitor

  - alias: workroom_motion_off
    id: workroom_motion_off
    mode: restart
    triggers:
      - trigger: state
        entity_id: binary_sensor.motion_office_occupancy
        to: "off"
        for:
          minutes: 10
      - trigger: state
        entity_id: binary_sensor.motion_office_tuya_occupancy
        to: "off"
        for:
          minutes: 10
    conditions:
      - condition: state
        entity_id: binary_sensor.motion_office_occupancy
        state: "off"
        for:
          minutes: 10
      - condition: state
        entity_id: binary_sensor.motion_office_tuya_occupancy
        state: "off"
        for:
          minutes: 10
    actions:
      - action: light.turn_off
        entity_id: light.group_office

  - alias: workroom_illuminance_high
    id: workroom_illuminance_high
    mode: restart
    triggers:
      - trigger: numeric_state
        entity_id: sensor.motion_office_illuminance
        above: 400
    actions:
      - action: light.turn_off
        entity_id: light.group_office_ceiling

  - alias: wardrobe_open
    id: wardrobe_open
    mode: restart
    triggers:
      - trigger: state
        entity_id:
          - binary_sensor.motion_wardrobe_occupancy
        to: "on"
    actions:
      - action: light.turn_on
        entity_id: light.office_tuya
        data:
          brightness_pct: 100

  - alias: wardrobe_close
    id: wardrobe_close
    mode: restart
    triggers:
      - trigger: state
        entity_id:
          - binary_sensor.motion_wardrobe_occupancy
        to: "off"
    conditions:
      - condition: state
        entity_id: light.group_office_ceiling
        state: "on"
    actions:
      - action: light.turn_on
        entity_id: light.office_tuya
        data:
          brightness: 1
