automation:
  - alias: workroom_switch_toggle
    id: workroom_switch_toggle
    mode: restart
    triggers:
      - trigger: state
        entity_id: binary_sensor.shelly_office_input
    actions:
      - action: light.toggle
        entity_id: light.group_office_ceiling
