automation:
  - alias: workroom_switch_toggle
    id: workroom_switch_toggle
    trigger:
      - platform: state
        entity_id: binary_sensor.shelly_office_input
    action:
      - service: light.toggle
        entity_id: light.light_office
