automation:
  - alias: WC Motion ON
    id: wc_motion_on
    mode: restart
    triggers:
      - trigger: state
        entity_id: binary_sensor.motion_wc
        to: "on"
    conditions:
      - condition: state
        entity_id: binary_sensor.condition_illumninance
        state: "on"
    actions:
      - action: light.turn_on
        entity_id: light.wc_led

  - alias: WC Motion OFF
    id: wc_motion_off
    mode: restart
    triggers:
      - trigger: state
        entity_id: binary_sensor.motion_wc
        to: "off"
        for:
          minutes: 5
    actions:
      - action: light.turn_off
        entity_id: light.wc_led

  - alias: WC Motion OFF Long
    id: wc_motion_off_long
    mode: restart
    triggers:
      - trigger: state
        entity_id: binary_sensor.motion_wc
        to: "off"
        for:
          minutes: 5
    actions:
      - action: light.turn_off
        entity_id: light.shelly_wc
