- alias: Home OFF
  trigger:
    - platform: state
      entity_id: input_boolean.state_home
      to: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.all_off
    - service: media_player.media_stop
      entity_id: media_player.googlehome7490
    - service: media_player.media_stop
      entity_id: media_player.googlehome4508
    - service: media_player.media_stop
      entity_id: media_player.home_group

- alias: Home ON Livingroom Light Mode Normal
  trigger:
    - platform: state
      entity_id: input_boolean.state_home
      to: 'off'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.mode_livingroom_light
        option: 'Normal'
