- alias: state_home_off
  trigger:
    - platform: state
      entity_id: input_boolean.state_home
      to: 'off'
  action:
    - service: script.turn_on
      entity_id: script.all_off
    # google
    - service: media_player.media_stop
      entity_id: media_player.wohnzimmer_assistent
    - service: media_player.media_stop
      entity_id: media_player.schlafzimmer_assistent
    - service: media_player.media_stop
      entity_id: media_player.home_group
    # vacuum
    - service: vacuum.start
      entity_id: vacuum.staubi

- alias: state_home_on
  trigger:
    - platform: state
      entity_id: input_boolean.state_home
      to: 'on'
  action:
    # states
    - service: input_boolean.turn_off
      entity_id: input_boolean.state_workroom
    - service: input_boolean.turn_off
      entity_id: input_boolean.state_fitnessroom
    # light
    - service: input_select.select_option
      data:
        entity_id: input_select.mode_livingroom_light
        option: 'Chill'
    - service: light.turn_on
      entity_id: light.shelly_diningtable
