- alias: Home OFF
  trigger:
    - platform: state
      entity_id: input_boolean.state_home
      to: 'off'
  action:
    - service: script.turn_on
      entity_id: script.all_off
    # google
    - service: media_player.media_stop
      entity_id: media_player.wohnzimmer_assistant
    - service: media_player.media_stop
      entity_id: media_player.schlafzimmer_assistant
    - service: media_player.media_stop
      entity_id: media_player.home_group
    # vacuum
    - service: vacuum.start
      entity_id: vacuum.xiaomi_vacuum

- alias: Home ON Livingroom Light Mode Chill
  trigger:
    - platform: state
      entity_id: input_boolean.state_home
      to: 'off'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.mode_livingroom_light
        option: 'Chill'
    - service: light.turn_on
      entity_id: light.shelly_diningtable
