- alias: people_not_home
  trigger:
    - platform: state
      entity_id: group.people
      to: 'not_home'
  condition:
    - condition: state
      entity_id: input_boolean.state_sleep
      state: 'off'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.state_home
