- alias: Sleep ON
  id: sleep_on
  trigger:
    - platform: state
      entity_id: input_boolean.state_sleep
      to: 'on'
  action:
    # google volume
    - service: media_player.volume_set
      entity_id: media_player.schlafzimmer_assistent
      data_template:
        volume_level: "{{ states('input_number.schlafzimmer_assistent_volume_sleep') }}"
    - service: media_player.volume_set
      entity_id: media_player.wohnzimmer_assistent
      data_template:
        volume_level: "{{ states('input_number.wohnzimmer_assistent_volume_sleep') }}"
    # all off
    - service: script.turn_on
      entity_id: script.all_off


- alias: Sleep OFF
  id: sleep_off
  trigger:
    - platform: state
      entity_id: input_boolean.state_sleep
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.state_home
      state: 'on'
  action:
    # google
    - service: media_player.volume_set
      entity_id: media_player.schlafzimmer_assistent
      data_template:
        volume_level: "{{ states('input_number.schlafzimmer_assistent_volume_awake') }}"
    - service: media_player.volume_set
      entity_id: media_player.wohnzimmer_assistent
      data_template:
        volume_level: "{{ states('input_number.wohnzimmer_assistent_volume_awake') }}"
    - service: input_select.select_option
      data:
        entity_id: input_select.mode_livingroom_light
        option: 'Chill'
