- alias: Sleep ON
  trigger:
    - platform: state
      entity_id: input_boolean.state_sleep
      to: 'on'
  action:
    - service: script.turn_on
      entity_id: script.all_off
    # states
    - service: input_boolean.turn_off
      entity_id: input_boolean.state_workroom
    - service: input_boolean.turn_off
      entity_id: input_boolean.state_fitnessroom
    - service: input_boolean.turn_off
      entity_id: input_boolean.state_media
    # google
    - service: media_player.volume_set
      entity_id: media_player.schlafzimmer_assistent
      data:
        volume_level: 0.05
    - service: media_player.volume_set
      entity_id: media_player.wohnzimmer_assistent
      data:
        volume_level: 0

- alias: Sleep OFF
  trigger:
    - platform: state
      entity_id: input_boolean.state_sleep
      to: 'off'
  action:
    # google
    - service: media_player.volume_set
      entity_id: media_player.schlafzimmer_assistent
      data:
        volume_level: 0.1
    - service: media_player.volume_set
      entity_id: media_player.wohnzimmer_assistent
      data:
        volume_level: 0.5
    - service: input_select.select_option
      data:
        entity_id: input_select.mode_livingroom_light
        option: 'Chill'
