- alias: Sleep ON
  trigger:
    - platform: state
      entity_id: input_boolean.state_sleep
      to: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.all_off

- alias: Sleep OFF
  trigger:
    - platform: state
      entity_id: input_boolean.state_sleep
      to: 'off'
  condition:
    - condition: state
      entity_id: device_tracker.flo
      state: 'home'
  action:
    - service: switch.turn_on
      entity_id: switch.espresso
    - service: script.bedroom_light_wakeup
