- alias: Sleep ON
  trigger:
    - platform: state
      entity_id: input_boolean.state_sleep
      to: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.all_off
    - service: notify.flo
      data:
        message: 'state.sleep.on'
