home:
  sequence:
    # states
    - service: input_boolean.turn_on
      entity_id: input_boolean.state_home
    - service: input_boolean.turn_off
      entity_id: input_boolean.state_sleep
    # light
    - condition: and
      conditions: !include ../../condition/light_livingroom.yaml
    - service: light.turn_on
      entity_id: light.light_door
    - service: light.turn_on
      entity_id: light.floor
