not_home:
  sequence:
    - service: light.turn_off
      entity_id: light.light_door_light
    # delay
    - delay:
        minutes: 10
    # no people home
    - condition: state
      entity_id: group.people
      state: 'not_home'
    # no sleep
    - condition: state
      entity_id: input_boolean.state_sleep
      state: 'off'
    # states
    - service: input_boolean.turn_off
      entity_id: input_boolean.state_home
