- name: livingroom_bass
  state_topic: "homie/livingroom-bass/switch/state"
  command_topic: "homie/livingroom-bass/switch/state/set"
  retain: true

- name: espresso
  state_topic: "homie/espresso/switch/state"
  command_topic: "homie/espresso/switch/state/set"
  retain: true

- name: humidifier
  state_topic: "homie/livingroom-steamer/switch/state"
  command_topic: "homie/livingroom-steamer/switch/state/set"
  retain: true

- name: resin
  state_topic: "homie/resin/switch/state"
  command_topic: "homie/resin/switch/state/set"
  retain: true
