- type: vertical-stack
  cards:

    # Wasser (7d)
    - type: 'custom:mini-graph-card'
      name: Wasser (7d)
      entities:
        - entity: sensor.plant1_moisture
          name: Busch
          show_points: false
        - entity: sensor.plant2_moisture
          name: Baum
          show_points: false
        - entity: sensor.plant3_moisture
          name: Rosmarin
          show_points: false
      animate: true
      height: 190
      line_width: 4
      decimals: 0
      hour24: true
      hours_to_show: 168
      points_per_hour: 0.1
      lower_bound: 0
      upper_bound: 100
      show:
        icon_adaptive_color: true
        extrema: true
        average: true
      color_thresholds:
        - value: 20
          color: '#ff0000'
        - value: 40
          color: '#00ff00'
        - value: 60
          color: '#00ff00'
        - value: 80
          color: '#0000ff'

    # Dünger (7d)
    - type: 'custom:mini-graph-card'
      name: Dünger (7d)
      entities:
        - entity: sensor.plant1_conductivity
          name: Busch
          show_points: false
        - entity: sensor.plant2_conductivity
          name: Baum
          show_points: false
        - entity: sensor.plant3_conductivity
          name: Rosmarin
          show_points: false
      animate: true
      height: 190
      line_width: 4
      decimals: 0
      hour24: true
      hours_to_show: 168
      points_per_hour: 0.1
      lower_bound: 0
      upper_bound: 3000
      show:
        icon_adaptive_color: true
        extrema: true
        average: true
      color_thresholds:
        - value: 300
          color: '#ff0000'
        - value: 800
          color: '#00ff00'
        - value: 2000
          color: '#00ff00'
        - value: 2500
          color: '#0000ff'
