light:
  name: Wohnung
  entities:
    - light.floor
    - light.kitchen
    - group.light_livingroom
    - light.bedroom
    - light.wc
    - light.badroom

light_livingroom:
  name: Wohnzimmer
  entities:
    - light.livingroom_back
    - light.livingroom_led_top
    - light.livingroom_led_top_front
    - light.livingroom_led_top_back
    - light.livingroom_back_small
    - light.livingroom_front
    - light.rainbow

motion:
  name: Bewegungsmelder
  entities:
    - binary_sensor.floor_motion
    - binary_sensor.kitchen_motion
    - binary_sensor.livingroom_motion
    - binary_sensor.wc_motion
    - binary_sensor.badroom_motion

people:
  name: Leute
  entities:
    - device_tracker.f1e84262_flo
    - device_tracker.louisa
    - device_tracker.myrtha
    - device_tracker.ries
    - device_tracker.bri
    - device_tracker.gubi

media:
  name: Media
  control: hidden
  entities:
    - input_select.media_power
    - input_select.media_channel
    - script.ir_receiver_power
    - script.ir_beamer_power_on
    - script.ir_beamer_power_off
    - script.ir_receiver_vol_up
    - script.ir_receiver_vol_down
    - switch.livingroom_bass

states:
  name: Zustände
  entities:    
    - binary_sensor.sleep
    - input_boolean.sleep

weather:
  name: Wetter
  entities:
    - sun.sun
    - sensor.yr_symbol
    - sensor.yr_temperature
    - sensor.yr_humidity
    - sensor.yr_cloudiness
    - sensor.yr_wind_speed
    - sensor.yr_wind_direction
    - sensor.yr_pressure

flat:
  name: Wohnung
  entities:
    - sensor.livingroom_temperature
    - sensor.livingroom_humidity
    - sensor.kitchen_temperature
    - sensor.kitchen_humidity
    - sensor.mold_indicator
    - switch.livingroom_humidifier
    - switch.resin

scenes:
  name: Scenes
  entities:
    - script.scene_ambient
    - script.scene_media
    - script.scene_pause
