default_viewf:
  view: yes
  entities:
    - group.wetter
    - group.sound
    - group.licht
    - group.leute

licht:
  name: Licht
  entities:
    - light.kitchen
    - light.rainbow
    - light.livingroom_back
    - light.livingroom_front
    - light.bedroom

leute:
  entities:
    - device_tracker.flo
    - device_tracker.louisa
    - device_tracker.myrtha
    - device_tracker.ries
    - device_tracker.bri
    - device_tracker.gubi

sound:
  entities:
    - switch.livingroom_bass

wetter:
  entities:
    - sun.sun
    - sensor.yr_symbol
    - sensor.yr_temperature
    - sensor.yr_humidity
    - sensor.yr_cloudiness
    - sensor.yr_wind_speed
    - sensor.yr_wind_direction
    - sensor.yr_pressure
