default_view2:
  view: yes
  entities:
    - group.light
    - group.media
    - group.motion
    - group.people
    - group.states
    - group.flat
    - group.weather

light:
  name: Licht
  entities:
    - light.floor
    - light.kitchen
    - light.rainbow
    - light.livingroom_led_top
    - light.livingroom_back
    - light.livingroom_front
    - light.bedroom
    - light.wc

motion:
  name: Bewegungsmelder
  entities:
    - binary_sensor.floor_motion
    - binary_sensor.kitchen_motion
    - binary_sensor.wc_motion

people:
  name: Leute
  entities:
    - device_tracker.f1e84262_flo
    - device_tracker.eefa3116_louisa
    - device_tracker.myrtha
    - device_tracker.ries
    - device_tracker.bri
    - device_tracker.gubi

media:
  entities:
    - input_select.media_power
    - input_select.media_channel
    - script.ir_receiver_power
    - script.ir_beamer_power_on
    - script.ir_beamer_power_off
    - script.ir_receiver_vol_up
    - script.ir_receiver_vol_down
    - switch.livingroom_bass

states:
  name: Zustände
  entities:
    - binary_sensor.sleep

weather:
  name: Wetter
  entities:
    - sun.sun
    - sensor.yr_symbol
    - sensor.yr_temperature
    - sensor.yr_humidity
    - sensor.yr_cloudiness
    - sensor.yr_wind_speed
    - sensor.yr_wind_direction
    - sensor.yr_pressure

flat:
  name: Wohnung
  entities:
    - sensor.flat_temperature
    - sensor.flat_humidity
