default_viewf:
  view: yes
  entities:
    - group.weather
    - group.sound
    - group.light
    - group.people

light:
  name: Licht
  entities:
    - light.floor
    - light.kitchen
    - light.rainbow
    - light.livingroom_led_top
    - light.livingroom_back
    - light.livingroom_front
    - light.bedroom
    - light.wc

motion:
  name: Bewegungsmelder
  entities:
    - binary_sensor.floor_motion
    - binary_sensor.kitchen_motion
    - binary_sensor.wc_motion

people:
  name: Leute
  entities:
    - device_tracker.f1e84262_flo
    - device_tracker.louisa
    - device_tracker.myrtha
    - device_tracker.ries
    - device_tracker.bri
    - device_tracker.gubi

sound:
  entities:
    - switch.livingroom_bass

states:
  name: Zustände
  entities:
    - binary_sensor.sleep

weather:
  name: Wetter
  entities:
    - sun.sun
    - sensor.yr_symbol
    - sensor.yr_temperature
    - sensor.yr_humidity
    - sensor.yr_cloudiness
    - sensor.yr_wind_speed
    - sensor.yr_wind_direction
    - sensor.yr_pressure

house:
  name: Wohnung
  entities:
    - sensor.flat_temperature
    - sensor.flat_humidity
