espresso_view:
  view: yes
  name: Espresso
  entities:
    - group.machine
    - group.mill
    - group.mill_config

machine:
  name: Maschine
  entities:
    - switch.espresso
    - sensor.espresso_temperature
    - sensor.espresso_humidity

mill:
  name: Mühle
  entities:
    - switch.mill
    - sensor.mill_seconds
    - input_slider.mill_seconds
    - input_slider.mill_current_g
    - input_slider.mill_g
