espresso:
  name: Espresso
  entities:
    - switch.espresso

mill:
  name: Mühle
  entities:
    - switch.mill
    - sensor.mill_seconds
    - input_slider.mill_seconds
    - input_slider.mill_current_g
    - input_slider.mill_g
