states:
  name: Zustände
  entities:
    - script.all_off
    - input_boolean.state_home
    - input_boolean.state_sleep
    - input_boolean.state_media

vacuum:
  name: Staubsauger
  entities:
    - vacuum.xiaomi_vacuum
    - script.vacuum_kitchen
    - script.vacuum_livingroom
    - script.vacuum_livingroom_table
