livingroom_light:
  name: Licht
  entities:
    - input_select.state_livingroom_light
    - binary_sensor.motion_livingroom_1_occupancy
    - sensor.motion_livingroom_1_illuminance
    - binary_sensor.motion_livingroom_2_occupancy
    - sensor.motion_livingroom_2_illuminance
    - light.livingroom_rainbow
    - light.livingroom_front
    - light.livingroom_big
    - light.livingroom_sofatable
    - light.livingroom_led_rgb
    - light.livingroom_led_white_front
    - light.livingroom_led_white_back

livingroom_devices:
  name: Geräte
  control: hidden
  entities:
    - switch.resin
    - switch.humidifier
    - switch.ps4

livingroom_sensors:
  name: Sensors
  control: hidden
  entities:
    - sensor.temperature_livingroom
    - sensor.humidity_livingroom

livingroom_media:
  name: Media
  control: hidden
  entities:
    - script.media_power_on
    - script.media_power_off
    - switch.livingroom_bass
    - script.ir_receiver_vol_up
    - script.ir_receiver_vol_down

livingroom_scenes:
  name: Scenes
  control: hidden
  entities:
    - input_select.mode_livingroom_light
    - scene.livingroom_ambient
    - scene.livingroom_bright
    - scene.livingroom_beamer
    - scene.livingroom_beamer_bright
    - scene.livingroom_film
