zigbee_battery:
  name: ZigBee Batterie
  control: hidden
  entities:
    - sensor.sensor_door_battery
    - sensor.motion_livingroom_1_battery
    - sensor.motion_livingroom_2_battery
    - sensor.motion_workroom_battery
    - sensor.switch_livingroom_battery
    - sensor.switch_door_battery
    - sensor.dimmer_battery
