vacuum_livingroom_table:
  sequence:
    - service: vacuum.xiaomi_clean_zone
      data_template:
        entity_id: vacuum.xiaomi_vacuum
        repeats: 2
        zone:
          - [25952,18015,28352,19765]
