vacuum_point:
  mode: restart
  fields:
    x:
      required: true
      default: 32300
      selector:
        text:
    y:
      required: true
      default: 26550
      selector:
        text:
  sequence:
    - service: script.vacuum_ensure_notcleaning
    - service: xiaomi_miio.vacuum_goto
      entity_id: vacuum.staubi
      data:
        x_coord: >
          {{ x }}
        y_coord: >
          {{ y }}

vacuum_point_kitchen:
  mode: restart
  sequence:
    - service: script.vacuum_point
      data:
        x: 32300
        y: 26550
