vacuum_point:
  mode: restart
  sequence:
    - service: script.vacuum_ensure_notcleaning
    - service: xiaomi_miio.vacuum_goto
      entity_id: vacuum.staubi
      data:
        x_coord: >
          {{ x }}
        y_coord: >
          {{ y }}

vacuum_point_kitchen:
  mode: restart
  sequence:
    - service: script.vacuum_point
      data:
        x: 32300
        y: 26550
