vacuum_room:
  mode: restart
  sequence:
    - service: script.vacuum_ensure_notcleaning
    - service: vacuum.send_command
      entity_id: vacuum.staubi
      data:
        command: app_segment_clean
        params:
          - segments: >
              {% set segmentIds = namespace(x=[]) %}
              {% for room in rooms  %}
                {% set segmentIds.x = segmentIds.x + [states('input_number.vacuum_room_'+room) | int] %}
              {% endfor %}
              {{segmentIds.x}}
            repeat: >
              {{ repeat }}

vacuum_room_kitchen:
  mode: restart
  sequence:
    - service: script.vacuum_room
      data:
        rooms:
          - kitchen
        repeat: 2
