vacuum_ensure_notcleaning:
  mode: restart
  sequence:
    - if:
        - not:
          - condition: state
            entity_id: vacuum.staubi
            state: 'docked'
      then:
        - service: vacuum.stop
          entity_id: vacuum.staubi
        - delay:
            seconds: 3
