all_off:
  sequence:
    # entities
    - service: light.turn_off
      entity_id: all
    - service: switch.turn_off
      entity_id: switch.espresso
    - service: input_select.select_option
      data:
        entity_id: input_select.state_livingroom_light
        option: Aus
    # states
    - service: input_boolean.turn_off
      entity_id: input_boolean.state_workroom
    - service: input_boolean.turn_off
      entity_id: input_boolean.state_fitnessroom
    - service: input_boolean.turn_off
      entity_id: input_boolean.state_media
    # music
    - service: script.music_turn_off
    # tv off
    - service: notify.google_assistant
      data:
        message: "turn off schlafzimmer tv"
