all_off:
  sequence:
    - service: light.turn_off
      entity_id: all
    - service: switch.turn_off
      entity_id: all
    - service: input_select.select_option
      data:
        entity_id: input_select.state_livingroom_light
        option: Aus'
