all_off:
  mode: restart
  sequence:
    # entities
    - service: switch.turn_off
      entity_id: switch.espresso
    - service: input_select.select_option
      data:
        entity_id: input_select.state_livingroom_light
        option: Aus
    # music
    - service: script.music_turn_off
    # lights
    - service: script.all_lights_off
      continue_on_error: true
    # tv
    - service: switch.turn_off
      entity_id: switch.livingroom_tv_relay


all_lights_off:
  mode: restart
  fields:
    exclude_entity_ids:
      description: entity_ids to exclude
  sequence:
    - variables:
        light_entities: >
          {{
            states.light
              | selectattr('state', 'eq', 'on')
              | rejectattr('entity_id', 'in', exclude_entity_ids)
              | map(attribute='entity_id')
              | list
          }}
    - condition: template
      value_template: "{{ (light_entities | count) > 0}}"
    - repeat:
        for_each: "{{ light_entities }}"
        sequence:
          - service: light.turn_off
            continue_on_error: true
            data_template:
              entity_id: "{{ repeat.item }}"
