all_off:
  mode: restart
  sequence:
    # entities
    - service: switch.turn_off
      entity_id: switch.espresso
    - service: input_select.select_option
      data:
        entity_id: input_select.state_livingroom_light
        option: Aus
    # states
    - service: input_boolean.turn_off
      entity_id: input_boolean.state_workroom
    - service: input_boolean.turn_off
      entity_id: input_boolean.state_fitnessroom
    # tv
    - service: switch.turn_off
      entity_id: switch.livingroom_tv_relay
    # music
    - service: script.turn_on
      entity_id: script.music_turn_off
    # lights
    - service: script.turn_on
      entity_id: script.all_lights_off


all_lights_off:
  mode: restart
  fields:
    exclude_entity_ids:
      description: entity_ids to exclude
  sequence:
    - service: light.turn_off
      continue_on_error: true
      target:
        entity_id: >
          {{
            states.light
              | selectattr('state', 'eq', 'on')
              | rejectattr('entity_id', 'in', exclude_entity_ids)
              | map(attribute='entity_id')
              | join(', ')
          }}
