all_off:
  sequence:
    # entities
    - service: switch.turn_off
      entity_id: switch.espresso
    - service: input_select.select_option
      data:
        entity_id: input_select.state_livingroom_light
        option: Aus
    # states
    - service: input_boolean.turn_off
      entity_id: input_boolean.state_workroom
    - service: input_boolean.turn_off
      entity_id: input_boolean.state_fitnessroom
    # tv
    - service: switch.turn_off
      entity_id: switch.livingroom_tv_relay
    # music
    - service: script.turn_on
      entity_id: script.music_turn_off
    # lights
    - service: light.turn_off
      entity_id: all
