home:
  sequence:
    - service: input_boolean.turn_on
      entity_id: input_boolean.state_home
    - service: input_boolean.turn_off
      entity_id: input_boolean.state_sleep
    - condition: and
      conditions: !include ../condition/light.nosleep.yaml
    - service: light.turn_on
      entity_id: light.floor
