livingroom_led_top_brightness_max:
    sequence:
      - service: light.turn_on
        entity_id: light.livingroom_led_top
        data:
          brightness: 255


livingroom_led_top_brightness_medium:
    sequence:
      - service: light.turn_on
        entity_id: light.livingroom_led_top
        data:
          brightness: 125


livingroom_led_top_brightness_low:
    sequence:
      - service: light.turn_on
        entity_id: light.livingroom_led_top
        data:
          brightness: 10


livingroom_led_top_rainbow:
  sequence:
    - service: light.turn_on
      entity_id: light.livingroom_led_top
      data:
        effect: "rainbow"
        transition: 300


livingroom_led_top_rainbow_light:
  sequence:
    - service: light.turn_on
      entity_id: light.livingroom_led_top
      data:
        effect: "rainbow-light"
        transition: 300


livingroom_led_top_rainbow_low:
  sequence:
    - service: script.livingroom_led_top_brightness_low
    - service: script.livingroom_led_top_rainbow


livingroom_led_top_rainbow_light_low:
  sequence:
    - service: script.livingroom_led_top_brightness_low
    - service: script.livingroom_led_top_rainbow_light


livingroom_led_top_rainbow_max:
  sequence:
    - service: script.livingroom_led_top_brightness_max
    - service: script.livingroom_led_top_rainbow


livingroom_led_top_rainbow_light_max:
  sequence:
    - service: script.livingroom_led_top_brightness_max
    - service: script.livingroom_led_top_rainbow_light
