# light_livingroom_led_rgb_rainbow:
#   sequence:
#     - service: light.turn_on
#       entity_id: light.livingroom_led_rgb
#       data:
#         effect: "rainbow"
#         transition: 300


# light_livingroom_led_rgb_rainbow_light:
#   sequence:
#     - service: light.turn_on
#       entity_id: light.livingroom_led_rgb
#       data:
#         effect: "rainbow-light"
#         transition: 300
