media_power_on:
  sequence:
    # disable off script
    - service: script.turn_off
      entity_id: script.media_power_off
    
    # scene beamer bright
    - service: input_select.select_option
      data:
        entity_id: input_select.state_livingroom_light
        option: Beamer Hell
    
    # turn on devices
    - service: script.ir_receiver_tv
    - delay:
        seconds: 1
    - service: script.ir_beamer_power_on
    - delay:
        seconds: 3
    - service: script.ir_receiver_tv
    - delay:
        seconds: 1
    - service: script.ir_beamer_power_on
    - delay:
        seconds: 3
    - service: script.ir_receiver_tv
    - delay:
        seconds: 1
    - service: script.ir_beamer_power_on
    - delay:
        seconds: 20
    
    - service: switch.turn_on
      entity_id: switch.livingroom_bass
    
    # scene beamer
    - service: input_select.select_option
      data:
        entity_id: input_select.state_livingroom_light
        option: Beamer


media_power_off:
  sequence:
    # disable off script
    - service: script.turn_off
      entity_id: script.media_power_on

    # scene
    - service: input_select.select_option
      data:
        entity_id: input_select.state_livingroom_light
        option: Normal

    # turn off devices
    - service: switch.turn_off
      entity_id: switch.livingroom_bass
      
    - service: script.ir_receiver_tv
    - delay:
        seconds: 1
    - service: script.ir_receiver_power
    - delay:
        seconds: 1
    - service: script.ir_beamer_power_off
    - delay:
        seconds: 10
    - service: script.ir_beamer_power_off
    - delay:
        minutes: 1
    - service: script.ir_beamer_power_off
