media_power_on:
  sequence:
    # disable off script
    - service: script.turn_off
      entity_id: script.media_power_off
    
    # scene beamer bright
    - service: input_select.select_option
      data:
        entity_id: input_select.state_livingroom_light
        option: Beamer Hell
    
    # turn on devices
    - service: script.turn_on
      entity_id:
        - script.receiver_on
        - script.beamer_on

    - delay:
        seconds: 30
    
    # scene beamer
    - service: input_select.select_option
      data:
        entity_id: input_select.state_livingroom_light
        option: Beamer


media_power_off:
  sequence:
    # disable off script
    - service: script.turn_off
      entity_id: script.media_power_on

    # scene
    - service: input_select.select_option
      data:
        entity_id: input_select.state_livingroom_light
        option: Chill

    # turn off devices
    - service: media_player.turn_off
      entity_id: media_player.playstation_4
    - service: media_player.turn_off
      entity_id: media_player.shield
    - service: script.turn_on
      entity_id:
        - script.receiver_off
        - script.beamer_off

receiver_on:
  sequence:
    # disable off script
    - service: script.turn_off
      entity_id: script.receiver_off

    - service: script.ir_receiver_tv
    - delay:
        seconds: 3
    - service: script.ir_receiver_tv
    - delay:
        seconds: 3
    - service: script.ir_receiver_tv

receiver_off:
  sequence:
    # disable off script
    - service: script.turn_off
      entity_id: script.receiver_off_internal
    - delay:
        seconds: 5
    - service: script.receiver_off_internal

receiver_off_internal:
  sequence:
    # disable on script
    - service: script.turn_off
      entity_id: script.receiver_on

    - service: script.ir_receiver_power
    - delay:
        seconds: 10
    - service: script.ir_receiver_tv
    - delay:
        seconds: 10
    - service: script.ir_receiver_power

beamer_on:
  sequence:
    # disable off script
    - service: script.turn_off
      entity_id: script.beamer_off

    - service: script.ir_beamer_power_on
    - delay:
        seconds: 3
    - service: script.ir_beamer_power_on
    - delay:
        seconds: 3
    - service: script.ir_beamer_power_on

beamer_off:
  sequence:
    # disable on script
    - service: script.turn_off
      entity_id: script.beamer_on

    - service: script.ir_beamer_power_off
    - delay:
        seconds: 3
    - service: script.ir_beamer_power_off
    - delay:
        seconds: 3
    - service: script.ir_beamer_power_off
