not_home:
  sequence:
    # delay
    - delay:
        minutes: 10
    # no people home
    - condition: state
      entity_id: group.people
      state: 'not_home'
    # states
    - service: input_boolean.turn_off
      entity_id: input_boolean.state_home
    - service: input_boolean.turn_off
      entity_id: input_boolean.state_sleep
