notify_google:
  sequence:
    # - service: media_player.media_stop
    #   entity_id: media_player.home_group

    # # livingroom
    # - service: media_player.volume_set
    #   entity_id: media_player.googlehome4508
    #   data:
    #     volume_level: 0.7

    # # bedroom
    # - service: media_player.volume_set
    #   entity_id: media_player.googlehome7490
    #   data:
    #     volume_level: 0.7

    # - service: tts.google_say
    #   entity_id: media_player.home_group
    #   data_template:
    #     language: '{{ language }}'
    #     message: '{{ message }}'

    - service: notify.google
      data_template:
        message: '{{ message }}'

    # - delay:
    #     seconds: 5

    # # livingroom
    # - service: media_player.volume_set
    #   entity_id: media_player.googlehome4508
    #   data:
    #     volume_level: 0.4

    # # bedroom
    # - service: media_player.volume_set
    #   entity_id: media_player.googlehome7490
    #   data:
    #     volume_level: 0.2
