notify_google:
  sequence:
    - service: media_player.volume_up
      entity_id: media_player.home_group
    - service: media_player.volume_up
      entity_id: media_player.home_group
    - service: media_player.volume_up
      entity_id: media_player.home_group
    - service: media_player.volume_up
      entity_id: media_player.home_group
    - service: media_player.volume_up
      entity_id: media_player.home_group

    - service: tts.google_say
      entity_id: media_player.home_group
      data_template:
        language: '{{ language }}'
        message: '{{ message }}'

    - delay:
        seconds: 5

    - service: media_player.volume_down
      entity_id: media_player.home_group
    - service: media_player.volume_down
      entity_id: media_player.home_group
    - service: media_player.volume_down
      entity_id: media_player.home_group
    - service: media_player.volume_down
      entity_id: media_player.home_group
    - service: media_player.volume_down
      entity_id: media_player.home_group
