notify_google:
  sequence:
    - service: media_player.volume_set
      entity_id: media_player.home_group
      data:
        volume_level: 0.6

    - service: tts.google_say
      entity_id: media_player.home_group
      data_template:
        language: '{{ language }}'
        message: '{{ message }}'

    - delay:
        seconds: 5

    - service: media_player.volume_set
      entity_id: media_player.home_group
      data:
        volume_level: 0.2
