scene_ambient:
  sequence:
    - condition: and
      conditions: !include ../conditions/night.yaml
    - service: scene.turn_on
      entity_id: scene.ambient
    - service: script.livingroom_led_top_rainbow_light

scene_pause:
  sequence:
    - condition: and
      conditions: !include ../conditions/night.yaml
    - service: scene.turn_on
      entity_id: scene.pause
    - service: script.livingroom_led_top_rainbow_light

scene_media:
  sequence:
    - condition: and
      conditions: !include ../conditions/night.yaml
    - service: scene.turn_on
      entity_id: scene.media
    - service: script.livingroom_led_top_rainbow_light_low

scene_livingroom_off:
  sequence:
    - service: scene.turn_on
      entity_id: scene.livingroom_off

scene_all_off:
  sequence:
    - service: scene.turn_on
      entity_id: scene.all_off

scene_all_on:
  sequence:
    - service: scene.turn_on
      entity_id: scene.all_on
    - service: script.livingroom_led_top_rainbow

scene_night:
  sequence:
    - service: scene.turn_on
      entity_id: scene.night

scene_floor_ambient:
  sequence:
    - service: light.turn_on
      entity_id: light.floor
