loop:
  sequence:
    - service: script.turn_off
      data_template:
        entity_id: "script.{{ script }}"
    - service: script.turn_on
      data_template:
        entity_id: "script.{{ script }}"
