- alias: wohnzimmer_tv_on
  id: wohnzimmer_tv_on
  trigger:
    - platform: state
      entity_id: media_player.wohnzimmer_tv
      to: 'on'
  action:
    - service: script.livingroom_light
      data:
        mode: TV
    - service: script.receiver_on

- alias: wohnzimmer_tv_off
  id: wohnzimmer_tv_off
  trigger:
    - platform: state
      entity_id: media_player.wohnzimmer_tv
      from: 'on'
  action:
    - service: script.livingroom_light
      data:
        mode: Normal
    - service: script.turn_on
      entity_id: script.receiver_off
