####################  Sunrise  ####################
- type: entities
  title: Sunrise
  show_header_toggle: false
  entities:
    - type: 'custom:multiple-entity-row'
      entity: input_boolean.sunrise_enabled
      name: Sunrise
      toggle: true
      entities:
        - entity: input_datetime.sunrise_time
          name: Zeit
        - entity: input_boolean.sunrise_weekend
          name: Wochenende


####################  Assistent Volume  ####################
- type: entities
  title: Assistent Lautstärke
  entities:
    - type: custom:slider-entity-row
      entity: input_number.wohnzimmer_assistent_volume_awake
      name: Wohnzimmer
      grow: true
    - type: custom:slider-entity-row
      entity: input_number.schlafzimmer_assistent_volume_awake
      name: Schlafzimmer
      grow: true
    - type: custom:slider-entity-row
      entity: input_number.wohnzimmer_assistent_volume_sleep
      name: Wohnzimmer (Nacht)
      grow: true
    - type: custom:slider-entity-row
      entity: input_number.schlafzimmer_assistent_volume_sleep
      name: Schlafzimmer (Nacht)
      grow: true


####################  Battery  ####################
- type: custom:battery-state-card
  title: Batterie
  entities:
    - entity: sensor.motion_livingroom_battery
      name: Bewegung Wohnzimmer
    - entity: sensor.motion_workroom_battery
      name: Bewegung Büro
    - entity: sensor.motion_fitnessroom_battery
      name: Bewegung Fitnesszimmer
    - entity: sensor.motion_bathroom_battery
      name: Bewegung Bad
    - entity: sensor.sensor_door_battery
      name: Türe
    - entity: sensor.switch_livingroom_battery
      name: Schalter Wohnzimmer
    - entity: sensor.switch_door_battery
      name: Schalter Eingang
    - entity: sensor.switch_bedroom_battery
      name: Schalter Schlafzimmer
    - entity: sensor.plant1_battery
      name: Pflanze Busch
    - entity: sensor.plant2_battery
      name: Pflanze Baum
    - entity: sensor.plant3_battery
      name: Pflanze Rosmarin


####################  Media  ####################
- type: entities
  title: Media
  entities:
    - entity: input_text.radio_srf4
    - entity: input_text.playlist_chill
    - entity: input_text.playlist_electro
    - entity: input_text.playlist_charts
